/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BillCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillCreateRequest{}

// BillCreateRequest struct for BillCreateRequest
type BillCreateRequest struct {
	Date *string `json:"date,omitempty"`
	// The language ISO code by ISO 639-1.
	Language string `json:"language"`
	// Currency code (ISO 4217)
	Currency      string                                `json:"currency"`
	DueAfterDays  int32                                 `json:"dueAfterDays"`
	Recipient     BillCreateRequestRecipient            `json:"recipient"`
	ServicePeriod *BillCreateRequestServicePeriod       `json:"servicePeriod,omitempty"`
	Discount      *BillCreateRequestDiscount            `json:"discount,omitempty"`
	CashDiscounts []BillCreateRequestCashDiscountsInner `json:"cashDiscounts,omitempty"`
	// Amount in the smallest unit of the currency.
	ShippingCost *int32 `json:"shippingCost,omitempty"`
	// Amount in the smallest unit of the currency.
	ApplicationFee  *int32                              `json:"applicationFee,omitempty"`
	Note            *string                             `json:"note,omitempty"`
	Terms           *string                             `json:"terms,omitempty"`
	Positions       []BillCreateRequestPositionsInner   `json:"positions"`
	Attachments     []BillCreateRequestAttachmentsInner `json:"attachments,omitempty"`
	BankInformation *BillCreateRequestBankInformation   `json:"bankInformation,omitempty"`
	// This payout descriptor is added to the payout statement (Only for Payrexx Swiss Collecting payments and single transaction payouts). Max. 80 chars.
	PayoutDescriptor *string                           `json:"payoutDescriptor,omitempty"`
	Psp              []int32                           `json:"psp,omitempty"`
	Pm               []string                          `json:"pm,omitempty"`
	Reminders        []BillCreateRequestRemindersInner `json:"reminders,omitempty"`
	Reference        *string                           `json:"reference,omitempty"`
	Design           *string                           `json:"design,omitempty"`
	// Whether to send the invoice.
	Send *bool `json:"send,omitempty"`
	// Send invoice to additional recipients. Pass email addresses as Strings.
	AdditionalRecipients []string `json:"additionalRecipients,omitempty"`
	// Whether to complete the invoice.
	Complete *bool `json:"complete,omitempty"`
}

type _BillCreateRequest BillCreateRequest

// NewBillCreateRequest instantiates a new BillCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillCreateRequest(language string, currency string, dueAfterDays int32, recipient BillCreateRequestRecipient, positions []BillCreateRequestPositionsInner) *BillCreateRequest {
	this := BillCreateRequest{}
	this.Language = language
	this.Currency = currency
	this.DueAfterDays = dueAfterDays
	this.Recipient = recipient
	this.Positions = positions
	var send bool = false
	this.Send = &send
	var complete bool = false
	this.Complete = &complete
	return &this
}

// NewBillCreateRequestWithDefaults instantiates a new BillCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillCreateRequestWithDefaults() *BillCreateRequest {
	this := BillCreateRequest{}
	var send bool = false
	this.Send = &send
	var complete bool = false
	this.Complete = &complete
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *BillCreateRequest) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *BillCreateRequest) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *BillCreateRequest) SetDate(v string) {
	o.Date = &v
}

// GetLanguage returns the Language field value
func (o *BillCreateRequest) GetLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Language
}

// GetLanguageOk returns a tuple with the Language field value
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Language, true
}

// SetLanguage sets field value
func (o *BillCreateRequest) SetLanguage(v string) {
	o.Language = v
}

// GetCurrency returns the Currency field value
func (o *BillCreateRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *BillCreateRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetDueAfterDays returns the DueAfterDays field value
func (o *BillCreateRequest) GetDueAfterDays() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DueAfterDays
}

// GetDueAfterDaysOk returns a tuple with the DueAfterDays field value
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetDueAfterDaysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DueAfterDays, true
}

// SetDueAfterDays sets field value
func (o *BillCreateRequest) SetDueAfterDays(v int32) {
	o.DueAfterDays = v
}

// GetRecipient returns the Recipient field value
func (o *BillCreateRequest) GetRecipient() BillCreateRequestRecipient {
	if o == nil {
		var ret BillCreateRequestRecipient
		return ret
	}

	return o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetRecipientOk() (*BillCreateRequestRecipient, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recipient, true
}

// SetRecipient sets field value
func (o *BillCreateRequest) SetRecipient(v BillCreateRequestRecipient) {
	o.Recipient = v
}

// GetServicePeriod returns the ServicePeriod field value if set, zero value otherwise.
func (o *BillCreateRequest) GetServicePeriod() BillCreateRequestServicePeriod {
	if o == nil || IsNil(o.ServicePeriod) {
		var ret BillCreateRequestServicePeriod
		return ret
	}
	return *o.ServicePeriod
}

// GetServicePeriodOk returns a tuple with the ServicePeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetServicePeriodOk() (*BillCreateRequestServicePeriod, bool) {
	if o == nil || IsNil(o.ServicePeriod) {
		return nil, false
	}
	return o.ServicePeriod, true
}

// HasServicePeriod returns a boolean if a field has been set.
func (o *BillCreateRequest) HasServicePeriod() bool {
	if o != nil && !IsNil(o.ServicePeriod) {
		return true
	}

	return false
}

// SetServicePeriod gets a reference to the given BillCreateRequestServicePeriod and assigns it to the ServicePeriod field.
func (o *BillCreateRequest) SetServicePeriod(v BillCreateRequestServicePeriod) {
	o.ServicePeriod = &v
}

// GetDiscount returns the Discount field value if set, zero value otherwise.
func (o *BillCreateRequest) GetDiscount() BillCreateRequestDiscount {
	if o == nil || IsNil(o.Discount) {
		var ret BillCreateRequestDiscount
		return ret
	}
	return *o.Discount
}

// GetDiscountOk returns a tuple with the Discount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetDiscountOk() (*BillCreateRequestDiscount, bool) {
	if o == nil || IsNil(o.Discount) {
		return nil, false
	}
	return o.Discount, true
}

// HasDiscount returns a boolean if a field has been set.
func (o *BillCreateRequest) HasDiscount() bool {
	if o != nil && !IsNil(o.Discount) {
		return true
	}

	return false
}

// SetDiscount gets a reference to the given BillCreateRequestDiscount and assigns it to the Discount field.
func (o *BillCreateRequest) SetDiscount(v BillCreateRequestDiscount) {
	o.Discount = &v
}

// GetCashDiscounts returns the CashDiscounts field value if set, zero value otherwise.
func (o *BillCreateRequest) GetCashDiscounts() []BillCreateRequestCashDiscountsInner {
	if o == nil || IsNil(o.CashDiscounts) {
		var ret []BillCreateRequestCashDiscountsInner
		return ret
	}
	return o.CashDiscounts
}

// GetCashDiscountsOk returns a tuple with the CashDiscounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetCashDiscountsOk() ([]BillCreateRequestCashDiscountsInner, bool) {
	if o == nil || IsNil(o.CashDiscounts) {
		return nil, false
	}
	return o.CashDiscounts, true
}

// HasCashDiscounts returns a boolean if a field has been set.
func (o *BillCreateRequest) HasCashDiscounts() bool {
	if o != nil && !IsNil(o.CashDiscounts) {
		return true
	}

	return false
}

// SetCashDiscounts gets a reference to the given []BillCreateRequestCashDiscountsInner and assigns it to the CashDiscounts field.
func (o *BillCreateRequest) SetCashDiscounts(v []BillCreateRequestCashDiscountsInner) {
	o.CashDiscounts = v
}

// GetShippingCost returns the ShippingCost field value if set, zero value otherwise.
func (o *BillCreateRequest) GetShippingCost() int32 {
	if o == nil || IsNil(o.ShippingCost) {
		var ret int32
		return ret
	}
	return *o.ShippingCost
}

// GetShippingCostOk returns a tuple with the ShippingCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetShippingCostOk() (*int32, bool) {
	if o == nil || IsNil(o.ShippingCost) {
		return nil, false
	}
	return o.ShippingCost, true
}

// HasShippingCost returns a boolean if a field has been set.
func (o *BillCreateRequest) HasShippingCost() bool {
	if o != nil && !IsNil(o.ShippingCost) {
		return true
	}

	return false
}

// SetShippingCost gets a reference to the given int32 and assigns it to the ShippingCost field.
func (o *BillCreateRequest) SetShippingCost(v int32) {
	o.ShippingCost = &v
}

// GetApplicationFee returns the ApplicationFee field value if set, zero value otherwise.
func (o *BillCreateRequest) GetApplicationFee() int32 {
	if o == nil || IsNil(o.ApplicationFee) {
		var ret int32
		return ret
	}
	return *o.ApplicationFee
}

// GetApplicationFeeOk returns a tuple with the ApplicationFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetApplicationFeeOk() (*int32, bool) {
	if o == nil || IsNil(o.ApplicationFee) {
		return nil, false
	}
	return o.ApplicationFee, true
}

// HasApplicationFee returns a boolean if a field has been set.
func (o *BillCreateRequest) HasApplicationFee() bool {
	if o != nil && !IsNil(o.ApplicationFee) {
		return true
	}

	return false
}

// SetApplicationFee gets a reference to the given int32 and assigns it to the ApplicationFee field.
func (o *BillCreateRequest) SetApplicationFee(v int32) {
	o.ApplicationFee = &v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *BillCreateRequest) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *BillCreateRequest) HasNote() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *BillCreateRequest) SetNote(v string) {
	o.Note = &v
}

// GetTerms returns the Terms field value if set, zero value otherwise.
func (o *BillCreateRequest) GetTerms() string {
	if o == nil || IsNil(o.Terms) {
		var ret string
		return ret
	}
	return *o.Terms
}

// GetTermsOk returns a tuple with the Terms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetTermsOk() (*string, bool) {
	if o == nil || IsNil(o.Terms) {
		return nil, false
	}
	return o.Terms, true
}

// HasTerms returns a boolean if a field has been set.
func (o *BillCreateRequest) HasTerms() bool {
	if o != nil && !IsNil(o.Terms) {
		return true
	}

	return false
}

// SetTerms gets a reference to the given string and assigns it to the Terms field.
func (o *BillCreateRequest) SetTerms(v string) {
	o.Terms = &v
}

// GetPositions returns the Positions field value
func (o *BillCreateRequest) GetPositions() []BillCreateRequestPositionsInner {
	if o == nil {
		var ret []BillCreateRequestPositionsInner
		return ret
	}

	return o.Positions
}

// GetPositionsOk returns a tuple with the Positions field value
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetPositionsOk() ([]BillCreateRequestPositionsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Positions, true
}

// SetPositions sets field value
func (o *BillCreateRequest) SetPositions(v []BillCreateRequestPositionsInner) {
	o.Positions = v
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *BillCreateRequest) GetAttachments() []BillCreateRequestAttachmentsInner {
	if o == nil || IsNil(o.Attachments) {
		var ret []BillCreateRequestAttachmentsInner
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetAttachmentsOk() ([]BillCreateRequestAttachmentsInner, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *BillCreateRequest) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []BillCreateRequestAttachmentsInner and assigns it to the Attachments field.
func (o *BillCreateRequest) SetAttachments(v []BillCreateRequestAttachmentsInner) {
	o.Attachments = v
}

// GetBankInformation returns the BankInformation field value if set, zero value otherwise.
func (o *BillCreateRequest) GetBankInformation() BillCreateRequestBankInformation {
	if o == nil || IsNil(o.BankInformation) {
		var ret BillCreateRequestBankInformation
		return ret
	}
	return *o.BankInformation
}

// GetBankInformationOk returns a tuple with the BankInformation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetBankInformationOk() (*BillCreateRequestBankInformation, bool) {
	if o == nil || IsNil(o.BankInformation) {
		return nil, false
	}
	return o.BankInformation, true
}

// HasBankInformation returns a boolean if a field has been set.
func (o *BillCreateRequest) HasBankInformation() bool {
	if o != nil && !IsNil(o.BankInformation) {
		return true
	}

	return false
}

// SetBankInformation gets a reference to the given BillCreateRequestBankInformation and assigns it to the BankInformation field.
func (o *BillCreateRequest) SetBankInformation(v BillCreateRequestBankInformation) {
	o.BankInformation = &v
}

// GetPayoutDescriptor returns the PayoutDescriptor field value if set, zero value otherwise.
func (o *BillCreateRequest) GetPayoutDescriptor() string {
	if o == nil || IsNil(o.PayoutDescriptor) {
		var ret string
		return ret
	}
	return *o.PayoutDescriptor
}

// GetPayoutDescriptorOk returns a tuple with the PayoutDescriptor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetPayoutDescriptorOk() (*string, bool) {
	if o == nil || IsNil(o.PayoutDescriptor) {
		return nil, false
	}
	return o.PayoutDescriptor, true
}

// HasPayoutDescriptor returns a boolean if a field has been set.
func (o *BillCreateRequest) HasPayoutDescriptor() bool {
	if o != nil && !IsNil(o.PayoutDescriptor) {
		return true
	}

	return false
}

// SetPayoutDescriptor gets a reference to the given string and assigns it to the PayoutDescriptor field.
func (o *BillCreateRequest) SetPayoutDescriptor(v string) {
	o.PayoutDescriptor = &v
}

// GetPsp returns the Psp field value if set, zero value otherwise.
func (o *BillCreateRequest) GetPsp() []int32 {
	if o == nil || IsNil(o.Psp) {
		var ret []int32
		return ret
	}
	return o.Psp
}

// GetPspOk returns a tuple with the Psp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetPspOk() ([]int32, bool) {
	if o == nil || IsNil(o.Psp) {
		return nil, false
	}
	return o.Psp, true
}

// HasPsp returns a boolean if a field has been set.
func (o *BillCreateRequest) HasPsp() bool {
	if o != nil && !IsNil(o.Psp) {
		return true
	}

	return false
}

// SetPsp gets a reference to the given []int32 and assigns it to the Psp field.
func (o *BillCreateRequest) SetPsp(v []int32) {
	o.Psp = v
}

// GetPm returns the Pm field value if set, zero value otherwise.
func (o *BillCreateRequest) GetPm() []string {
	if o == nil || IsNil(o.Pm) {
		var ret []string
		return ret
	}
	return o.Pm
}

// GetPmOk returns a tuple with the Pm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetPmOk() ([]string, bool) {
	if o == nil || IsNil(o.Pm) {
		return nil, false
	}
	return o.Pm, true
}

// HasPm returns a boolean if a field has been set.
func (o *BillCreateRequest) HasPm() bool {
	if o != nil && !IsNil(o.Pm) {
		return true
	}

	return false
}

// SetPm gets a reference to the given []string and assigns it to the Pm field.
func (o *BillCreateRequest) SetPm(v []string) {
	o.Pm = v
}

// GetReminders returns the Reminders field value if set, zero value otherwise.
func (o *BillCreateRequest) GetReminders() []BillCreateRequestRemindersInner {
	if o == nil || IsNil(o.Reminders) {
		var ret []BillCreateRequestRemindersInner
		return ret
	}
	return o.Reminders
}

// GetRemindersOk returns a tuple with the Reminders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetRemindersOk() ([]BillCreateRequestRemindersInner, bool) {
	if o == nil || IsNil(o.Reminders) {
		return nil, false
	}
	return o.Reminders, true
}

// HasReminders returns a boolean if a field has been set.
func (o *BillCreateRequest) HasReminders() bool {
	if o != nil && !IsNil(o.Reminders) {
		return true
	}

	return false
}

// SetReminders gets a reference to the given []BillCreateRequestRemindersInner and assigns it to the Reminders field.
func (o *BillCreateRequest) SetReminders(v []BillCreateRequestRemindersInner) {
	o.Reminders = v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *BillCreateRequest) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *BillCreateRequest) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *BillCreateRequest) SetReference(v string) {
	o.Reference = &v
}

// GetDesign returns the Design field value if set, zero value otherwise.
func (o *BillCreateRequest) GetDesign() string {
	if o == nil || IsNil(o.Design) {
		var ret string
		return ret
	}
	return *o.Design
}

// GetDesignOk returns a tuple with the Design field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetDesignOk() (*string, bool) {
	if o == nil || IsNil(o.Design) {
		return nil, false
	}
	return o.Design, true
}

// HasDesign returns a boolean if a field has been set.
func (o *BillCreateRequest) HasDesign() bool {
	if o != nil && !IsNil(o.Design) {
		return true
	}

	return false
}

// SetDesign gets a reference to the given string and assigns it to the Design field.
func (o *BillCreateRequest) SetDesign(v string) {
	o.Design = &v
}

// GetSend returns the Send field value if set, zero value otherwise.
func (o *BillCreateRequest) GetSend() bool {
	if o == nil || IsNil(o.Send) {
		var ret bool
		return ret
	}
	return *o.Send
}

// GetSendOk returns a tuple with the Send field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetSendOk() (*bool, bool) {
	if o == nil || IsNil(o.Send) {
		return nil, false
	}
	return o.Send, true
}

// HasSend returns a boolean if a field has been set.
func (o *BillCreateRequest) HasSend() bool {
	if o != nil && !IsNil(o.Send) {
		return true
	}

	return false
}

// SetSend gets a reference to the given bool and assigns it to the Send field.
func (o *BillCreateRequest) SetSend(v bool) {
	o.Send = &v
}

// GetAdditionalRecipients returns the AdditionalRecipients field value if set, zero value otherwise.
func (o *BillCreateRequest) GetAdditionalRecipients() []string {
	if o == nil || IsNil(o.AdditionalRecipients) {
		var ret []string
		return ret
	}
	return o.AdditionalRecipients
}

// GetAdditionalRecipientsOk returns a tuple with the AdditionalRecipients field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetAdditionalRecipientsOk() ([]string, bool) {
	if o == nil || IsNil(o.AdditionalRecipients) {
		return nil, false
	}
	return o.AdditionalRecipients, true
}

// HasAdditionalRecipients returns a boolean if a field has been set.
func (o *BillCreateRequest) HasAdditionalRecipients() bool {
	if o != nil && !IsNil(o.AdditionalRecipients) {
		return true
	}

	return false
}

// SetAdditionalRecipients gets a reference to the given []string and assigns it to the AdditionalRecipients field.
func (o *BillCreateRequest) SetAdditionalRecipients(v []string) {
	o.AdditionalRecipients = v
}

// GetComplete returns the Complete field value if set, zero value otherwise.
func (o *BillCreateRequest) GetComplete() bool {
	if o == nil || IsNil(o.Complete) {
		var ret bool
		return ret
	}
	return *o.Complete
}

// GetCompleteOk returns a tuple with the Complete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequest) GetCompleteOk() (*bool, bool) {
	if o == nil || IsNil(o.Complete) {
		return nil, false
	}
	return o.Complete, true
}

// HasComplete returns a boolean if a field has been set.
func (o *BillCreateRequest) HasComplete() bool {
	if o != nil && !IsNil(o.Complete) {
		return true
	}

	return false
}

// SetComplete gets a reference to the given bool and assigns it to the Complete field.
func (o *BillCreateRequest) SetComplete(v bool) {
	o.Complete = &v
}

func (o BillCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	toSerialize["language"] = o.Language
	toSerialize["currency"] = o.Currency
	toSerialize["dueAfterDays"] = o.DueAfterDays
	toSerialize["recipient"] = o.Recipient
	if !IsNil(o.ServicePeriod) {
		toSerialize["servicePeriod"] = o.ServicePeriod
	}
	if !IsNil(o.Discount) {
		toSerialize["discount"] = o.Discount
	}
	if !IsNil(o.CashDiscounts) {
		toSerialize["cashDiscounts"] = o.CashDiscounts
	}
	if !IsNil(o.ShippingCost) {
		toSerialize["shippingCost"] = o.ShippingCost
	}
	if !IsNil(o.ApplicationFee) {
		toSerialize["applicationFee"] = o.ApplicationFee
	}
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}
	if !IsNil(o.Terms) {
		toSerialize["terms"] = o.Terms
	}
	toSerialize["positions"] = o.Positions
	if !IsNil(o.Attachments) {
		toSerialize["attachments"] = o.Attachments
	}
	if !IsNil(o.BankInformation) {
		toSerialize["bankInformation"] = o.BankInformation
	}
	if !IsNil(o.PayoutDescriptor) {
		toSerialize["payoutDescriptor"] = o.PayoutDescriptor
	}
	if !IsNil(o.Psp) {
		toSerialize["psp"] = o.Psp
	}
	if !IsNil(o.Pm) {
		toSerialize["pm"] = o.Pm
	}
	if !IsNil(o.Reminders) {
		toSerialize["reminders"] = o.Reminders
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	if !IsNil(o.Design) {
		toSerialize["design"] = o.Design
	}
	if !IsNil(o.Send) {
		toSerialize["send"] = o.Send
	}
	if !IsNil(o.AdditionalRecipients) {
		toSerialize["additionalRecipients"] = o.AdditionalRecipients
	}
	if !IsNil(o.Complete) {
		toSerialize["complete"] = o.Complete
	}
	return toSerialize, nil
}

func (o *BillCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"language",
		"currency",
		"dueAfterDays",
		"recipient",
		"positions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillCreateRequest := _BillCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillCreateRequest)

	if err != nil {
		return err
	}

	*o = BillCreateRequest(varBillCreateRequest)

	return err
}

type NullableBillCreateRequest struct {
	value *BillCreateRequest
	isSet bool
}

func (v NullableBillCreateRequest) Get() *BillCreateRequest {
	return v.value
}

func (v *NullableBillCreateRequest) Set(val *BillCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBillCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBillCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillCreateRequest(val *BillCreateRequest) *NullableBillCreateRequest {
	return &NullableBillCreateRequest{value: val, isSet: true}
}

func (v NullableBillCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
