/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the EcrPaymentMethod type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EcrPaymentMethod{}

// EcrPaymentMethod struct for EcrPaymentMethod
type EcrPaymentMethod struct {
	Name           *string                  `json:"name,omitempty"`
	Type           *string                  `json:"type,omitempty"`
	Group          *string                  `json:"group,omitempty"`
	OrderBy        *string                  `json:"order_by,omitempty"`
	PaymentOptions []map[string]interface{} `json:"payment_options,omitempty"`
}

// NewEcrPaymentMethod instantiates a new EcrPaymentMethod object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEcrPaymentMethod() *EcrPaymentMethod {
	this := EcrPaymentMethod{}
	return &this
}

// NewEcrPaymentMethodWithDefaults instantiates a new EcrPaymentMethod object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEcrPaymentMethodWithDefaults() *EcrPaymentMethod {
	this := EcrPaymentMethod{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EcrPaymentMethod) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EcrPaymentMethod) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EcrPaymentMethod) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EcrPaymentMethod) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *EcrPaymentMethod) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EcrPaymentMethod) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *EcrPaymentMethod) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *EcrPaymentMethod) SetType(v string) {
	o.Type = &v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *EcrPaymentMethod) GetGroup() string {
	if o == nil || IsNil(o.Group) {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EcrPaymentMethod) GetGroupOk() (*string, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *EcrPaymentMethod) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *EcrPaymentMethod) SetGroup(v string) {
	o.Group = &v
}

// GetOrderBy returns the OrderBy field value if set, zero value otherwise.
func (o *EcrPaymentMethod) GetOrderBy() string {
	if o == nil || IsNil(o.OrderBy) {
		var ret string
		return ret
	}
	return *o.OrderBy
}

// GetOrderByOk returns a tuple with the OrderBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EcrPaymentMethod) GetOrderByOk() (*string, bool) {
	if o == nil || IsNil(o.OrderBy) {
		return nil, false
	}
	return o.OrderBy, true
}

// HasOrderBy returns a boolean if a field has been set.
func (o *EcrPaymentMethod) HasOrderBy() bool {
	if o != nil && !IsNil(o.OrderBy) {
		return true
	}

	return false
}

// SetOrderBy gets a reference to the given string and assigns it to the OrderBy field.
func (o *EcrPaymentMethod) SetOrderBy(v string) {
	o.OrderBy = &v
}

// GetPaymentOptions returns the PaymentOptions field value if set, zero value otherwise.
func (o *EcrPaymentMethod) GetPaymentOptions() []map[string]interface{} {
	if o == nil || IsNil(o.PaymentOptions) {
		var ret []map[string]interface{}
		return ret
	}
	return o.PaymentOptions
}

// GetPaymentOptionsOk returns a tuple with the PaymentOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EcrPaymentMethod) GetPaymentOptionsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.PaymentOptions) {
		return nil, false
	}
	return o.PaymentOptions, true
}

// HasPaymentOptions returns a boolean if a field has been set.
func (o *EcrPaymentMethod) HasPaymentOptions() bool {
	if o != nil && !IsNil(o.PaymentOptions) {
		return true
	}

	return false
}

// SetPaymentOptions gets a reference to the given []map[string]interface{} and assigns it to the PaymentOptions field.
func (o *EcrPaymentMethod) SetPaymentOptions(v []map[string]interface{}) {
	o.PaymentOptions = v
}

func (o EcrPaymentMethod) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EcrPaymentMethod) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	if !IsNil(o.OrderBy) {
		toSerialize["order_by"] = o.OrderBy
	}
	if !IsNil(o.PaymentOptions) {
		toSerialize["payment_options"] = o.PaymentOptions
	}
	return toSerialize, nil
}

type NullableEcrPaymentMethod struct {
	value *EcrPaymentMethod
	isSet bool
}

func (v NullableEcrPaymentMethod) Get() *EcrPaymentMethod {
	return v.value
}

func (v *NullableEcrPaymentMethod) Set(val *EcrPaymentMethod) {
	v.value = val
	v.isSet = true
}

func (v NullableEcrPaymentMethod) IsSet() bool {
	return v.isSet
}

func (v *NullableEcrPaymentMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEcrPaymentMethod(val *EcrPaymentMethod) *NullableEcrPaymentMethod {
	return &NullableEcrPaymentMethod{value: val, isSet: true}
}

func (v NullableEcrPaymentMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEcrPaymentMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
