/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the Paylink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Paylink{}

// Paylink struct for Paylink
type Paylink struct {
	Id                               *int32         `json:"id,omitempty"`
	Hash                             *string        `json:"hash,omitempty"`
	ReferenceId                      *string        `json:"referenceId,omitempty"`
	Link                             *string        `json:"link,omitempty"`
	Invoices                         []string       `json:"invoices,omitempty"`
	PreAuthorization                 *int32         `json:"preAuthorization,omitempty"`
	Reservation                      *int32         `json:"reservation,omitempty"`
	Name                             *string        `json:"name,omitempty"`
	Api                              *bool          `json:"api,omitempty"`
	Fields                           *PaylinkFields `json:"fields,omitempty"`
	Psp                              *int32         `json:"psp,omitempty"`
	Pm                               []string       `json:"pm,omitempty"`
	Purpose                          *string        `json:"purpose,omitempty"`
	Amount                           *int32         `json:"amount,omitempty"`
	VatRate                          *float32       `json:"vatRate,omitempty"`
	Currency                         *string        `json:"currency,omitempty"`
	Sku                              *string        `json:"sku,omitempty"`
	SubscriptionState                *bool          `json:"subscriptionState,omitempty"`
	SubscriptionInterval             *string        `json:"subscriptionInterval,omitempty"`
	SubscriptionPeriod               *string        `json:"subscriptionPeriod,omitempty"`
	SubscriptionPeriodMinAmount      *string        `json:"subscriptionPeriodMinAmount,omitempty"`
	SubscriptionCancellationInterval *string        `json:"subscriptionCancellationInterval,omitempty"`
	CreatedAt                        *int32         `json:"createdAt,omitempty"`
}

// NewPaylink instantiates a new Paylink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaylink() *Paylink {
	this := Paylink{}
	var id int32 = 0
	this.Id = &id
	var preAuthorization int32 = 0
	this.PreAuthorization = &preAuthorization
	var reservation int32 = 0
	this.Reservation = &reservation
	var api bool = true
	this.Api = &api
	var psp int32 = 0
	this.Psp = &psp
	var amount int32 = 0
	this.Amount = &amount
	var vatRate float32 = 0
	this.VatRate = &vatRate
	var subscriptionState bool = true
	this.SubscriptionState = &subscriptionState
	var createdAt int32 = 0
	this.CreatedAt = &createdAt
	return &this
}

// NewPaylinkWithDefaults instantiates a new Paylink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaylinkWithDefaults() *Paylink {
	this := Paylink{}
	var id int32 = 0
	this.Id = &id
	var preAuthorization int32 = 0
	this.PreAuthorization = &preAuthorization
	var reservation int32 = 0
	this.Reservation = &reservation
	var api bool = true
	this.Api = &api
	var psp int32 = 0
	this.Psp = &psp
	var amount int32 = 0
	this.Amount = &amount
	var vatRate float32 = 0
	this.VatRate = &vatRate
	var subscriptionState bool = true
	this.SubscriptionState = &subscriptionState
	var createdAt int32 = 0
	this.CreatedAt = &createdAt
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Paylink) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Paylink) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *Paylink) SetId(v int32) {
	o.Id = &v
}

// GetHash returns the Hash field value if set, zero value otherwise.
func (o *Paylink) GetHash() string {
	if o == nil || IsNil(o.Hash) {
		var ret string
		return ret
	}
	return *o.Hash
}

// GetHashOk returns a tuple with the Hash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetHashOk() (*string, bool) {
	if o == nil || IsNil(o.Hash) {
		return nil, false
	}
	return o.Hash, true
}

// HasHash returns a boolean if a field has been set.
func (o *Paylink) HasHash() bool {
	if o != nil && !IsNil(o.Hash) {
		return true
	}

	return false
}

// SetHash gets a reference to the given string and assigns it to the Hash field.
func (o *Paylink) SetHash(v string) {
	o.Hash = &v
}

// GetReferenceId returns the ReferenceId field value if set, zero value otherwise.
func (o *Paylink) GetReferenceId() string {
	if o == nil || IsNil(o.ReferenceId) {
		var ret string
		return ret
	}
	return *o.ReferenceId
}

// GetReferenceIdOk returns a tuple with the ReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetReferenceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ReferenceId) {
		return nil, false
	}
	return o.ReferenceId, true
}

// HasReferenceId returns a boolean if a field has been set.
func (o *Paylink) HasReferenceId() bool {
	if o != nil && !IsNil(o.ReferenceId) {
		return true
	}

	return false
}

// SetReferenceId gets a reference to the given string and assigns it to the ReferenceId field.
func (o *Paylink) SetReferenceId(v string) {
	o.ReferenceId = &v
}

// GetLink returns the Link field value if set, zero value otherwise.
func (o *Paylink) GetLink() string {
	if o == nil || IsNil(o.Link) {
		var ret string
		return ret
	}
	return *o.Link
}

// GetLinkOk returns a tuple with the Link field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetLinkOk() (*string, bool) {
	if o == nil || IsNil(o.Link) {
		return nil, false
	}
	return o.Link, true
}

// HasLink returns a boolean if a field has been set.
func (o *Paylink) HasLink() bool {
	if o != nil && !IsNil(o.Link) {
		return true
	}

	return false
}

// SetLink gets a reference to the given string and assigns it to the Link field.
func (o *Paylink) SetLink(v string) {
	o.Link = &v
}

// GetInvoices returns the Invoices field value if set, zero value otherwise.
func (o *Paylink) GetInvoices() []string {
	if o == nil || IsNil(o.Invoices) {
		var ret []string
		return ret
	}
	return o.Invoices
}

// GetInvoicesOk returns a tuple with the Invoices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetInvoicesOk() ([]string, bool) {
	if o == nil || IsNil(o.Invoices) {
		return nil, false
	}
	return o.Invoices, true
}

// HasInvoices returns a boolean if a field has been set.
func (o *Paylink) HasInvoices() bool {
	if o != nil && !IsNil(o.Invoices) {
		return true
	}

	return false
}

// SetInvoices gets a reference to the given []string and assigns it to the Invoices field.
func (o *Paylink) SetInvoices(v []string) {
	o.Invoices = v
}

// GetPreAuthorization returns the PreAuthorization field value if set, zero value otherwise.
func (o *Paylink) GetPreAuthorization() int32 {
	if o == nil || IsNil(o.PreAuthorization) {
		var ret int32
		return ret
	}
	return *o.PreAuthorization
}

// GetPreAuthorizationOk returns a tuple with the PreAuthorization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetPreAuthorizationOk() (*int32, bool) {
	if o == nil || IsNil(o.PreAuthorization) {
		return nil, false
	}
	return o.PreAuthorization, true
}

// HasPreAuthorization returns a boolean if a field has been set.
func (o *Paylink) HasPreAuthorization() bool {
	if o != nil && !IsNil(o.PreAuthorization) {
		return true
	}

	return false
}

// SetPreAuthorization gets a reference to the given int32 and assigns it to the PreAuthorization field.
func (o *Paylink) SetPreAuthorization(v int32) {
	o.PreAuthorization = &v
}

// GetReservation returns the Reservation field value if set, zero value otherwise.
func (o *Paylink) GetReservation() int32 {
	if o == nil || IsNil(o.Reservation) {
		var ret int32
		return ret
	}
	return *o.Reservation
}

// GetReservationOk returns a tuple with the Reservation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetReservationOk() (*int32, bool) {
	if o == nil || IsNil(o.Reservation) {
		return nil, false
	}
	return o.Reservation, true
}

// HasReservation returns a boolean if a field has been set.
func (o *Paylink) HasReservation() bool {
	if o != nil && !IsNil(o.Reservation) {
		return true
	}

	return false
}

// SetReservation gets a reference to the given int32 and assigns it to the Reservation field.
func (o *Paylink) SetReservation(v int32) {
	o.Reservation = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Paylink) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Paylink) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Paylink) SetName(v string) {
	o.Name = &v
}

// GetApi returns the Api field value if set, zero value otherwise.
func (o *Paylink) GetApi() bool {
	if o == nil || IsNil(o.Api) {
		var ret bool
		return ret
	}
	return *o.Api
}

// GetApiOk returns a tuple with the Api field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetApiOk() (*bool, bool) {
	if o == nil || IsNil(o.Api) {
		return nil, false
	}
	return o.Api, true
}

// HasApi returns a boolean if a field has been set.
func (o *Paylink) HasApi() bool {
	if o != nil && !IsNil(o.Api) {
		return true
	}

	return false
}

// SetApi gets a reference to the given bool and assigns it to the Api field.
func (o *Paylink) SetApi(v bool) {
	o.Api = &v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *Paylink) GetFields() PaylinkFields {
	if o == nil || IsNil(o.Fields) {
		var ret PaylinkFields
		return ret
	}
	return *o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetFieldsOk() (*PaylinkFields, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *Paylink) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given PaylinkFields and assigns it to the Fields field.
func (o *Paylink) SetFields(v PaylinkFields) {
	o.Fields = &v
}

// GetPsp returns the Psp field value if set, zero value otherwise.
func (o *Paylink) GetPsp() int32 {
	if o == nil || IsNil(o.Psp) {
		var ret int32
		return ret
	}
	return *o.Psp
}

// GetPspOk returns a tuple with the Psp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetPspOk() (*int32, bool) {
	if o == nil || IsNil(o.Psp) {
		return nil, false
	}
	return o.Psp, true
}

// HasPsp returns a boolean if a field has been set.
func (o *Paylink) HasPsp() bool {
	if o != nil && !IsNil(o.Psp) {
		return true
	}

	return false
}

// SetPsp gets a reference to the given int32 and assigns it to the Psp field.
func (o *Paylink) SetPsp(v int32) {
	o.Psp = &v
}

// GetPm returns the Pm field value if set, zero value otherwise.
func (o *Paylink) GetPm() []string {
	if o == nil || IsNil(o.Pm) {
		var ret []string
		return ret
	}
	return o.Pm
}

// GetPmOk returns a tuple with the Pm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetPmOk() ([]string, bool) {
	if o == nil || IsNil(o.Pm) {
		return nil, false
	}
	return o.Pm, true
}

// HasPm returns a boolean if a field has been set.
func (o *Paylink) HasPm() bool {
	if o != nil && !IsNil(o.Pm) {
		return true
	}

	return false
}

// SetPm gets a reference to the given []string and assigns it to the Pm field.
func (o *Paylink) SetPm(v []string) {
	o.Pm = v
}

// GetPurpose returns the Purpose field value if set, zero value otherwise.
func (o *Paylink) GetPurpose() string {
	if o == nil || IsNil(o.Purpose) {
		var ret string
		return ret
	}
	return *o.Purpose
}

// GetPurposeOk returns a tuple with the Purpose field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetPurposeOk() (*string, bool) {
	if o == nil || IsNil(o.Purpose) {
		return nil, false
	}
	return o.Purpose, true
}

// HasPurpose returns a boolean if a field has been set.
func (o *Paylink) HasPurpose() bool {
	if o != nil && !IsNil(o.Purpose) {
		return true
	}

	return false
}

// SetPurpose gets a reference to the given string and assigns it to the Purpose field.
func (o *Paylink) SetPurpose(v string) {
	o.Purpose = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *Paylink) GetAmount() int32 {
	if o == nil || IsNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *Paylink) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *Paylink) SetAmount(v int32) {
	o.Amount = &v
}

// GetVatRate returns the VatRate field value if set, zero value otherwise.
func (o *Paylink) GetVatRate() float32 {
	if o == nil || IsNil(o.VatRate) {
		var ret float32
		return ret
	}
	return *o.VatRate
}

// GetVatRateOk returns a tuple with the VatRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetVatRateOk() (*float32, bool) {
	if o == nil || IsNil(o.VatRate) {
		return nil, false
	}
	return o.VatRate, true
}

// HasVatRate returns a boolean if a field has been set.
func (o *Paylink) HasVatRate() bool {
	if o != nil && !IsNil(o.VatRate) {
		return true
	}

	return false
}

// SetVatRate gets a reference to the given float32 and assigns it to the VatRate field.
func (o *Paylink) SetVatRate(v float32) {
	o.VatRate = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *Paylink) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *Paylink) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *Paylink) SetCurrency(v string) {
	o.Currency = &v
}

// GetSku returns the Sku field value if set, zero value otherwise.
func (o *Paylink) GetSku() string {
	if o == nil || IsNil(o.Sku) {
		var ret string
		return ret
	}
	return *o.Sku
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetSkuOk() (*string, bool) {
	if o == nil || IsNil(o.Sku) {
		return nil, false
	}
	return o.Sku, true
}

// HasSku returns a boolean if a field has been set.
func (o *Paylink) HasSku() bool {
	if o != nil && !IsNil(o.Sku) {
		return true
	}

	return false
}

// SetSku gets a reference to the given string and assigns it to the Sku field.
func (o *Paylink) SetSku(v string) {
	o.Sku = &v
}

// GetSubscriptionState returns the SubscriptionState field value if set, zero value otherwise.
func (o *Paylink) GetSubscriptionState() bool {
	if o == nil || IsNil(o.SubscriptionState) {
		var ret bool
		return ret
	}
	return *o.SubscriptionState
}

// GetSubscriptionStateOk returns a tuple with the SubscriptionState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetSubscriptionStateOk() (*bool, bool) {
	if o == nil || IsNil(o.SubscriptionState) {
		return nil, false
	}
	return o.SubscriptionState, true
}

// HasSubscriptionState returns a boolean if a field has been set.
func (o *Paylink) HasSubscriptionState() bool {
	if o != nil && !IsNil(o.SubscriptionState) {
		return true
	}

	return false
}

// SetSubscriptionState gets a reference to the given bool and assigns it to the SubscriptionState field.
func (o *Paylink) SetSubscriptionState(v bool) {
	o.SubscriptionState = &v
}

// GetSubscriptionInterval returns the SubscriptionInterval field value if set, zero value otherwise.
func (o *Paylink) GetSubscriptionInterval() string {
	if o == nil || IsNil(o.SubscriptionInterval) {
		var ret string
		return ret
	}
	return *o.SubscriptionInterval
}

// GetSubscriptionIntervalOk returns a tuple with the SubscriptionInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetSubscriptionIntervalOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionInterval) {
		return nil, false
	}
	return o.SubscriptionInterval, true
}

// HasSubscriptionInterval returns a boolean if a field has been set.
func (o *Paylink) HasSubscriptionInterval() bool {
	if o != nil && !IsNil(o.SubscriptionInterval) {
		return true
	}

	return false
}

// SetSubscriptionInterval gets a reference to the given string and assigns it to the SubscriptionInterval field.
func (o *Paylink) SetSubscriptionInterval(v string) {
	o.SubscriptionInterval = &v
}

// GetSubscriptionPeriod returns the SubscriptionPeriod field value if set, zero value otherwise.
func (o *Paylink) GetSubscriptionPeriod() string {
	if o == nil || IsNil(o.SubscriptionPeriod) {
		var ret string
		return ret
	}
	return *o.SubscriptionPeriod
}

// GetSubscriptionPeriodOk returns a tuple with the SubscriptionPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetSubscriptionPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionPeriod) {
		return nil, false
	}
	return o.SubscriptionPeriod, true
}

// HasSubscriptionPeriod returns a boolean if a field has been set.
func (o *Paylink) HasSubscriptionPeriod() bool {
	if o != nil && !IsNil(o.SubscriptionPeriod) {
		return true
	}

	return false
}

// SetSubscriptionPeriod gets a reference to the given string and assigns it to the SubscriptionPeriod field.
func (o *Paylink) SetSubscriptionPeriod(v string) {
	o.SubscriptionPeriod = &v
}

// GetSubscriptionPeriodMinAmount returns the SubscriptionPeriodMinAmount field value if set, zero value otherwise.
func (o *Paylink) GetSubscriptionPeriodMinAmount() string {
	if o == nil || IsNil(o.SubscriptionPeriodMinAmount) {
		var ret string
		return ret
	}
	return *o.SubscriptionPeriodMinAmount
}

// GetSubscriptionPeriodMinAmountOk returns a tuple with the SubscriptionPeriodMinAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetSubscriptionPeriodMinAmountOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionPeriodMinAmount) {
		return nil, false
	}
	return o.SubscriptionPeriodMinAmount, true
}

// HasSubscriptionPeriodMinAmount returns a boolean if a field has been set.
func (o *Paylink) HasSubscriptionPeriodMinAmount() bool {
	if o != nil && !IsNil(o.SubscriptionPeriodMinAmount) {
		return true
	}

	return false
}

// SetSubscriptionPeriodMinAmount gets a reference to the given string and assigns it to the SubscriptionPeriodMinAmount field.
func (o *Paylink) SetSubscriptionPeriodMinAmount(v string) {
	o.SubscriptionPeriodMinAmount = &v
}

// GetSubscriptionCancellationInterval returns the SubscriptionCancellationInterval field value if set, zero value otherwise.
func (o *Paylink) GetSubscriptionCancellationInterval() string {
	if o == nil || IsNil(o.SubscriptionCancellationInterval) {
		var ret string
		return ret
	}
	return *o.SubscriptionCancellationInterval
}

// GetSubscriptionCancellationIntervalOk returns a tuple with the SubscriptionCancellationInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetSubscriptionCancellationIntervalOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionCancellationInterval) {
		return nil, false
	}
	return o.SubscriptionCancellationInterval, true
}

// HasSubscriptionCancellationInterval returns a boolean if a field has been set.
func (o *Paylink) HasSubscriptionCancellationInterval() bool {
	if o != nil && !IsNil(o.SubscriptionCancellationInterval) {
		return true
	}

	return false
}

// SetSubscriptionCancellationInterval gets a reference to the given string and assigns it to the SubscriptionCancellationInterval field.
func (o *Paylink) SetSubscriptionCancellationInterval(v string) {
	o.SubscriptionCancellationInterval = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Paylink) GetCreatedAt() int32 {
	if o == nil || IsNil(o.CreatedAt) {
		var ret int32
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Paylink) GetCreatedAtOk() (*int32, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Paylink) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int32 and assigns it to the CreatedAt field.
func (o *Paylink) SetCreatedAt(v int32) {
	o.CreatedAt = &v
}

func (o Paylink) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Paylink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Hash) {
		toSerialize["hash"] = o.Hash
	}
	if !IsNil(o.ReferenceId) {
		toSerialize["referenceId"] = o.ReferenceId
	}
	if !IsNil(o.Link) {
		toSerialize["link"] = o.Link
	}
	if !IsNil(o.Invoices) {
		toSerialize["invoices"] = o.Invoices
	}
	if !IsNil(o.PreAuthorization) {
		toSerialize["preAuthorization"] = o.PreAuthorization
	}
	if !IsNil(o.Reservation) {
		toSerialize["reservation"] = o.Reservation
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Api) {
		toSerialize["api"] = o.Api
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	if !IsNil(o.Psp) {
		toSerialize["psp"] = o.Psp
	}
	if !IsNil(o.Pm) {
		toSerialize["pm"] = o.Pm
	}
	if !IsNil(o.Purpose) {
		toSerialize["purpose"] = o.Purpose
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.VatRate) {
		toSerialize["vatRate"] = o.VatRate
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Sku) {
		toSerialize["sku"] = o.Sku
	}
	if !IsNil(o.SubscriptionState) {
		toSerialize["subscriptionState"] = o.SubscriptionState
	}
	if !IsNil(o.SubscriptionInterval) {
		toSerialize["subscriptionInterval"] = o.SubscriptionInterval
	}
	if !IsNil(o.SubscriptionPeriod) {
		toSerialize["subscriptionPeriod"] = o.SubscriptionPeriod
	}
	if !IsNil(o.SubscriptionPeriodMinAmount) {
		toSerialize["subscriptionPeriodMinAmount"] = o.SubscriptionPeriodMinAmount
	}
	if !IsNil(o.SubscriptionCancellationInterval) {
		toSerialize["subscriptionCancellationInterval"] = o.SubscriptionCancellationInterval
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullablePaylink struct {
	value *Paylink
	isSet bool
}

func (v NullablePaylink) Get() *Paylink {
	return v.value
}

func (v *NullablePaylink) Set(val *Paylink) {
	v.value = val
	v.isSet = true
}

func (v NullablePaylink) IsSet() bool {
	return v.isSet
}

func (v *NullablePaylink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaylink(val *Paylink) *NullablePaylink {
	return &NullablePaylink{value: val, isSet: true}
}

func (v NullablePaylink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaylink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
