/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BillCreateRequestBankInformation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillCreateRequestBankInformation{}

// BillCreateRequestBankInformation struct for BillCreateRequestBankInformation
type BillCreateRequestBankInformation struct {
	Iban    string `json:"iban"`
	Name    string `json:"name"`
	Address string `json:"address"`
}

type _BillCreateRequestBankInformation BillCreateRequestBankInformation

// NewBillCreateRequestBankInformation instantiates a new BillCreateRequestBankInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillCreateRequestBankInformation(iban string, name string, address string) *BillCreateRequestBankInformation {
	this := BillCreateRequestBankInformation{}
	this.Iban = iban
	this.Name = name
	this.Address = address
	return &this
}

// NewBillCreateRequestBankInformationWithDefaults instantiates a new BillCreateRequestBankInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillCreateRequestBankInformationWithDefaults() *BillCreateRequestBankInformation {
	this := BillCreateRequestBankInformation{}
	return &this
}

// GetIban returns the Iban field value
func (o *BillCreateRequestBankInformation) GetIban() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Iban
}

// GetIbanOk returns a tuple with the Iban field value
// and a boolean to check if the value has been set.
func (o *BillCreateRequestBankInformation) GetIbanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Iban, true
}

// SetIban sets field value
func (o *BillCreateRequestBankInformation) SetIban(v string) {
	o.Iban = v
}

// GetName returns the Name field value
func (o *BillCreateRequestBankInformation) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BillCreateRequestBankInformation) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BillCreateRequestBankInformation) SetName(v string) {
	o.Name = v
}

// GetAddress returns the Address field value
func (o *BillCreateRequestBankInformation) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *BillCreateRequestBankInformation) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *BillCreateRequestBankInformation) SetAddress(v string) {
	o.Address = v
}

func (o BillCreateRequestBankInformation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillCreateRequestBankInformation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["iban"] = o.Iban
	toSerialize["name"] = o.Name
	toSerialize["address"] = o.Address
	return toSerialize, nil
}

func (o *BillCreateRequestBankInformation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"iban",
		"name",
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillCreateRequestBankInformation := _BillCreateRequestBankInformation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillCreateRequestBankInformation)

	if err != nil {
		return err
	}

	*o = BillCreateRequestBankInformation(varBillCreateRequestBankInformation)

	return err
}

type NullableBillCreateRequestBankInformation struct {
	value *BillCreateRequestBankInformation
	isSet bool
}

func (v NullableBillCreateRequestBankInformation) Get() *BillCreateRequestBankInformation {
	return v.value
}

func (v *NullableBillCreateRequestBankInformation) Set(val *BillCreateRequestBankInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableBillCreateRequestBankInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableBillCreateRequestBankInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillCreateRequestBankInformation(val *BillCreateRequestBankInformation) *NullableBillCreateRequestBankInformation {
	return &NullableBillCreateRequestBankInformation{value: val, isSet: true}
}

func (v NullableBillCreateRequestBankInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillCreateRequestBankInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
