/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the PayoutDestination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PayoutDestination{}

// PayoutDestination struct for PayoutDestination
type PayoutDestination struct {
	Type          *string `json:"type,omitempty"`
	Iban          *string `json:"iban,omitempty"`
	AccountHolder *string `json:"account_holder,omitempty"`
}

// NewPayoutDestination instantiates a new PayoutDestination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPayoutDestination() *PayoutDestination {
	this := PayoutDestination{}
	return &this
}

// NewPayoutDestinationWithDefaults instantiates a new PayoutDestination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPayoutDestinationWithDefaults() *PayoutDestination {
	this := PayoutDestination{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *PayoutDestination) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayoutDestination) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *PayoutDestination) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *PayoutDestination) SetType(v string) {
	o.Type = &v
}

// GetIban returns the Iban field value if set, zero value otherwise.
func (o *PayoutDestination) GetIban() string {
	if o == nil || IsNil(o.Iban) {
		var ret string
		return ret
	}
	return *o.Iban
}

// GetIbanOk returns a tuple with the Iban field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayoutDestination) GetIbanOk() (*string, bool) {
	if o == nil || IsNil(o.Iban) {
		return nil, false
	}
	return o.Iban, true
}

// HasIban returns a boolean if a field has been set.
func (o *PayoutDestination) HasIban() bool {
	if o != nil && !IsNil(o.Iban) {
		return true
	}

	return false
}

// SetIban gets a reference to the given string and assigns it to the Iban field.
func (o *PayoutDestination) SetIban(v string) {
	o.Iban = &v
}

// GetAccountHolder returns the AccountHolder field value if set, zero value otherwise.
func (o *PayoutDestination) GetAccountHolder() string {
	if o == nil || IsNil(o.AccountHolder) {
		var ret string
		return ret
	}
	return *o.AccountHolder
}

// GetAccountHolderOk returns a tuple with the AccountHolder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayoutDestination) GetAccountHolderOk() (*string, bool) {
	if o == nil || IsNil(o.AccountHolder) {
		return nil, false
	}
	return o.AccountHolder, true
}

// HasAccountHolder returns a boolean if a field has been set.
func (o *PayoutDestination) HasAccountHolder() bool {
	if o != nil && !IsNil(o.AccountHolder) {
		return true
	}

	return false
}

// SetAccountHolder gets a reference to the given string and assigns it to the AccountHolder field.
func (o *PayoutDestination) SetAccountHolder(v string) {
	o.AccountHolder = &v
}

func (o PayoutDestination) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PayoutDestination) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Iban) {
		toSerialize["iban"] = o.Iban
	}
	if !IsNil(o.AccountHolder) {
		toSerialize["account_holder"] = o.AccountHolder
	}
	return toSerialize, nil
}

type NullablePayoutDestination struct {
	value *PayoutDestination
	isSet bool
}

func (v NullablePayoutDestination) Get() *PayoutDestination {
	return v.value
}

func (v *NullablePayoutDestination) Set(val *PayoutDestination) {
	v.value = val
	v.isSet = true
}

func (v NullablePayoutDestination) IsSet() bool {
	return v.isSet
}

func (v *NullablePayoutDestination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayoutDestination(val *PayoutDestination) *NullablePayoutDestination {
	return &NullablePayoutDestination{value: val, isSet: true}
}

func (v NullablePayoutDestination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayoutDestination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
