/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GatewayCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayCreateRequest{}

// GatewayCreateRequest struct for GatewayCreateRequest
type GatewayCreateRequest struct {
	// Amount of payment in cents.
	Amount int32 `json:"amount"`
	// VAT Rate Percentage
	VatRate *float32 `json:"vatRate,omitempty"`
	// Currency of payment (ISO code).
	Currency string `json:"currency"`
	// Product stock keeping unit
	Sku *string `json:"sku,omitempty"`
	// The purpose of the payment.
	Purpose *string `json:"purpose,omitempty"`
	// URL to redirect to after successful payment.
	SuccessRedirectUrl *string `json:"successRedirectUrl,omitempty"`
	// URL to redirect to after failed payment.
	FailedRedirectUrl *string `json:"failedRedirectUrl,omitempty"`
	// URL to redirect to after manual cancellation by shopper.
	CancelRedirectUrl *string `json:"cancelRedirectUrl,omitempty"`
	// List of all products (incl. shipping costs). The sum of all product amounts must match the amount parameter above. Basket products contains name, description, quantity, amount (in cents) and vatRate (in Percent).
	Basket []GatewayCreateRequestBasketInner `json:"basket,omitempty"`
	// List of PSPs to provide for payment. If empty all available PSPs are provied.
	Psp []int32 `json:"psp,omitempty"`
	// List of payment mean names to display
	Pm []string `json:"pm,omitempty"`
	// Whether charge payment manually at a later date (type authorization)
	PreAuthorization *bool `json:"preAuthorization,omitempty"`
	// Whether charge payment manually at a later date (type reservation)
	Reservation *bool `json:"reservation,omitempty"`
	// An internal reference id used by your system.
	ReferenceId *string                     `json:"referenceId,omitempty"`
	Fields      *GatewayCreateRequestFields `json:"fields,omitempty"`
	// The language ISO code by ISO 639-1.
	Language *string `json:"language,omitempty"`
	// Only available for Concardis PSP and if the custom ORDERID option is activated in PSP settings in Payrexx administration. This ORDERID will be transferred to the Payengine.
	ConcardisOrderId *string `json:"concardisOrderId,omitempty"`
	// Skip result page and directly redirect to success or failed URL
	SkipResultPage *bool `json:"skipResultPage,omitempty"`
	// preAuthorization needs to be \"true\". This will charge the authorization during the first payment.
	ChargeOnAuthorization *bool `json:"chargeOnAuthorization,omitempty"`
	// Gateway validity in minutes.
	Validity *int32 `json:"validity,omitempty"`
	// Defines whether the payment should be handled as subscription.
	SubscriptionState *bool `json:"subscriptionState,omitempty"`
	// Payment interval
	SubscriptionInterval *string `json:"subscriptionInterval,omitempty"`
	// Duration of the subscription
	SubscriptionPeriod *string `json:"subscriptionPeriod,omitempty"`
	// Defines the period, in which a subscription can be canceled.
	SubscriptionCancellationInterval *string `json:"subscriptionCancellationInterval,omitempty"`
	// Change the default button Text \"Pay\" to a custom String
	ButtonText []string `json:"buttonText,omitempty"`
	// UUID of the look and feel profile to use.
	LookAndFeelProfile *string `json:"lookAndFeelProfile,omitempty"`
	// Custom success message on result page.
	SuccessMessage *string `json:"successMessage,omitempty"`
	// Holds the session ID of a scanned QR code. Only available and needed for Static QR Code with Twint.
	QrCodeSessionId *string `json:"qrCodeSessionId,omitempty"`
	// Amount in the smallest unit of the currency.
	ApplicationFee *int32 `json:"applicationFee,omitempty"`
	// preAuthorization needs to be \"true\". This will create a reservation based on an authorization during the first payment.
	ReserveOnAuthorization *bool `json:"reserveOnAuthorization,omitempty"`
	// if set to  true the vat will be added on top of amount
	IsPriceExclusiveVat *bool `json:"isPriceExclusiveVat,omitempty"`
}

type _GatewayCreateRequest GatewayCreateRequest

// NewGatewayCreateRequest instantiates a new GatewayCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayCreateRequest(amount int32, currency string) *GatewayCreateRequest {
	this := GatewayCreateRequest{}
	this.Amount = amount
	this.Currency = currency
	var preAuthorization bool = false
	this.PreAuthorization = &preAuthorization
	var reservation bool = false
	this.Reservation = &reservation
	var skipResultPage bool = false
	this.SkipResultPage = &skipResultPage
	var chargeOnAuthorization bool = false
	this.ChargeOnAuthorization = &chargeOnAuthorization
	var subscriptionState bool = false
	this.SubscriptionState = &subscriptionState
	return &this
}

// NewGatewayCreateRequestWithDefaults instantiates a new GatewayCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayCreateRequestWithDefaults() *GatewayCreateRequest {
	this := GatewayCreateRequest{}
	var preAuthorization bool = false
	this.PreAuthorization = &preAuthorization
	var reservation bool = false
	this.Reservation = &reservation
	var skipResultPage bool = false
	this.SkipResultPage = &skipResultPage
	var chargeOnAuthorization bool = false
	this.ChargeOnAuthorization = &chargeOnAuthorization
	var subscriptionState bool = false
	this.SubscriptionState = &subscriptionState
	return &this
}

// GetAmount returns the Amount field value
func (o *GatewayCreateRequest) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *GatewayCreateRequest) SetAmount(v int32) {
	o.Amount = v
}

// GetVatRate returns the VatRate field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetVatRate() float32 {
	if o == nil || IsNil(o.VatRate) {
		var ret float32
		return ret
	}
	return *o.VatRate
}

// GetVatRateOk returns a tuple with the VatRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetVatRateOk() (*float32, bool) {
	if o == nil || IsNil(o.VatRate) {
		return nil, false
	}
	return o.VatRate, true
}

// HasVatRate returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasVatRate() bool {
	if o != nil && !IsNil(o.VatRate) {
		return true
	}

	return false
}

// SetVatRate gets a reference to the given float32 and assigns it to the VatRate field.
func (o *GatewayCreateRequest) SetVatRate(v float32) {
	o.VatRate = &v
}

// GetCurrency returns the Currency field value
func (o *GatewayCreateRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *GatewayCreateRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetSku returns the Sku field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetSku() string {
	if o == nil || IsNil(o.Sku) {
		var ret string
		return ret
	}
	return *o.Sku
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetSkuOk() (*string, bool) {
	if o == nil || IsNil(o.Sku) {
		return nil, false
	}
	return o.Sku, true
}

// HasSku returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasSku() bool {
	if o != nil && !IsNil(o.Sku) {
		return true
	}

	return false
}

// SetSku gets a reference to the given string and assigns it to the Sku field.
func (o *GatewayCreateRequest) SetSku(v string) {
	o.Sku = &v
}

// GetPurpose returns the Purpose field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetPurpose() string {
	if o == nil || IsNil(o.Purpose) {
		var ret string
		return ret
	}
	return *o.Purpose
}

// GetPurposeOk returns a tuple with the Purpose field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetPurposeOk() (*string, bool) {
	if o == nil || IsNil(o.Purpose) {
		return nil, false
	}
	return o.Purpose, true
}

// HasPurpose returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasPurpose() bool {
	if o != nil && !IsNil(o.Purpose) {
		return true
	}

	return false
}

// SetPurpose gets a reference to the given string and assigns it to the Purpose field.
func (o *GatewayCreateRequest) SetPurpose(v string) {
	o.Purpose = &v
}

// GetSuccessRedirectUrl returns the SuccessRedirectUrl field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetSuccessRedirectUrl() string {
	if o == nil || IsNil(o.SuccessRedirectUrl) {
		var ret string
		return ret
	}
	return *o.SuccessRedirectUrl
}

// GetSuccessRedirectUrlOk returns a tuple with the SuccessRedirectUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetSuccessRedirectUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SuccessRedirectUrl) {
		return nil, false
	}
	return o.SuccessRedirectUrl, true
}

// HasSuccessRedirectUrl returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasSuccessRedirectUrl() bool {
	if o != nil && !IsNil(o.SuccessRedirectUrl) {
		return true
	}

	return false
}

// SetSuccessRedirectUrl gets a reference to the given string and assigns it to the SuccessRedirectUrl field.
func (o *GatewayCreateRequest) SetSuccessRedirectUrl(v string) {
	o.SuccessRedirectUrl = &v
}

// GetFailedRedirectUrl returns the FailedRedirectUrl field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetFailedRedirectUrl() string {
	if o == nil || IsNil(o.FailedRedirectUrl) {
		var ret string
		return ret
	}
	return *o.FailedRedirectUrl
}

// GetFailedRedirectUrlOk returns a tuple with the FailedRedirectUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetFailedRedirectUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FailedRedirectUrl) {
		return nil, false
	}
	return o.FailedRedirectUrl, true
}

// HasFailedRedirectUrl returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasFailedRedirectUrl() bool {
	if o != nil && !IsNil(o.FailedRedirectUrl) {
		return true
	}

	return false
}

// SetFailedRedirectUrl gets a reference to the given string and assigns it to the FailedRedirectUrl field.
func (o *GatewayCreateRequest) SetFailedRedirectUrl(v string) {
	o.FailedRedirectUrl = &v
}

// GetCancelRedirectUrl returns the CancelRedirectUrl field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetCancelRedirectUrl() string {
	if o == nil || IsNil(o.CancelRedirectUrl) {
		var ret string
		return ret
	}
	return *o.CancelRedirectUrl
}

// GetCancelRedirectUrlOk returns a tuple with the CancelRedirectUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetCancelRedirectUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CancelRedirectUrl) {
		return nil, false
	}
	return o.CancelRedirectUrl, true
}

// HasCancelRedirectUrl returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasCancelRedirectUrl() bool {
	if o != nil && !IsNil(o.CancelRedirectUrl) {
		return true
	}

	return false
}

// SetCancelRedirectUrl gets a reference to the given string and assigns it to the CancelRedirectUrl field.
func (o *GatewayCreateRequest) SetCancelRedirectUrl(v string) {
	o.CancelRedirectUrl = &v
}

// GetBasket returns the Basket field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetBasket() []GatewayCreateRequestBasketInner {
	if o == nil || IsNil(o.Basket) {
		var ret []GatewayCreateRequestBasketInner
		return ret
	}
	return o.Basket
}

// GetBasketOk returns a tuple with the Basket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetBasketOk() ([]GatewayCreateRequestBasketInner, bool) {
	if o == nil || IsNil(o.Basket) {
		return nil, false
	}
	return o.Basket, true
}

// HasBasket returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasBasket() bool {
	if o != nil && !IsNil(o.Basket) {
		return true
	}

	return false
}

// SetBasket gets a reference to the given []GatewayCreateRequestBasketInner and assigns it to the Basket field.
func (o *GatewayCreateRequest) SetBasket(v []GatewayCreateRequestBasketInner) {
	o.Basket = v
}

// GetPsp returns the Psp field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetPsp() []int32 {
	if o == nil || IsNil(o.Psp) {
		var ret []int32
		return ret
	}
	return o.Psp
}

// GetPspOk returns a tuple with the Psp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetPspOk() ([]int32, bool) {
	if o == nil || IsNil(o.Psp) {
		return nil, false
	}
	return o.Psp, true
}

// HasPsp returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasPsp() bool {
	if o != nil && !IsNil(o.Psp) {
		return true
	}

	return false
}

// SetPsp gets a reference to the given []int32 and assigns it to the Psp field.
func (o *GatewayCreateRequest) SetPsp(v []int32) {
	o.Psp = v
}

// GetPm returns the Pm field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetPm() []string {
	if o == nil || IsNil(o.Pm) {
		var ret []string
		return ret
	}
	return o.Pm
}

// GetPmOk returns a tuple with the Pm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetPmOk() ([]string, bool) {
	if o == nil || IsNil(o.Pm) {
		return nil, false
	}
	return o.Pm, true
}

// HasPm returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasPm() bool {
	if o != nil && !IsNil(o.Pm) {
		return true
	}

	return false
}

// SetPm gets a reference to the given []string and assigns it to the Pm field.
func (o *GatewayCreateRequest) SetPm(v []string) {
	o.Pm = v
}

// GetPreAuthorization returns the PreAuthorization field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetPreAuthorization() bool {
	if o == nil || IsNil(o.PreAuthorization) {
		var ret bool
		return ret
	}
	return *o.PreAuthorization
}

// GetPreAuthorizationOk returns a tuple with the PreAuthorization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetPreAuthorizationOk() (*bool, bool) {
	if o == nil || IsNil(o.PreAuthorization) {
		return nil, false
	}
	return o.PreAuthorization, true
}

// HasPreAuthorization returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasPreAuthorization() bool {
	if o != nil && !IsNil(o.PreAuthorization) {
		return true
	}

	return false
}

// SetPreAuthorization gets a reference to the given bool and assigns it to the PreAuthorization field.
func (o *GatewayCreateRequest) SetPreAuthorization(v bool) {
	o.PreAuthorization = &v
}

// GetReservation returns the Reservation field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetReservation() bool {
	if o == nil || IsNil(o.Reservation) {
		var ret bool
		return ret
	}
	return *o.Reservation
}

// GetReservationOk returns a tuple with the Reservation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetReservationOk() (*bool, bool) {
	if o == nil || IsNil(o.Reservation) {
		return nil, false
	}
	return o.Reservation, true
}

// HasReservation returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasReservation() bool {
	if o != nil && !IsNil(o.Reservation) {
		return true
	}

	return false
}

// SetReservation gets a reference to the given bool and assigns it to the Reservation field.
func (o *GatewayCreateRequest) SetReservation(v bool) {
	o.Reservation = &v
}

// GetReferenceId returns the ReferenceId field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetReferenceId() string {
	if o == nil || IsNil(o.ReferenceId) {
		var ret string
		return ret
	}
	return *o.ReferenceId
}

// GetReferenceIdOk returns a tuple with the ReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetReferenceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ReferenceId) {
		return nil, false
	}
	return o.ReferenceId, true
}

// HasReferenceId returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasReferenceId() bool {
	if o != nil && !IsNil(o.ReferenceId) {
		return true
	}

	return false
}

// SetReferenceId gets a reference to the given string and assigns it to the ReferenceId field.
func (o *GatewayCreateRequest) SetReferenceId(v string) {
	o.ReferenceId = &v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetFields() GatewayCreateRequestFields {
	if o == nil || IsNil(o.Fields) {
		var ret GatewayCreateRequestFields
		return ret
	}
	return *o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetFieldsOk() (*GatewayCreateRequestFields, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given GatewayCreateRequestFields and assigns it to the Fields field.
func (o *GatewayCreateRequest) SetFields(v GatewayCreateRequestFields) {
	o.Fields = &v
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetLanguage() string {
	if o == nil || IsNil(o.Language) {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.Language) {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasLanguage() bool {
	if o != nil && !IsNil(o.Language) {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *GatewayCreateRequest) SetLanguage(v string) {
	o.Language = &v
}

// GetConcardisOrderId returns the ConcardisOrderId field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetConcardisOrderId() string {
	if o == nil || IsNil(o.ConcardisOrderId) {
		var ret string
		return ret
	}
	return *o.ConcardisOrderId
}

// GetConcardisOrderIdOk returns a tuple with the ConcardisOrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetConcardisOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConcardisOrderId) {
		return nil, false
	}
	return o.ConcardisOrderId, true
}

// HasConcardisOrderId returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasConcardisOrderId() bool {
	if o != nil && !IsNil(o.ConcardisOrderId) {
		return true
	}

	return false
}

// SetConcardisOrderId gets a reference to the given string and assigns it to the ConcardisOrderId field.
func (o *GatewayCreateRequest) SetConcardisOrderId(v string) {
	o.ConcardisOrderId = &v
}

// GetSkipResultPage returns the SkipResultPage field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetSkipResultPage() bool {
	if o == nil || IsNil(o.SkipResultPage) {
		var ret bool
		return ret
	}
	return *o.SkipResultPage
}

// GetSkipResultPageOk returns a tuple with the SkipResultPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetSkipResultPageOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipResultPage) {
		return nil, false
	}
	return o.SkipResultPage, true
}

// HasSkipResultPage returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasSkipResultPage() bool {
	if o != nil && !IsNil(o.SkipResultPage) {
		return true
	}

	return false
}

// SetSkipResultPage gets a reference to the given bool and assigns it to the SkipResultPage field.
func (o *GatewayCreateRequest) SetSkipResultPage(v bool) {
	o.SkipResultPage = &v
}

// GetChargeOnAuthorization returns the ChargeOnAuthorization field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetChargeOnAuthorization() bool {
	if o == nil || IsNil(o.ChargeOnAuthorization) {
		var ret bool
		return ret
	}
	return *o.ChargeOnAuthorization
}

// GetChargeOnAuthorizationOk returns a tuple with the ChargeOnAuthorization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetChargeOnAuthorizationOk() (*bool, bool) {
	if o == nil || IsNil(o.ChargeOnAuthorization) {
		return nil, false
	}
	return o.ChargeOnAuthorization, true
}

// HasChargeOnAuthorization returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasChargeOnAuthorization() bool {
	if o != nil && !IsNil(o.ChargeOnAuthorization) {
		return true
	}

	return false
}

// SetChargeOnAuthorization gets a reference to the given bool and assigns it to the ChargeOnAuthorization field.
func (o *GatewayCreateRequest) SetChargeOnAuthorization(v bool) {
	o.ChargeOnAuthorization = &v
}

// GetValidity returns the Validity field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetValidity() int32 {
	if o == nil || IsNil(o.Validity) {
		var ret int32
		return ret
	}
	return *o.Validity
}

// GetValidityOk returns a tuple with the Validity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetValidityOk() (*int32, bool) {
	if o == nil || IsNil(o.Validity) {
		return nil, false
	}
	return o.Validity, true
}

// HasValidity returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasValidity() bool {
	if o != nil && !IsNil(o.Validity) {
		return true
	}

	return false
}

// SetValidity gets a reference to the given int32 and assigns it to the Validity field.
func (o *GatewayCreateRequest) SetValidity(v int32) {
	o.Validity = &v
}

// GetSubscriptionState returns the SubscriptionState field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetSubscriptionState() bool {
	if o == nil || IsNil(o.SubscriptionState) {
		var ret bool
		return ret
	}
	return *o.SubscriptionState
}

// GetSubscriptionStateOk returns a tuple with the SubscriptionState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetSubscriptionStateOk() (*bool, bool) {
	if o == nil || IsNil(o.SubscriptionState) {
		return nil, false
	}
	return o.SubscriptionState, true
}

// HasSubscriptionState returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasSubscriptionState() bool {
	if o != nil && !IsNil(o.SubscriptionState) {
		return true
	}

	return false
}

// SetSubscriptionState gets a reference to the given bool and assigns it to the SubscriptionState field.
func (o *GatewayCreateRequest) SetSubscriptionState(v bool) {
	o.SubscriptionState = &v
}

// GetSubscriptionInterval returns the SubscriptionInterval field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetSubscriptionInterval() string {
	if o == nil || IsNil(o.SubscriptionInterval) {
		var ret string
		return ret
	}
	return *o.SubscriptionInterval
}

// GetSubscriptionIntervalOk returns a tuple with the SubscriptionInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetSubscriptionIntervalOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionInterval) {
		return nil, false
	}
	return o.SubscriptionInterval, true
}

// HasSubscriptionInterval returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasSubscriptionInterval() bool {
	if o != nil && !IsNil(o.SubscriptionInterval) {
		return true
	}

	return false
}

// SetSubscriptionInterval gets a reference to the given string and assigns it to the SubscriptionInterval field.
func (o *GatewayCreateRequest) SetSubscriptionInterval(v string) {
	o.SubscriptionInterval = &v
}

// GetSubscriptionPeriod returns the SubscriptionPeriod field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetSubscriptionPeriod() string {
	if o == nil || IsNil(o.SubscriptionPeriod) {
		var ret string
		return ret
	}
	return *o.SubscriptionPeriod
}

// GetSubscriptionPeriodOk returns a tuple with the SubscriptionPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetSubscriptionPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionPeriod) {
		return nil, false
	}
	return o.SubscriptionPeriod, true
}

// HasSubscriptionPeriod returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasSubscriptionPeriod() bool {
	if o != nil && !IsNil(o.SubscriptionPeriod) {
		return true
	}

	return false
}

// SetSubscriptionPeriod gets a reference to the given string and assigns it to the SubscriptionPeriod field.
func (o *GatewayCreateRequest) SetSubscriptionPeriod(v string) {
	o.SubscriptionPeriod = &v
}

// GetSubscriptionCancellationInterval returns the SubscriptionCancellationInterval field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetSubscriptionCancellationInterval() string {
	if o == nil || IsNil(o.SubscriptionCancellationInterval) {
		var ret string
		return ret
	}
	return *o.SubscriptionCancellationInterval
}

// GetSubscriptionCancellationIntervalOk returns a tuple with the SubscriptionCancellationInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetSubscriptionCancellationIntervalOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionCancellationInterval) {
		return nil, false
	}
	return o.SubscriptionCancellationInterval, true
}

// HasSubscriptionCancellationInterval returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasSubscriptionCancellationInterval() bool {
	if o != nil && !IsNil(o.SubscriptionCancellationInterval) {
		return true
	}

	return false
}

// SetSubscriptionCancellationInterval gets a reference to the given string and assigns it to the SubscriptionCancellationInterval field.
func (o *GatewayCreateRequest) SetSubscriptionCancellationInterval(v string) {
	o.SubscriptionCancellationInterval = &v
}

// GetButtonText returns the ButtonText field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetButtonText() []string {
	if o == nil || IsNil(o.ButtonText) {
		var ret []string
		return ret
	}
	return o.ButtonText
}

// GetButtonTextOk returns a tuple with the ButtonText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetButtonTextOk() ([]string, bool) {
	if o == nil || IsNil(o.ButtonText) {
		return nil, false
	}
	return o.ButtonText, true
}

// HasButtonText returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasButtonText() bool {
	if o != nil && !IsNil(o.ButtonText) {
		return true
	}

	return false
}

// SetButtonText gets a reference to the given []string and assigns it to the ButtonText field.
func (o *GatewayCreateRequest) SetButtonText(v []string) {
	o.ButtonText = v
}

// GetLookAndFeelProfile returns the LookAndFeelProfile field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetLookAndFeelProfile() string {
	if o == nil || IsNil(o.LookAndFeelProfile) {
		var ret string
		return ret
	}
	return *o.LookAndFeelProfile
}

// GetLookAndFeelProfileOk returns a tuple with the LookAndFeelProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetLookAndFeelProfileOk() (*string, bool) {
	if o == nil || IsNil(o.LookAndFeelProfile) {
		return nil, false
	}
	return o.LookAndFeelProfile, true
}

// HasLookAndFeelProfile returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasLookAndFeelProfile() bool {
	if o != nil && !IsNil(o.LookAndFeelProfile) {
		return true
	}

	return false
}

// SetLookAndFeelProfile gets a reference to the given string and assigns it to the LookAndFeelProfile field.
func (o *GatewayCreateRequest) SetLookAndFeelProfile(v string) {
	o.LookAndFeelProfile = &v
}

// GetSuccessMessage returns the SuccessMessage field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetSuccessMessage() string {
	if o == nil || IsNil(o.SuccessMessage) {
		var ret string
		return ret
	}
	return *o.SuccessMessage
}

// GetSuccessMessageOk returns a tuple with the SuccessMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetSuccessMessageOk() (*string, bool) {
	if o == nil || IsNil(o.SuccessMessage) {
		return nil, false
	}
	return o.SuccessMessage, true
}

// HasSuccessMessage returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasSuccessMessage() bool {
	if o != nil && !IsNil(o.SuccessMessage) {
		return true
	}

	return false
}

// SetSuccessMessage gets a reference to the given string and assigns it to the SuccessMessage field.
func (o *GatewayCreateRequest) SetSuccessMessage(v string) {
	o.SuccessMessage = &v
}

// GetQrCodeSessionId returns the QrCodeSessionId field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetQrCodeSessionId() string {
	if o == nil || IsNil(o.QrCodeSessionId) {
		var ret string
		return ret
	}
	return *o.QrCodeSessionId
}

// GetQrCodeSessionIdOk returns a tuple with the QrCodeSessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetQrCodeSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.QrCodeSessionId) {
		return nil, false
	}
	return o.QrCodeSessionId, true
}

// HasQrCodeSessionId returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasQrCodeSessionId() bool {
	if o != nil && !IsNil(o.QrCodeSessionId) {
		return true
	}

	return false
}

// SetQrCodeSessionId gets a reference to the given string and assigns it to the QrCodeSessionId field.
func (o *GatewayCreateRequest) SetQrCodeSessionId(v string) {
	o.QrCodeSessionId = &v
}

// GetApplicationFee returns the ApplicationFee field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetApplicationFee() int32 {
	if o == nil || IsNil(o.ApplicationFee) {
		var ret int32
		return ret
	}
	return *o.ApplicationFee
}

// GetApplicationFeeOk returns a tuple with the ApplicationFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetApplicationFeeOk() (*int32, bool) {
	if o == nil || IsNil(o.ApplicationFee) {
		return nil, false
	}
	return o.ApplicationFee, true
}

// HasApplicationFee returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasApplicationFee() bool {
	if o != nil && !IsNil(o.ApplicationFee) {
		return true
	}

	return false
}

// SetApplicationFee gets a reference to the given int32 and assigns it to the ApplicationFee field.
func (o *GatewayCreateRequest) SetApplicationFee(v int32) {
	o.ApplicationFee = &v
}

// GetReserveOnAuthorization returns the ReserveOnAuthorization field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetReserveOnAuthorization() bool {
	if o == nil || IsNil(o.ReserveOnAuthorization) {
		var ret bool
		return ret
	}
	return *o.ReserveOnAuthorization
}

// GetReserveOnAuthorizationOk returns a tuple with the ReserveOnAuthorization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetReserveOnAuthorizationOk() (*bool, bool) {
	if o == nil || IsNil(o.ReserveOnAuthorization) {
		return nil, false
	}
	return o.ReserveOnAuthorization, true
}

// HasReserveOnAuthorization returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasReserveOnAuthorization() bool {
	if o != nil && !IsNil(o.ReserveOnAuthorization) {
		return true
	}

	return false
}

// SetReserveOnAuthorization gets a reference to the given bool and assigns it to the ReserveOnAuthorization field.
func (o *GatewayCreateRequest) SetReserveOnAuthorization(v bool) {
	o.ReserveOnAuthorization = &v
}

// GetIsPriceExclusiveVat returns the IsPriceExclusiveVat field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetIsPriceExclusiveVat() bool {
	if o == nil || IsNil(o.IsPriceExclusiveVat) {
		var ret bool
		return ret
	}
	return *o.IsPriceExclusiveVat
}

// GetIsPriceExclusiveVatOk returns a tuple with the IsPriceExclusiveVat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetIsPriceExclusiveVatOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPriceExclusiveVat) {
		return nil, false
	}
	return o.IsPriceExclusiveVat, true
}

// HasIsPriceExclusiveVat returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasIsPriceExclusiveVat() bool {
	if o != nil && !IsNil(o.IsPriceExclusiveVat) {
		return true
	}

	return false
}

// SetIsPriceExclusiveVat gets a reference to the given bool and assigns it to the IsPriceExclusiveVat field.
func (o *GatewayCreateRequest) SetIsPriceExclusiveVat(v bool) {
	o.IsPriceExclusiveVat = &v
}

func (o GatewayCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount"] = o.Amount
	if !IsNil(o.VatRate) {
		toSerialize["vatRate"] = o.VatRate
	}
	toSerialize["currency"] = o.Currency
	if !IsNil(o.Sku) {
		toSerialize["sku"] = o.Sku
	}
	if !IsNil(o.Purpose) {
		toSerialize["purpose"] = o.Purpose
	}
	if !IsNil(o.SuccessRedirectUrl) {
		toSerialize["successRedirectUrl"] = o.SuccessRedirectUrl
	}
	if !IsNil(o.FailedRedirectUrl) {
		toSerialize["failedRedirectUrl"] = o.FailedRedirectUrl
	}
	if !IsNil(o.CancelRedirectUrl) {
		toSerialize["cancelRedirectUrl"] = o.CancelRedirectUrl
	}
	if !IsNil(o.Basket) {
		toSerialize["basket"] = o.Basket
	}
	if !IsNil(o.Psp) {
		toSerialize["psp"] = o.Psp
	}
	if !IsNil(o.Pm) {
		toSerialize["pm"] = o.Pm
	}
	if !IsNil(o.PreAuthorization) {
		toSerialize["preAuthorization"] = o.PreAuthorization
	}
	if !IsNil(o.Reservation) {
		toSerialize["reservation"] = o.Reservation
	}
	if !IsNil(o.ReferenceId) {
		toSerialize["referenceId"] = o.ReferenceId
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	if !IsNil(o.Language) {
		toSerialize["language"] = o.Language
	}
	if !IsNil(o.ConcardisOrderId) {
		toSerialize["concardisOrderId"] = o.ConcardisOrderId
	}
	if !IsNil(o.SkipResultPage) {
		toSerialize["skipResultPage"] = o.SkipResultPage
	}
	if !IsNil(o.ChargeOnAuthorization) {
		toSerialize["chargeOnAuthorization"] = o.ChargeOnAuthorization
	}
	if !IsNil(o.Validity) {
		toSerialize["validity"] = o.Validity
	}
	if !IsNil(o.SubscriptionState) {
		toSerialize["subscriptionState"] = o.SubscriptionState
	}
	if !IsNil(o.SubscriptionInterval) {
		toSerialize["subscriptionInterval"] = o.SubscriptionInterval
	}
	if !IsNil(o.SubscriptionPeriod) {
		toSerialize["subscriptionPeriod"] = o.SubscriptionPeriod
	}
	if !IsNil(o.SubscriptionCancellationInterval) {
		toSerialize["subscriptionCancellationInterval"] = o.SubscriptionCancellationInterval
	}
	if !IsNil(o.ButtonText) {
		toSerialize["buttonText"] = o.ButtonText
	}
	if !IsNil(o.LookAndFeelProfile) {
		toSerialize["lookAndFeelProfile"] = o.LookAndFeelProfile
	}
	if !IsNil(o.SuccessMessage) {
		toSerialize["successMessage"] = o.SuccessMessage
	}
	if !IsNil(o.QrCodeSessionId) {
		toSerialize["qrCodeSessionId"] = o.QrCodeSessionId
	}
	if !IsNil(o.ApplicationFee) {
		toSerialize["applicationFee"] = o.ApplicationFee
	}
	if !IsNil(o.ReserveOnAuthorization) {
		toSerialize["reserveOnAuthorization"] = o.ReserveOnAuthorization
	}
	if !IsNil(o.IsPriceExclusiveVat) {
		toSerialize["isPriceExclusiveVat"] = o.IsPriceExclusiveVat
	}
	return toSerialize, nil
}

func (o *GatewayCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount",
		"currency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGatewayCreateRequest := _GatewayCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGatewayCreateRequest)

	if err != nil {
		return err
	}

	*o = GatewayCreateRequest(varGatewayCreateRequest)

	return err
}

type NullableGatewayCreateRequest struct {
	value *GatewayCreateRequest
	isSet bool
}

func (v NullableGatewayCreateRequest) Get() *GatewayCreateRequest {
	return v.value
}

func (v *NullableGatewayCreateRequest) Set(val *GatewayCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayCreateRequest(val *GatewayCreateRequest) *NullableGatewayCreateRequest {
	return &NullableGatewayCreateRequest{value: val, isSet: true}
}

func (v NullableGatewayCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
