/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
)

// checks if the InvoiceCreatePaylinkRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoiceCreatePaylinkRequest{}

// InvoiceCreatePaylinkRequest struct for InvoiceCreatePaylinkRequest
type InvoiceCreatePaylinkRequest struct {
	// This is the page title which will be shown on the payment page.
	Title string `json:"title"`
	// This is a description which will be shown on the payment page.
	Description string `json:"description"`
	// An internal reference id used by your system.
	ReferenceId string `json:"referenceId"`
	// The purpose of the payment.
	Purpose string `json:"purpose"`
	// The amount of the payment in cents.
	Amount int32 `json:"amount"`
	// VAT rate percentage
	VatRate *float32 `json:"vatRate,omitempty"`
	// The currency of the payment.
	Currency string `json:"currency"`
	// The psp which should be used for the payment. (Can be an array of integers.)
	Psp []int32 `json:"psp,omitempty"`
	// List of payment mean names to display
	Pm []string `json:"pm,omitempty"`
	// Product stock keeping unit
	Sku *string `json:"sku,omitempty"`
	// Whether charge payment manually at a later date (type authorization).
	PreAuthorization *bool `json:"preAuthorization,omitempty"`
	// Whether charge payment manually at a later date (type reservation).
	Reservation *bool `json:"reservation,omitempty"`
	// This is an internal name of the payment page. This name will be displayed to the administrator only.
	Name *string `json:"name,omitempty"`
	// The contact data fields which should be displayed. See fields for more
	Fields []string `json:"fields,omitempty"`
	// Hide the whole contact fields section on invoice page
	HideFields *bool `json:"hideFields,omitempty"`
	// Only available for Concardis PSP and if the custom ORDERID option is activated in PSP settings in Payrexx administration. This ORDERID will be transferred to the Payengine.
	ConcardisOrderId *string `json:"concardisOrderId,omitempty"`
	// Custom pay button text.
	ButtonText *string `json:"buttonText,omitempty"`
	// Expiration date for link.
	ExpirationDate *string `json:"expirationDate,omitempty"`
	// URL to redirect to after successful payment.
	SuccessRedirectUrl *string `json:"successRedirectUrl,omitempty"`
	// URL to redirect to after failed payment.
	FailedRedirectUrl *string `json:"failedRedirectUrl,omitempty"`
	// Defines whether the payment should be handled as subscription.
	SubscriptionState *bool `json:"subscriptionState,omitempty"`
	// Payment interval
	SubscriptionInterval *string `json:"subscriptionInterval,omitempty"`
	// Duration of the subscription
	SubscriptionPeriod *string `json:"subscriptionPeriod,omitempty"`
	// Defines the period, in which a subscription can be canceled.
	SubscriptionCancellationInterval *string `json:"subscriptionCancellationInterval,omitempty"`
	// Provide your customers file attachments.
	Attachments **os.File `json:"attachments,omitempty"`
	// If set to true the Vat will be added on top of the price
	IsPriceExclusiveVat *bool `json:"isPriceExclusiveVat,omitempty"`
}

type _InvoiceCreatePaylinkRequest InvoiceCreatePaylinkRequest

// NewInvoiceCreatePaylinkRequest instantiates a new InvoiceCreatePaylinkRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceCreatePaylinkRequest(title string, description string, referenceId string, purpose string, amount int32, currency string) *InvoiceCreatePaylinkRequest {
	this := InvoiceCreatePaylinkRequest{}
	this.Title = title
	this.Description = description
	this.ReferenceId = referenceId
	this.Purpose = purpose
	this.Amount = amount
	this.Currency = currency
	var preAuthorization bool = false
	this.PreAuthorization = &preAuthorization
	var reservation bool = false
	this.Reservation = &reservation
	var hideFields bool = false
	this.HideFields = &hideFields
	var subscriptionState bool = false
	this.SubscriptionState = &subscriptionState
	return &this
}

// NewInvoiceCreatePaylinkRequestWithDefaults instantiates a new InvoiceCreatePaylinkRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceCreatePaylinkRequestWithDefaults() *InvoiceCreatePaylinkRequest {
	this := InvoiceCreatePaylinkRequest{}
	var preAuthorization bool = false
	this.PreAuthorization = &preAuthorization
	var reservation bool = false
	this.Reservation = &reservation
	var hideFields bool = false
	this.HideFields = &hideFields
	var subscriptionState bool = false
	this.SubscriptionState = &subscriptionState
	return &this
}

// GetTitle returns the Title field value
func (o *InvoiceCreatePaylinkRequest) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *InvoiceCreatePaylinkRequest) SetTitle(v string) {
	o.Title = v
}

// GetDescription returns the Description field value
func (o *InvoiceCreatePaylinkRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *InvoiceCreatePaylinkRequest) SetDescription(v string) {
	o.Description = v
}

// GetReferenceId returns the ReferenceId field value
func (o *InvoiceCreatePaylinkRequest) GetReferenceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReferenceId
}

// GetReferenceIdOk returns a tuple with the ReferenceId field value
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetReferenceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferenceId, true
}

// SetReferenceId sets field value
func (o *InvoiceCreatePaylinkRequest) SetReferenceId(v string) {
	o.ReferenceId = v
}

// GetPurpose returns the Purpose field value
func (o *InvoiceCreatePaylinkRequest) GetPurpose() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Purpose
}

// GetPurposeOk returns a tuple with the Purpose field value
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetPurposeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Purpose, true
}

// SetPurpose sets field value
func (o *InvoiceCreatePaylinkRequest) SetPurpose(v string) {
	o.Purpose = v
}

// GetAmount returns the Amount field value
func (o *InvoiceCreatePaylinkRequest) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *InvoiceCreatePaylinkRequest) SetAmount(v int32) {
	o.Amount = v
}

// GetVatRate returns the VatRate field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetVatRate() float32 {
	if o == nil || IsNil(o.VatRate) {
		var ret float32
		return ret
	}
	return *o.VatRate
}

// GetVatRateOk returns a tuple with the VatRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetVatRateOk() (*float32, bool) {
	if o == nil || IsNil(o.VatRate) {
		return nil, false
	}
	return o.VatRate, true
}

// HasVatRate returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasVatRate() bool {
	if o != nil && !IsNil(o.VatRate) {
		return true
	}

	return false
}

// SetVatRate gets a reference to the given float32 and assigns it to the VatRate field.
func (o *InvoiceCreatePaylinkRequest) SetVatRate(v float32) {
	o.VatRate = &v
}

// GetCurrency returns the Currency field value
func (o *InvoiceCreatePaylinkRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *InvoiceCreatePaylinkRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetPsp returns the Psp field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetPsp() []int32 {
	if o == nil || IsNil(o.Psp) {
		var ret []int32
		return ret
	}
	return o.Psp
}

// GetPspOk returns a tuple with the Psp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetPspOk() ([]int32, bool) {
	if o == nil || IsNil(o.Psp) {
		return nil, false
	}
	return o.Psp, true
}

// HasPsp returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasPsp() bool {
	if o != nil && !IsNil(o.Psp) {
		return true
	}

	return false
}

// SetPsp gets a reference to the given []int32 and assigns it to the Psp field.
func (o *InvoiceCreatePaylinkRequest) SetPsp(v []int32) {
	o.Psp = v
}

// GetPm returns the Pm field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetPm() []string {
	if o == nil || IsNil(o.Pm) {
		var ret []string
		return ret
	}
	return o.Pm
}

// GetPmOk returns a tuple with the Pm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetPmOk() ([]string, bool) {
	if o == nil || IsNil(o.Pm) {
		return nil, false
	}
	return o.Pm, true
}

// HasPm returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasPm() bool {
	if o != nil && !IsNil(o.Pm) {
		return true
	}

	return false
}

// SetPm gets a reference to the given []string and assigns it to the Pm field.
func (o *InvoiceCreatePaylinkRequest) SetPm(v []string) {
	o.Pm = v
}

// GetSku returns the Sku field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetSku() string {
	if o == nil || IsNil(o.Sku) {
		var ret string
		return ret
	}
	return *o.Sku
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetSkuOk() (*string, bool) {
	if o == nil || IsNil(o.Sku) {
		return nil, false
	}
	return o.Sku, true
}

// HasSku returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasSku() bool {
	if o != nil && !IsNil(o.Sku) {
		return true
	}

	return false
}

// SetSku gets a reference to the given string and assigns it to the Sku field.
func (o *InvoiceCreatePaylinkRequest) SetSku(v string) {
	o.Sku = &v
}

// GetPreAuthorization returns the PreAuthorization field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetPreAuthorization() bool {
	if o == nil || IsNil(o.PreAuthorization) {
		var ret bool
		return ret
	}
	return *o.PreAuthorization
}

// GetPreAuthorizationOk returns a tuple with the PreAuthorization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetPreAuthorizationOk() (*bool, bool) {
	if o == nil || IsNil(o.PreAuthorization) {
		return nil, false
	}
	return o.PreAuthorization, true
}

// HasPreAuthorization returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasPreAuthorization() bool {
	if o != nil && !IsNil(o.PreAuthorization) {
		return true
	}

	return false
}

// SetPreAuthorization gets a reference to the given bool and assigns it to the PreAuthorization field.
func (o *InvoiceCreatePaylinkRequest) SetPreAuthorization(v bool) {
	o.PreAuthorization = &v
}

// GetReservation returns the Reservation field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetReservation() bool {
	if o == nil || IsNil(o.Reservation) {
		var ret bool
		return ret
	}
	return *o.Reservation
}

// GetReservationOk returns a tuple with the Reservation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetReservationOk() (*bool, bool) {
	if o == nil || IsNil(o.Reservation) {
		return nil, false
	}
	return o.Reservation, true
}

// HasReservation returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasReservation() bool {
	if o != nil && !IsNil(o.Reservation) {
		return true
	}

	return false
}

// SetReservation gets a reference to the given bool and assigns it to the Reservation field.
func (o *InvoiceCreatePaylinkRequest) SetReservation(v bool) {
	o.Reservation = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InvoiceCreatePaylinkRequest) SetName(v string) {
	o.Name = &v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetFields() []string {
	if o == nil || IsNil(o.Fields) {
		var ret []string
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetFieldsOk() ([]string, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []string and assigns it to the Fields field.
func (o *InvoiceCreatePaylinkRequest) SetFields(v []string) {
	o.Fields = v
}

// GetHideFields returns the HideFields field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetHideFields() bool {
	if o == nil || IsNil(o.HideFields) {
		var ret bool
		return ret
	}
	return *o.HideFields
}

// GetHideFieldsOk returns a tuple with the HideFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetHideFieldsOk() (*bool, bool) {
	if o == nil || IsNil(o.HideFields) {
		return nil, false
	}
	return o.HideFields, true
}

// HasHideFields returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasHideFields() bool {
	if o != nil && !IsNil(o.HideFields) {
		return true
	}

	return false
}

// SetHideFields gets a reference to the given bool and assigns it to the HideFields field.
func (o *InvoiceCreatePaylinkRequest) SetHideFields(v bool) {
	o.HideFields = &v
}

// GetConcardisOrderId returns the ConcardisOrderId field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetConcardisOrderId() string {
	if o == nil || IsNil(o.ConcardisOrderId) {
		var ret string
		return ret
	}
	return *o.ConcardisOrderId
}

// GetConcardisOrderIdOk returns a tuple with the ConcardisOrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetConcardisOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConcardisOrderId) {
		return nil, false
	}
	return o.ConcardisOrderId, true
}

// HasConcardisOrderId returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasConcardisOrderId() bool {
	if o != nil && !IsNil(o.ConcardisOrderId) {
		return true
	}

	return false
}

// SetConcardisOrderId gets a reference to the given string and assigns it to the ConcardisOrderId field.
func (o *InvoiceCreatePaylinkRequest) SetConcardisOrderId(v string) {
	o.ConcardisOrderId = &v
}

// GetButtonText returns the ButtonText field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetButtonText() string {
	if o == nil || IsNil(o.ButtonText) {
		var ret string
		return ret
	}
	return *o.ButtonText
}

// GetButtonTextOk returns a tuple with the ButtonText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetButtonTextOk() (*string, bool) {
	if o == nil || IsNil(o.ButtonText) {
		return nil, false
	}
	return o.ButtonText, true
}

// HasButtonText returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasButtonText() bool {
	if o != nil && !IsNil(o.ButtonText) {
		return true
	}

	return false
}

// SetButtonText gets a reference to the given string and assigns it to the ButtonText field.
func (o *InvoiceCreatePaylinkRequest) SetButtonText(v string) {
	o.ButtonText = &v
}

// GetExpirationDate returns the ExpirationDate field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetExpirationDate() string {
	if o == nil || IsNil(o.ExpirationDate) {
		var ret string
		return ret
	}
	return *o.ExpirationDate
}

// GetExpirationDateOk returns a tuple with the ExpirationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetExpirationDateOk() (*string, bool) {
	if o == nil || IsNil(o.ExpirationDate) {
		return nil, false
	}
	return o.ExpirationDate, true
}

// HasExpirationDate returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasExpirationDate() bool {
	if o != nil && !IsNil(o.ExpirationDate) {
		return true
	}

	return false
}

// SetExpirationDate gets a reference to the given string and assigns it to the ExpirationDate field.
func (o *InvoiceCreatePaylinkRequest) SetExpirationDate(v string) {
	o.ExpirationDate = &v
}

// GetSuccessRedirectUrl returns the SuccessRedirectUrl field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetSuccessRedirectUrl() string {
	if o == nil || IsNil(o.SuccessRedirectUrl) {
		var ret string
		return ret
	}
	return *o.SuccessRedirectUrl
}

// GetSuccessRedirectUrlOk returns a tuple with the SuccessRedirectUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetSuccessRedirectUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SuccessRedirectUrl) {
		return nil, false
	}
	return o.SuccessRedirectUrl, true
}

// HasSuccessRedirectUrl returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasSuccessRedirectUrl() bool {
	if o != nil && !IsNil(o.SuccessRedirectUrl) {
		return true
	}

	return false
}

// SetSuccessRedirectUrl gets a reference to the given string and assigns it to the SuccessRedirectUrl field.
func (o *InvoiceCreatePaylinkRequest) SetSuccessRedirectUrl(v string) {
	o.SuccessRedirectUrl = &v
}

// GetFailedRedirectUrl returns the FailedRedirectUrl field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetFailedRedirectUrl() string {
	if o == nil || IsNil(o.FailedRedirectUrl) {
		var ret string
		return ret
	}
	return *o.FailedRedirectUrl
}

// GetFailedRedirectUrlOk returns a tuple with the FailedRedirectUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetFailedRedirectUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FailedRedirectUrl) {
		return nil, false
	}
	return o.FailedRedirectUrl, true
}

// HasFailedRedirectUrl returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasFailedRedirectUrl() bool {
	if o != nil && !IsNil(o.FailedRedirectUrl) {
		return true
	}

	return false
}

// SetFailedRedirectUrl gets a reference to the given string and assigns it to the FailedRedirectUrl field.
func (o *InvoiceCreatePaylinkRequest) SetFailedRedirectUrl(v string) {
	o.FailedRedirectUrl = &v
}

// GetSubscriptionState returns the SubscriptionState field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetSubscriptionState() bool {
	if o == nil || IsNil(o.SubscriptionState) {
		var ret bool
		return ret
	}
	return *o.SubscriptionState
}

// GetSubscriptionStateOk returns a tuple with the SubscriptionState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetSubscriptionStateOk() (*bool, bool) {
	if o == nil || IsNil(o.SubscriptionState) {
		return nil, false
	}
	return o.SubscriptionState, true
}

// HasSubscriptionState returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasSubscriptionState() bool {
	if o != nil && !IsNil(o.SubscriptionState) {
		return true
	}

	return false
}

// SetSubscriptionState gets a reference to the given bool and assigns it to the SubscriptionState field.
func (o *InvoiceCreatePaylinkRequest) SetSubscriptionState(v bool) {
	o.SubscriptionState = &v
}

// GetSubscriptionInterval returns the SubscriptionInterval field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetSubscriptionInterval() string {
	if o == nil || IsNil(o.SubscriptionInterval) {
		var ret string
		return ret
	}
	return *o.SubscriptionInterval
}

// GetSubscriptionIntervalOk returns a tuple with the SubscriptionInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetSubscriptionIntervalOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionInterval) {
		return nil, false
	}
	return o.SubscriptionInterval, true
}

// HasSubscriptionInterval returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasSubscriptionInterval() bool {
	if o != nil && !IsNil(o.SubscriptionInterval) {
		return true
	}

	return false
}

// SetSubscriptionInterval gets a reference to the given string and assigns it to the SubscriptionInterval field.
func (o *InvoiceCreatePaylinkRequest) SetSubscriptionInterval(v string) {
	o.SubscriptionInterval = &v
}

// GetSubscriptionPeriod returns the SubscriptionPeriod field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetSubscriptionPeriod() string {
	if o == nil || IsNil(o.SubscriptionPeriod) {
		var ret string
		return ret
	}
	return *o.SubscriptionPeriod
}

// GetSubscriptionPeriodOk returns a tuple with the SubscriptionPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetSubscriptionPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionPeriod) {
		return nil, false
	}
	return o.SubscriptionPeriod, true
}

// HasSubscriptionPeriod returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasSubscriptionPeriod() bool {
	if o != nil && !IsNil(o.SubscriptionPeriod) {
		return true
	}

	return false
}

// SetSubscriptionPeriod gets a reference to the given string and assigns it to the SubscriptionPeriod field.
func (o *InvoiceCreatePaylinkRequest) SetSubscriptionPeriod(v string) {
	o.SubscriptionPeriod = &v
}

// GetSubscriptionCancellationInterval returns the SubscriptionCancellationInterval field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetSubscriptionCancellationInterval() string {
	if o == nil || IsNil(o.SubscriptionCancellationInterval) {
		var ret string
		return ret
	}
	return *o.SubscriptionCancellationInterval
}

// GetSubscriptionCancellationIntervalOk returns a tuple with the SubscriptionCancellationInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetSubscriptionCancellationIntervalOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionCancellationInterval) {
		return nil, false
	}
	return o.SubscriptionCancellationInterval, true
}

// HasSubscriptionCancellationInterval returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasSubscriptionCancellationInterval() bool {
	if o != nil && !IsNil(o.SubscriptionCancellationInterval) {
		return true
	}

	return false
}

// SetSubscriptionCancellationInterval gets a reference to the given string and assigns it to the SubscriptionCancellationInterval field.
func (o *InvoiceCreatePaylinkRequest) SetSubscriptionCancellationInterval(v string) {
	o.SubscriptionCancellationInterval = &v
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetAttachments() *os.File {
	if o == nil || IsNil(o.Attachments) {
		var ret *os.File
		return ret
	}
	return *o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetAttachmentsOk() (**os.File, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given *os.File and assigns it to the Attachments field.
func (o *InvoiceCreatePaylinkRequest) SetAttachments(v *os.File) {
	o.Attachments = &v
}

// GetIsPriceExclusiveVat returns the IsPriceExclusiveVat field value if set, zero value otherwise.
func (o *InvoiceCreatePaylinkRequest) GetIsPriceExclusiveVat() bool {
	if o == nil || IsNil(o.IsPriceExclusiveVat) {
		var ret bool
		return ret
	}
	return *o.IsPriceExclusiveVat
}

// GetIsPriceExclusiveVatOk returns a tuple with the IsPriceExclusiveVat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCreatePaylinkRequest) GetIsPriceExclusiveVatOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPriceExclusiveVat) {
		return nil, false
	}
	return o.IsPriceExclusiveVat, true
}

// HasIsPriceExclusiveVat returns a boolean if a field has been set.
func (o *InvoiceCreatePaylinkRequest) HasIsPriceExclusiveVat() bool {
	if o != nil && !IsNil(o.IsPriceExclusiveVat) {
		return true
	}

	return false
}

// SetIsPriceExclusiveVat gets a reference to the given bool and assigns it to the IsPriceExclusiveVat field.
func (o *InvoiceCreatePaylinkRequest) SetIsPriceExclusiveVat(v bool) {
	o.IsPriceExclusiveVat = &v
}

func (o InvoiceCreatePaylinkRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoiceCreatePaylinkRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["title"] = o.Title
	toSerialize["description"] = o.Description
	toSerialize["referenceId"] = o.ReferenceId
	toSerialize["purpose"] = o.Purpose
	toSerialize["amount"] = o.Amount
	if !IsNil(o.VatRate) {
		toSerialize["vatRate"] = o.VatRate
	}
	toSerialize["currency"] = o.Currency
	if !IsNil(o.Psp) {
		toSerialize["psp"] = o.Psp
	}
	if !IsNil(o.Pm) {
		toSerialize["pm"] = o.Pm
	}
	if !IsNil(o.Sku) {
		toSerialize["sku"] = o.Sku
	}
	if !IsNil(o.PreAuthorization) {
		toSerialize["preAuthorization"] = o.PreAuthorization
	}
	if !IsNil(o.Reservation) {
		toSerialize["reservation"] = o.Reservation
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	if !IsNil(o.HideFields) {
		toSerialize["hideFields"] = o.HideFields
	}
	if !IsNil(o.ConcardisOrderId) {
		toSerialize["concardisOrderId"] = o.ConcardisOrderId
	}
	if !IsNil(o.ButtonText) {
		toSerialize["buttonText"] = o.ButtonText
	}
	if !IsNil(o.ExpirationDate) {
		toSerialize["expirationDate"] = o.ExpirationDate
	}
	if !IsNil(o.SuccessRedirectUrl) {
		toSerialize["successRedirectUrl"] = o.SuccessRedirectUrl
	}
	if !IsNil(o.FailedRedirectUrl) {
		toSerialize["failedRedirectUrl"] = o.FailedRedirectUrl
	}
	if !IsNil(o.SubscriptionState) {
		toSerialize["subscriptionState"] = o.SubscriptionState
	}
	if !IsNil(o.SubscriptionInterval) {
		toSerialize["subscriptionInterval"] = o.SubscriptionInterval
	}
	if !IsNil(o.SubscriptionPeriod) {
		toSerialize["subscriptionPeriod"] = o.SubscriptionPeriod
	}
	if !IsNil(o.SubscriptionCancellationInterval) {
		toSerialize["subscriptionCancellationInterval"] = o.SubscriptionCancellationInterval
	}
	if !IsNil(o.Attachments) {
		toSerialize["attachments"] = o.Attachments
	}
	if !IsNil(o.IsPriceExclusiveVat) {
		toSerialize["isPriceExclusiveVat"] = o.IsPriceExclusiveVat
	}
	return toSerialize, nil
}

func (o *InvoiceCreatePaylinkRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"description",
		"referenceId",
		"purpose",
		"amount",
		"currency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInvoiceCreatePaylinkRequest := _InvoiceCreatePaylinkRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInvoiceCreatePaylinkRequest)

	if err != nil {
		return err
	}

	*o = InvoiceCreatePaylinkRequest(varInvoiceCreatePaylinkRequest)

	return err
}

type NullableInvoiceCreatePaylinkRequest struct {
	value *InvoiceCreatePaylinkRequest
	isSet bool
}

func (v NullableInvoiceCreatePaylinkRequest) Get() *InvoiceCreatePaylinkRequest {
	return v.value
}

func (v *NullableInvoiceCreatePaylinkRequest) Set(val *InvoiceCreatePaylinkRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceCreatePaylinkRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceCreatePaylinkRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceCreatePaylinkRequest(val *InvoiceCreatePaylinkRequest) *NullableInvoiceCreatePaylinkRequest {
	return &NullableInvoiceCreatePaylinkRequest{value: val, isSet: true}
}

func (v NullableInvoiceCreatePaylinkRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceCreatePaylinkRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
