/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the PaylinkFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaylinkFields{}

// PaylinkFields struct for PaylinkFields
type PaylinkFields struct {
	Title         *GatewayFieldsTitle       `json:"title,omitempty"`
	Forename      *GatewayFieldsTitle       `json:"forename,omitempty"`
	Surname       *GatewayFieldsTitle       `json:"surname,omitempty"`
	Company       *GatewayFieldsTitle       `json:"company,omitempty"`
	Street        *GatewayFieldsTitle       `json:"street,omitempty"`
	Postcode      *GatewayFieldsTitle       `json:"postcode,omitempty"`
	Place         *GatewayFieldsTitle       `json:"place,omitempty"`
	Country       *GatewayFieldsTitle       `json:"country,omitempty"`
	Phone         *GatewayFieldsTitle       `json:"phone,omitempty"`
	Email         *GatewayFieldsTitle       `json:"email,omitempty"`
	DateOfBirth   *GatewayFieldsTitle       `json:"date_of_birth,omitempty"`
	Terms         *GatewayFieldsTitle       `json:"terms,omitempty"`
	PrivacyPolicy *GatewayFieldsTitle       `json:"privacy_policy,omitempty"`
	CustomField1  *GatewayFieldsDateOfBirth `json:"custom_field_1,omitempty"`
	CustomField2  *GatewayFieldsDateOfBirth `json:"custom_field_2,omitempty"`
	CustomField3  *GatewayFieldsDateOfBirth `json:"custom_field_3,omitempty"`
}

// NewPaylinkFields instantiates a new PaylinkFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaylinkFields() *PaylinkFields {
	this := PaylinkFields{}
	return &this
}

// NewPaylinkFieldsWithDefaults instantiates a new PaylinkFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaylinkFieldsWithDefaults() *PaylinkFields {
	this := PaylinkFields{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *PaylinkFields) GetTitle() GatewayFieldsTitle {
	if o == nil || IsNil(o.Title) {
		var ret GatewayFieldsTitle
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaylinkFields) GetTitleOk() (*GatewayFieldsTitle, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *PaylinkFields) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given GatewayFieldsTitle and assigns it to the Title field.
func (o *PaylinkFields) SetTitle(v GatewayFieldsTitle) {
	o.Title = &v
}

// GetForename returns the Forename field value if set, zero value otherwise.
func (o *PaylinkFields) GetForename() GatewayFieldsTitle {
	if o == nil || IsNil(o.Forename) {
		var ret GatewayFieldsTitle
		return ret
	}
	return *o.Forename
}

// GetForenameOk returns a tuple with the Forename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaylinkFields) GetForenameOk() (*GatewayFieldsTitle, bool) {
	if o == nil || IsNil(o.Forename) {
		return nil, false
	}
	return o.Forename, true
}

// HasForename returns a boolean if a field has been set.
func (o *PaylinkFields) HasForename() bool {
	if o != nil && !IsNil(o.Forename) {
		return true
	}

	return false
}

// SetForename gets a reference to the given GatewayFieldsTitle and assigns it to the Forename field.
func (o *PaylinkFields) SetForename(v GatewayFieldsTitle) {
	o.Forename = &v
}

// GetSurname returns the Surname field value if set, zero value otherwise.
func (o *PaylinkFields) GetSurname() GatewayFieldsTitle {
	if o == nil || IsNil(o.Surname) {
		var ret GatewayFieldsTitle
		return ret
	}
	return *o.Surname
}

// GetSurnameOk returns a tuple with the Surname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaylinkFields) GetSurnameOk() (*GatewayFieldsTitle, bool) {
	if o == nil || IsNil(o.Surname) {
		return nil, false
	}
	return o.Surname, true
}

// HasSurname returns a boolean if a field has been set.
func (o *PaylinkFields) HasSurname() bool {
	if o != nil && !IsNil(o.Surname) {
		return true
	}

	return false
}

// SetSurname gets a reference to the given GatewayFieldsTitle and assigns it to the Surname field.
func (o *PaylinkFields) SetSurname(v GatewayFieldsTitle) {
	o.Surname = &v
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *PaylinkFields) GetCompany() GatewayFieldsTitle {
	if o == nil || IsNil(o.Company) {
		var ret GatewayFieldsTitle
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaylinkFields) GetCompanyOk() (*GatewayFieldsTitle, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *PaylinkFields) HasCompany() bool {
	if o != nil && !IsNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given GatewayFieldsTitle and assigns it to the Company field.
func (o *PaylinkFields) SetCompany(v GatewayFieldsTitle) {
	o.Company = &v
}

// GetStreet returns the Street field value if set, zero value otherwise.
func (o *PaylinkFields) GetStreet() GatewayFieldsTitle {
	if o == nil || IsNil(o.Street) {
		var ret GatewayFieldsTitle
		return ret
	}
	return *o.Street
}

// GetStreetOk returns a tuple with the Street field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaylinkFields) GetStreetOk() (*GatewayFieldsTitle, bool) {
	if o == nil || IsNil(o.Street) {
		return nil, false
	}
	return o.Street, true
}

// HasStreet returns a boolean if a field has been set.
func (o *PaylinkFields) HasStreet() bool {
	if o != nil && !IsNil(o.Street) {
		return true
	}

	return false
}

// SetStreet gets a reference to the given GatewayFieldsTitle and assigns it to the Street field.
func (o *PaylinkFields) SetStreet(v GatewayFieldsTitle) {
	o.Street = &v
}

// GetPostcode returns the Postcode field value if set, zero value otherwise.
func (o *PaylinkFields) GetPostcode() GatewayFieldsTitle {
	if o == nil || IsNil(o.Postcode) {
		var ret GatewayFieldsTitle
		return ret
	}
	return *o.Postcode
}

// GetPostcodeOk returns a tuple with the Postcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaylinkFields) GetPostcodeOk() (*GatewayFieldsTitle, bool) {
	if o == nil || IsNil(o.Postcode) {
		return nil, false
	}
	return o.Postcode, true
}

// HasPostcode returns a boolean if a field has been set.
func (o *PaylinkFields) HasPostcode() bool {
	if o != nil && !IsNil(o.Postcode) {
		return true
	}

	return false
}

// SetPostcode gets a reference to the given GatewayFieldsTitle and assigns it to the Postcode field.
func (o *PaylinkFields) SetPostcode(v GatewayFieldsTitle) {
	o.Postcode = &v
}

// GetPlace returns the Place field value if set, zero value otherwise.
func (o *PaylinkFields) GetPlace() GatewayFieldsTitle {
	if o == nil || IsNil(o.Place) {
		var ret GatewayFieldsTitle
		return ret
	}
	return *o.Place
}

// GetPlaceOk returns a tuple with the Place field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaylinkFields) GetPlaceOk() (*GatewayFieldsTitle, bool) {
	if o == nil || IsNil(o.Place) {
		return nil, false
	}
	return o.Place, true
}

// HasPlace returns a boolean if a field has been set.
func (o *PaylinkFields) HasPlace() bool {
	if o != nil && !IsNil(o.Place) {
		return true
	}

	return false
}

// SetPlace gets a reference to the given GatewayFieldsTitle and assigns it to the Place field.
func (o *PaylinkFields) SetPlace(v GatewayFieldsTitle) {
	o.Place = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *PaylinkFields) GetCountry() GatewayFieldsTitle {
	if o == nil || IsNil(o.Country) {
		var ret GatewayFieldsTitle
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaylinkFields) GetCountryOk() (*GatewayFieldsTitle, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *PaylinkFields) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given GatewayFieldsTitle and assigns it to the Country field.
func (o *PaylinkFields) SetCountry(v GatewayFieldsTitle) {
	o.Country = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *PaylinkFields) GetPhone() GatewayFieldsTitle {
	if o == nil || IsNil(o.Phone) {
		var ret GatewayFieldsTitle
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaylinkFields) GetPhoneOk() (*GatewayFieldsTitle, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *PaylinkFields) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given GatewayFieldsTitle and assigns it to the Phone field.
func (o *PaylinkFields) SetPhone(v GatewayFieldsTitle) {
	o.Phone = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *PaylinkFields) GetEmail() GatewayFieldsTitle {
	if o == nil || IsNil(o.Email) {
		var ret GatewayFieldsTitle
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaylinkFields) GetEmailOk() (*GatewayFieldsTitle, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *PaylinkFields) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given GatewayFieldsTitle and assigns it to the Email field.
func (o *PaylinkFields) SetEmail(v GatewayFieldsTitle) {
	o.Email = &v
}

// GetDateOfBirth returns the DateOfBirth field value if set, zero value otherwise.
func (o *PaylinkFields) GetDateOfBirth() GatewayFieldsTitle {
	if o == nil || IsNil(o.DateOfBirth) {
		var ret GatewayFieldsTitle
		return ret
	}
	return *o.DateOfBirth
}

// GetDateOfBirthOk returns a tuple with the DateOfBirth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaylinkFields) GetDateOfBirthOk() (*GatewayFieldsTitle, bool) {
	if o == nil || IsNil(o.DateOfBirth) {
		return nil, false
	}
	return o.DateOfBirth, true
}

// HasDateOfBirth returns a boolean if a field has been set.
func (o *PaylinkFields) HasDateOfBirth() bool {
	if o != nil && !IsNil(o.DateOfBirth) {
		return true
	}

	return false
}

// SetDateOfBirth gets a reference to the given GatewayFieldsTitle and assigns it to the DateOfBirth field.
func (o *PaylinkFields) SetDateOfBirth(v GatewayFieldsTitle) {
	o.DateOfBirth = &v
}

// GetTerms returns the Terms field value if set, zero value otherwise.
func (o *PaylinkFields) GetTerms() GatewayFieldsTitle {
	if o == nil || IsNil(o.Terms) {
		var ret GatewayFieldsTitle
		return ret
	}
	return *o.Terms
}

// GetTermsOk returns a tuple with the Terms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaylinkFields) GetTermsOk() (*GatewayFieldsTitle, bool) {
	if o == nil || IsNil(o.Terms) {
		return nil, false
	}
	return o.Terms, true
}

// HasTerms returns a boolean if a field has been set.
func (o *PaylinkFields) HasTerms() bool {
	if o != nil && !IsNil(o.Terms) {
		return true
	}

	return false
}

// SetTerms gets a reference to the given GatewayFieldsTitle and assigns it to the Terms field.
func (o *PaylinkFields) SetTerms(v GatewayFieldsTitle) {
	o.Terms = &v
}

// GetPrivacyPolicy returns the PrivacyPolicy field value if set, zero value otherwise.
func (o *PaylinkFields) GetPrivacyPolicy() GatewayFieldsTitle {
	if o == nil || IsNil(o.PrivacyPolicy) {
		var ret GatewayFieldsTitle
		return ret
	}
	return *o.PrivacyPolicy
}

// GetPrivacyPolicyOk returns a tuple with the PrivacyPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaylinkFields) GetPrivacyPolicyOk() (*GatewayFieldsTitle, bool) {
	if o == nil || IsNil(o.PrivacyPolicy) {
		return nil, false
	}
	return o.PrivacyPolicy, true
}

// HasPrivacyPolicy returns a boolean if a field has been set.
func (o *PaylinkFields) HasPrivacyPolicy() bool {
	if o != nil && !IsNil(o.PrivacyPolicy) {
		return true
	}

	return false
}

// SetPrivacyPolicy gets a reference to the given GatewayFieldsTitle and assigns it to the PrivacyPolicy field.
func (o *PaylinkFields) SetPrivacyPolicy(v GatewayFieldsTitle) {
	o.PrivacyPolicy = &v
}

// GetCustomField1 returns the CustomField1 field value if set, zero value otherwise.
func (o *PaylinkFields) GetCustomField1() GatewayFieldsDateOfBirth {
	if o == nil || IsNil(o.CustomField1) {
		var ret GatewayFieldsDateOfBirth
		return ret
	}
	return *o.CustomField1
}

// GetCustomField1Ok returns a tuple with the CustomField1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaylinkFields) GetCustomField1Ok() (*GatewayFieldsDateOfBirth, bool) {
	if o == nil || IsNil(o.CustomField1) {
		return nil, false
	}
	return o.CustomField1, true
}

// HasCustomField1 returns a boolean if a field has been set.
func (o *PaylinkFields) HasCustomField1() bool {
	if o != nil && !IsNil(o.CustomField1) {
		return true
	}

	return false
}

// SetCustomField1 gets a reference to the given GatewayFieldsDateOfBirth and assigns it to the CustomField1 field.
func (o *PaylinkFields) SetCustomField1(v GatewayFieldsDateOfBirth) {
	o.CustomField1 = &v
}

// GetCustomField2 returns the CustomField2 field value if set, zero value otherwise.
func (o *PaylinkFields) GetCustomField2() GatewayFieldsDateOfBirth {
	if o == nil || IsNil(o.CustomField2) {
		var ret GatewayFieldsDateOfBirth
		return ret
	}
	return *o.CustomField2
}

// GetCustomField2Ok returns a tuple with the CustomField2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaylinkFields) GetCustomField2Ok() (*GatewayFieldsDateOfBirth, bool) {
	if o == nil || IsNil(o.CustomField2) {
		return nil, false
	}
	return o.CustomField2, true
}

// HasCustomField2 returns a boolean if a field has been set.
func (o *PaylinkFields) HasCustomField2() bool {
	if o != nil && !IsNil(o.CustomField2) {
		return true
	}

	return false
}

// SetCustomField2 gets a reference to the given GatewayFieldsDateOfBirth and assigns it to the CustomField2 field.
func (o *PaylinkFields) SetCustomField2(v GatewayFieldsDateOfBirth) {
	o.CustomField2 = &v
}

// GetCustomField3 returns the CustomField3 field value if set, zero value otherwise.
func (o *PaylinkFields) GetCustomField3() GatewayFieldsDateOfBirth {
	if o == nil || IsNil(o.CustomField3) {
		var ret GatewayFieldsDateOfBirth
		return ret
	}
	return *o.CustomField3
}

// GetCustomField3Ok returns a tuple with the CustomField3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaylinkFields) GetCustomField3Ok() (*GatewayFieldsDateOfBirth, bool) {
	if o == nil || IsNil(o.CustomField3) {
		return nil, false
	}
	return o.CustomField3, true
}

// HasCustomField3 returns a boolean if a field has been set.
func (o *PaylinkFields) HasCustomField3() bool {
	if o != nil && !IsNil(o.CustomField3) {
		return true
	}

	return false
}

// SetCustomField3 gets a reference to the given GatewayFieldsDateOfBirth and assigns it to the CustomField3 field.
func (o *PaylinkFields) SetCustomField3(v GatewayFieldsDateOfBirth) {
	o.CustomField3 = &v
}

func (o PaylinkFields) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaylinkFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Forename) {
		toSerialize["forename"] = o.Forename
	}
	if !IsNil(o.Surname) {
		toSerialize["surname"] = o.Surname
	}
	if !IsNil(o.Company) {
		toSerialize["company"] = o.Company
	}
	if !IsNil(o.Street) {
		toSerialize["street"] = o.Street
	}
	if !IsNil(o.Postcode) {
		toSerialize["postcode"] = o.Postcode
	}
	if !IsNil(o.Place) {
		toSerialize["place"] = o.Place
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.DateOfBirth) {
		toSerialize["date_of_birth"] = o.DateOfBirth
	}
	if !IsNil(o.Terms) {
		toSerialize["terms"] = o.Terms
	}
	if !IsNil(o.PrivacyPolicy) {
		toSerialize["privacy_policy"] = o.PrivacyPolicy
	}
	if !IsNil(o.CustomField1) {
		toSerialize["custom_field_1"] = o.CustomField1
	}
	if !IsNil(o.CustomField2) {
		toSerialize["custom_field_2"] = o.CustomField2
	}
	if !IsNil(o.CustomField3) {
		toSerialize["custom_field_3"] = o.CustomField3
	}
	return toSerialize, nil
}

type NullablePaylinkFields struct {
	value *PaylinkFields
	isSet bool
}

func (v NullablePaylinkFields) Get() *PaylinkFields {
	return v.value
}

func (v *NullablePaylinkFields) Set(val *PaylinkFields) {
	v.value = val
	v.isSet = true
}

func (v NullablePaylinkFields) IsSet() bool {
	return v.isSet
}

func (v *NullablePaylinkFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaylinkFields(val *PaylinkFields) *NullablePaylinkFields {
	return &NullablePaylinkFields{value: val, isSet: true}
}

func (v NullablePaylinkFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaylinkFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
