/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EcrPairRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EcrPairRequest{}

// EcrPairRequest struct for EcrPairRequest
type EcrPairRequest struct {
	PairingCode string `json:"pairingCode"`
	//
	CashierName *string `json:"cashierName,omitempty"`
}

type _EcrPairRequest EcrPairRequest

// NewEcrPairRequest instantiates a new EcrPairRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEcrPairRequest(pairingCode string) *EcrPairRequest {
	this := EcrPairRequest{}
	this.PairingCode = pairingCode
	var cashierName string = "terminalName"
	this.CashierName = &cashierName
	return &this
}

// NewEcrPairRequestWithDefaults instantiates a new EcrPairRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEcrPairRequestWithDefaults() *EcrPairRequest {
	this := EcrPairRequest{}
	var cashierName string = "terminalName"
	this.CashierName = &cashierName
	return &this
}

// GetPairingCode returns the PairingCode field value
func (o *EcrPairRequest) GetPairingCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PairingCode
}

// GetPairingCodeOk returns a tuple with the PairingCode field value
// and a boolean to check if the value has been set.
func (o *EcrPairRequest) GetPairingCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PairingCode, true
}

// SetPairingCode sets field value
func (o *EcrPairRequest) SetPairingCode(v string) {
	o.PairingCode = v
}

// GetCashierName returns the CashierName field value if set, zero value otherwise.
func (o *EcrPairRequest) GetCashierName() string {
	if o == nil || IsNil(o.CashierName) {
		var ret string
		return ret
	}
	return *o.CashierName
}

// GetCashierNameOk returns a tuple with the CashierName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EcrPairRequest) GetCashierNameOk() (*string, bool) {
	if o == nil || IsNil(o.CashierName) {
		return nil, false
	}
	return o.CashierName, true
}

// HasCashierName returns a boolean if a field has been set.
func (o *EcrPairRequest) HasCashierName() bool {
	if o != nil && !IsNil(o.CashierName) {
		return true
	}

	return false
}

// SetCashierName gets a reference to the given string and assigns it to the CashierName field.
func (o *EcrPairRequest) SetCashierName(v string) {
	o.CashierName = &v
}

func (o EcrPairRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EcrPairRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pairingCode"] = o.PairingCode
	if !IsNil(o.CashierName) {
		toSerialize["cashierName"] = o.CashierName
	}
	return toSerialize, nil
}

func (o *EcrPairRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pairingCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEcrPairRequest := _EcrPairRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEcrPairRequest)

	if err != nil {
		return err
	}

	*o = EcrPairRequest(varEcrPairRequest)

	return err
}

type NullableEcrPairRequest struct {
	value *EcrPairRequest
	isSet bool
}

func (v NullableEcrPairRequest) Get() *EcrPairRequest {
	return v.value
}

func (v *NullableEcrPairRequest) Set(val *EcrPairRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEcrPairRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEcrPairRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEcrPairRequest(val *EcrPairRequest) *NullableEcrPairRequest {
	return &NullableEcrPairRequest{value: val, isSet: true}
}

func (v NullableEcrPairRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEcrPairRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
