/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the Transaction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Transaction{}

// Transaction struct for Transaction
type Transaction struct {
	Id                  *int32              `json:"id,omitempty"`
	Uuid                *string             `json:"uuid,omitempty"`
	ReferenceId         *string             `json:"referenceId,omitempty"`
	Time                *string             `json:"time,omitempty"`
	Status              *string             `json:"status,omitempty"`
	Lang                *string             `json:"lang,omitempty"`
	Psp                 *string             `json:"psp,omitempty"`
	Amount              *int32              `json:"amount,omitempty"`
	Contact             *TransactionContact `json:"contact,omitempty"`
	PageUuid            *string             `json:"pageUuid,omitempty"`
	Payment             *TransactionPayment `json:"payment,omitempty"`
	PayoutUuid          *string             `json:"payoutUuid,omitempty"`
	PspId               *int32              `json:"pspId,omitempty"`
	Mode                *string             `json:"mode,omitempty"`
	Invoice             *TransactionInvoice `json:"invoice,omitempty"`
	Refundable          *bool               `json:"refundable,omitempty"`
	PartiallyRefundable *bool               `json:"partiallyRefundable,omitempty"`
	VatRate             *string             `json:"vatRate,omitempty"`
}

// NewTransaction instantiates a new Transaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransaction() *Transaction {
	this := Transaction{}
	var id int32 = 0
	this.Id = &id
	var amount int32 = 0
	this.Amount = &amount
	var pspId int32 = 0
	this.PspId = &pspId
	var refundable bool = true
	this.Refundable = &refundable
	var partiallyRefundable bool = true
	this.PartiallyRefundable = &partiallyRefundable
	return &this
}

// NewTransactionWithDefaults instantiates a new Transaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionWithDefaults() *Transaction {
	this := Transaction{}
	var id int32 = 0
	this.Id = &id
	var amount int32 = 0
	this.Amount = &amount
	var pspId int32 = 0
	this.PspId = &pspId
	var refundable bool = true
	this.Refundable = &refundable
	var partiallyRefundable bool = true
	this.PartiallyRefundable = &partiallyRefundable
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Transaction) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Transaction) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *Transaction) SetId(v int32) {
	o.Id = &v
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *Transaction) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *Transaction) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *Transaction) SetUuid(v string) {
	o.Uuid = &v
}

// GetReferenceId returns the ReferenceId field value if set, zero value otherwise.
func (o *Transaction) GetReferenceId() string {
	if o == nil || IsNil(o.ReferenceId) {
		var ret string
		return ret
	}
	return *o.ReferenceId
}

// GetReferenceIdOk returns a tuple with the ReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetReferenceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ReferenceId) {
		return nil, false
	}
	return o.ReferenceId, true
}

// HasReferenceId returns a boolean if a field has been set.
func (o *Transaction) HasReferenceId() bool {
	if o != nil && !IsNil(o.ReferenceId) {
		return true
	}

	return false
}

// SetReferenceId gets a reference to the given string and assigns it to the ReferenceId field.
func (o *Transaction) SetReferenceId(v string) {
	o.ReferenceId = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *Transaction) GetTime() string {
	if o == nil || IsNil(o.Time) {
		var ret string
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetTimeOk() (*string, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *Transaction) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given string and assigns it to the Time field.
func (o *Transaction) SetTime(v string) {
	o.Time = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Transaction) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Transaction) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Transaction) SetStatus(v string) {
	o.Status = &v
}

// GetLang returns the Lang field value if set, zero value otherwise.
func (o *Transaction) GetLang() string {
	if o == nil || IsNil(o.Lang) {
		var ret string
		return ret
	}
	return *o.Lang
}

// GetLangOk returns a tuple with the Lang field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetLangOk() (*string, bool) {
	if o == nil || IsNil(o.Lang) {
		return nil, false
	}
	return o.Lang, true
}

// HasLang returns a boolean if a field has been set.
func (o *Transaction) HasLang() bool {
	if o != nil && !IsNil(o.Lang) {
		return true
	}

	return false
}

// SetLang gets a reference to the given string and assigns it to the Lang field.
func (o *Transaction) SetLang(v string) {
	o.Lang = &v
}

// GetPsp returns the Psp field value if set, zero value otherwise.
func (o *Transaction) GetPsp() string {
	if o == nil || IsNil(o.Psp) {
		var ret string
		return ret
	}
	return *o.Psp
}

// GetPspOk returns a tuple with the Psp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetPspOk() (*string, bool) {
	if o == nil || IsNil(o.Psp) {
		return nil, false
	}
	return o.Psp, true
}

// HasPsp returns a boolean if a field has been set.
func (o *Transaction) HasPsp() bool {
	if o != nil && !IsNil(o.Psp) {
		return true
	}

	return false
}

// SetPsp gets a reference to the given string and assigns it to the Psp field.
func (o *Transaction) SetPsp(v string) {
	o.Psp = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *Transaction) GetAmount() int32 {
	if o == nil || IsNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *Transaction) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *Transaction) SetAmount(v int32) {
	o.Amount = &v
}

// GetContact returns the Contact field value if set, zero value otherwise.
func (o *Transaction) GetContact() TransactionContact {
	if o == nil || IsNil(o.Contact) {
		var ret TransactionContact
		return ret
	}
	return *o.Contact
}

// GetContactOk returns a tuple with the Contact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetContactOk() (*TransactionContact, bool) {
	if o == nil || IsNil(o.Contact) {
		return nil, false
	}
	return o.Contact, true
}

// HasContact returns a boolean if a field has been set.
func (o *Transaction) HasContact() bool {
	if o != nil && !IsNil(o.Contact) {
		return true
	}

	return false
}

// SetContact gets a reference to the given TransactionContact and assigns it to the Contact field.
func (o *Transaction) SetContact(v TransactionContact) {
	o.Contact = &v
}

// GetPageUuid returns the PageUuid field value if set, zero value otherwise.
func (o *Transaction) GetPageUuid() string {
	if o == nil || IsNil(o.PageUuid) {
		var ret string
		return ret
	}
	return *o.PageUuid
}

// GetPageUuidOk returns a tuple with the PageUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetPageUuidOk() (*string, bool) {
	if o == nil || IsNil(o.PageUuid) {
		return nil, false
	}
	return o.PageUuid, true
}

// HasPageUuid returns a boolean if a field has been set.
func (o *Transaction) HasPageUuid() bool {
	if o != nil && !IsNil(o.PageUuid) {
		return true
	}

	return false
}

// SetPageUuid gets a reference to the given string and assigns it to the PageUuid field.
func (o *Transaction) SetPageUuid(v string) {
	o.PageUuid = &v
}

// GetPayment returns the Payment field value if set, zero value otherwise.
func (o *Transaction) GetPayment() TransactionPayment {
	if o == nil || IsNil(o.Payment) {
		var ret TransactionPayment
		return ret
	}
	return *o.Payment
}

// GetPaymentOk returns a tuple with the Payment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetPaymentOk() (*TransactionPayment, bool) {
	if o == nil || IsNil(o.Payment) {
		return nil, false
	}
	return o.Payment, true
}

// HasPayment returns a boolean if a field has been set.
func (o *Transaction) HasPayment() bool {
	if o != nil && !IsNil(o.Payment) {
		return true
	}

	return false
}

// SetPayment gets a reference to the given TransactionPayment and assigns it to the Payment field.
func (o *Transaction) SetPayment(v TransactionPayment) {
	o.Payment = &v
}

// GetPayoutUuid returns the PayoutUuid field value if set, zero value otherwise.
func (o *Transaction) GetPayoutUuid() string {
	if o == nil || IsNil(o.PayoutUuid) {
		var ret string
		return ret
	}
	return *o.PayoutUuid
}

// GetPayoutUuidOk returns a tuple with the PayoutUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetPayoutUuidOk() (*string, bool) {
	if o == nil || IsNil(o.PayoutUuid) {
		return nil, false
	}
	return o.PayoutUuid, true
}

// HasPayoutUuid returns a boolean if a field has been set.
func (o *Transaction) HasPayoutUuid() bool {
	if o != nil && !IsNil(o.PayoutUuid) {
		return true
	}

	return false
}

// SetPayoutUuid gets a reference to the given string and assigns it to the PayoutUuid field.
func (o *Transaction) SetPayoutUuid(v string) {
	o.PayoutUuid = &v
}

// GetPspId returns the PspId field value if set, zero value otherwise.
func (o *Transaction) GetPspId() int32 {
	if o == nil || IsNil(o.PspId) {
		var ret int32
		return ret
	}
	return *o.PspId
}

// GetPspIdOk returns a tuple with the PspId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetPspIdOk() (*int32, bool) {
	if o == nil || IsNil(o.PspId) {
		return nil, false
	}
	return o.PspId, true
}

// HasPspId returns a boolean if a field has been set.
func (o *Transaction) HasPspId() bool {
	if o != nil && !IsNil(o.PspId) {
		return true
	}

	return false
}

// SetPspId gets a reference to the given int32 and assigns it to the PspId field.
func (o *Transaction) SetPspId(v int32) {
	o.PspId = &v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *Transaction) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *Transaction) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *Transaction) SetMode(v string) {
	o.Mode = &v
}

// GetInvoice returns the Invoice field value if set, zero value otherwise.
func (o *Transaction) GetInvoice() TransactionInvoice {
	if o == nil || IsNil(o.Invoice) {
		var ret TransactionInvoice
		return ret
	}
	return *o.Invoice
}

// GetInvoiceOk returns a tuple with the Invoice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetInvoiceOk() (*TransactionInvoice, bool) {
	if o == nil || IsNil(o.Invoice) {
		return nil, false
	}
	return o.Invoice, true
}

// HasInvoice returns a boolean if a field has been set.
func (o *Transaction) HasInvoice() bool {
	if o != nil && !IsNil(o.Invoice) {
		return true
	}

	return false
}

// SetInvoice gets a reference to the given TransactionInvoice and assigns it to the Invoice field.
func (o *Transaction) SetInvoice(v TransactionInvoice) {
	o.Invoice = &v
}

// GetRefundable returns the Refundable field value if set, zero value otherwise.
func (o *Transaction) GetRefundable() bool {
	if o == nil || IsNil(o.Refundable) {
		var ret bool
		return ret
	}
	return *o.Refundable
}

// GetRefundableOk returns a tuple with the Refundable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetRefundableOk() (*bool, bool) {
	if o == nil || IsNil(o.Refundable) {
		return nil, false
	}
	return o.Refundable, true
}

// HasRefundable returns a boolean if a field has been set.
func (o *Transaction) HasRefundable() bool {
	if o != nil && !IsNil(o.Refundable) {
		return true
	}

	return false
}

// SetRefundable gets a reference to the given bool and assigns it to the Refundable field.
func (o *Transaction) SetRefundable(v bool) {
	o.Refundable = &v
}

// GetPartiallyRefundable returns the PartiallyRefundable field value if set, zero value otherwise.
func (o *Transaction) GetPartiallyRefundable() bool {
	if o == nil || IsNil(o.PartiallyRefundable) {
		var ret bool
		return ret
	}
	return *o.PartiallyRefundable
}

// GetPartiallyRefundableOk returns a tuple with the PartiallyRefundable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetPartiallyRefundableOk() (*bool, bool) {
	if o == nil || IsNil(o.PartiallyRefundable) {
		return nil, false
	}
	return o.PartiallyRefundable, true
}

// HasPartiallyRefundable returns a boolean if a field has been set.
func (o *Transaction) HasPartiallyRefundable() bool {
	if o != nil && !IsNil(o.PartiallyRefundable) {
		return true
	}

	return false
}

// SetPartiallyRefundable gets a reference to the given bool and assigns it to the PartiallyRefundable field.
func (o *Transaction) SetPartiallyRefundable(v bool) {
	o.PartiallyRefundable = &v
}

// GetVatRate returns the VatRate field value if set, zero value otherwise.
func (o *Transaction) GetVatRate() string {
	if o == nil || IsNil(o.VatRate) {
		var ret string
		return ret
	}
	return *o.VatRate
}

// GetVatRateOk returns a tuple with the VatRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetVatRateOk() (*string, bool) {
	if o == nil || IsNil(o.VatRate) {
		return nil, false
	}
	return o.VatRate, true
}

// HasVatRate returns a boolean if a field has been set.
func (o *Transaction) HasVatRate() bool {
	if o != nil && !IsNil(o.VatRate) {
		return true
	}

	return false
}

// SetVatRate gets a reference to the given string and assigns it to the VatRate field.
func (o *Transaction) SetVatRate(v string) {
	o.VatRate = &v
}

func (o Transaction) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Transaction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	if !IsNil(o.ReferenceId) {
		toSerialize["referenceId"] = o.ReferenceId
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Lang) {
		toSerialize["lang"] = o.Lang
	}
	if !IsNil(o.Psp) {
		toSerialize["psp"] = o.Psp
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Contact) {
		toSerialize["contact"] = o.Contact
	}
	if !IsNil(o.PageUuid) {
		toSerialize["pageUuid"] = o.PageUuid
	}
	if !IsNil(o.Payment) {
		toSerialize["payment"] = o.Payment
	}
	if !IsNil(o.PayoutUuid) {
		toSerialize["payoutUuid"] = o.PayoutUuid
	}
	if !IsNil(o.PspId) {
		toSerialize["pspId"] = o.PspId
	}
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	if !IsNil(o.Invoice) {
		toSerialize["invoice"] = o.Invoice
	}
	if !IsNil(o.Refundable) {
		toSerialize["refundable"] = o.Refundable
	}
	if !IsNil(o.PartiallyRefundable) {
		toSerialize["partiallyRefundable"] = o.PartiallyRefundable
	}
	if !IsNil(o.VatRate) {
		toSerialize["vatRate"] = o.VatRate
	}
	return toSerialize, nil
}

type NullableTransaction struct {
	value *Transaction
	isSet bool
}

func (v NullableTransaction) Get() *Transaction {
	return v.value
}

func (v *NullableTransaction) Set(val *Transaction) {
	v.value = val
	v.isSet = true
}

func (v NullableTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullableTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransaction(val *Transaction) *NullableTransaction {
	return &NullableTransaction{value: val, isSet: true}
}

func (v NullableTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
