/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the GatewayFieldsTitle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayFieldsTitle{}

// GatewayFieldsTitle struct for GatewayFieldsTitle
type GatewayFieldsTitle struct {
	Active    *bool `json:"active,omitempty"`
	Mandatory *bool `json:"mandatory,omitempty"`
}

// NewGatewayFieldsTitle instantiates a new GatewayFieldsTitle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayFieldsTitle() *GatewayFieldsTitle {
	this := GatewayFieldsTitle{}
	var active bool = true
	this.Active = &active
	var mandatory bool = true
	this.Mandatory = &mandatory
	return &this
}

// NewGatewayFieldsTitleWithDefaults instantiates a new GatewayFieldsTitle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayFieldsTitleWithDefaults() *GatewayFieldsTitle {
	this := GatewayFieldsTitle{}
	var active bool = true
	this.Active = &active
	var mandatory bool = true
	this.Mandatory = &mandatory
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *GatewayFieldsTitle) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayFieldsTitle) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *GatewayFieldsTitle) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *GatewayFieldsTitle) SetActive(v bool) {
	o.Active = &v
}

// GetMandatory returns the Mandatory field value if set, zero value otherwise.
func (o *GatewayFieldsTitle) GetMandatory() bool {
	if o == nil || IsNil(o.Mandatory) {
		var ret bool
		return ret
	}
	return *o.Mandatory
}

// GetMandatoryOk returns a tuple with the Mandatory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayFieldsTitle) GetMandatoryOk() (*bool, bool) {
	if o == nil || IsNil(o.Mandatory) {
		return nil, false
	}
	return o.Mandatory, true
}

// HasMandatory returns a boolean if a field has been set.
func (o *GatewayFieldsTitle) HasMandatory() bool {
	if o != nil && !IsNil(o.Mandatory) {
		return true
	}

	return false
}

// SetMandatory gets a reference to the given bool and assigns it to the Mandatory field.
func (o *GatewayFieldsTitle) SetMandatory(v bool) {
	o.Mandatory = &v
}

func (o GatewayFieldsTitle) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayFieldsTitle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Mandatory) {
		toSerialize["mandatory"] = o.Mandatory
	}
	return toSerialize, nil
}

type NullableGatewayFieldsTitle struct {
	value *GatewayFieldsTitle
	isSet bool
}

func (v NullableGatewayFieldsTitle) Get() *GatewayFieldsTitle {
	return v.value
}

func (v *NullableGatewayFieldsTitle) Set(val *GatewayFieldsTitle) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayFieldsTitle) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayFieldsTitle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayFieldsTitle(val *GatewayFieldsTitle) *NullableGatewayFieldsTitle {
	return &NullableGatewayFieldsTitle{value: val, isSet: true}
}

func (v NullableGatewayFieldsTitle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayFieldsTitle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
