/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the TransactionInvoice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionInvoice{}

// TransactionInvoice struct for TransactionInvoice
type TransactionInvoice struct {
	CurrencyAlpha3 *string                           `json:"currencyAlpha3,omitempty"`
	Products       []TransactionInvoiceProductsInner `json:"products,omitempty"`
	Discount       *TransactionInvoiceDiscount       `json:"discount,omitempty"`
	ShippingAmount *int32                            `json:"shippingAmount,omitempty"`
	TotalAmount    *int32                            `json:"totalAmount,omitempty"`
	CustomFields   *TransactionInvoiceCustomFields   `json:"customFields,omitempty"`
}

// NewTransactionInvoice instantiates a new TransactionInvoice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionInvoice() *TransactionInvoice {
	this := TransactionInvoice{}
	var shippingAmount int32 = 0
	this.ShippingAmount = &shippingAmount
	var totalAmount int32 = 0
	this.TotalAmount = &totalAmount
	return &this
}

// NewTransactionInvoiceWithDefaults instantiates a new TransactionInvoice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionInvoiceWithDefaults() *TransactionInvoice {
	this := TransactionInvoice{}
	var shippingAmount int32 = 0
	this.ShippingAmount = &shippingAmount
	var totalAmount int32 = 0
	this.TotalAmount = &totalAmount
	return &this
}

// GetCurrencyAlpha3 returns the CurrencyAlpha3 field value if set, zero value otherwise.
func (o *TransactionInvoice) GetCurrencyAlpha3() string {
	if o == nil || IsNil(o.CurrencyAlpha3) {
		var ret string
		return ret
	}
	return *o.CurrencyAlpha3
}

// GetCurrencyAlpha3Ok returns a tuple with the CurrencyAlpha3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInvoice) GetCurrencyAlpha3Ok() (*string, bool) {
	if o == nil || IsNil(o.CurrencyAlpha3) {
		return nil, false
	}
	return o.CurrencyAlpha3, true
}

// HasCurrencyAlpha3 returns a boolean if a field has been set.
func (o *TransactionInvoice) HasCurrencyAlpha3() bool {
	if o != nil && !IsNil(o.CurrencyAlpha3) {
		return true
	}

	return false
}

// SetCurrencyAlpha3 gets a reference to the given string and assigns it to the CurrencyAlpha3 field.
func (o *TransactionInvoice) SetCurrencyAlpha3(v string) {
	o.CurrencyAlpha3 = &v
}

// GetProducts returns the Products field value if set, zero value otherwise.
func (o *TransactionInvoice) GetProducts() []TransactionInvoiceProductsInner {
	if o == nil || IsNil(o.Products) {
		var ret []TransactionInvoiceProductsInner
		return ret
	}
	return o.Products
}

// GetProductsOk returns a tuple with the Products field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInvoice) GetProductsOk() ([]TransactionInvoiceProductsInner, bool) {
	if o == nil || IsNil(o.Products) {
		return nil, false
	}
	return o.Products, true
}

// HasProducts returns a boolean if a field has been set.
func (o *TransactionInvoice) HasProducts() bool {
	if o != nil && !IsNil(o.Products) {
		return true
	}

	return false
}

// SetProducts gets a reference to the given []TransactionInvoiceProductsInner and assigns it to the Products field.
func (o *TransactionInvoice) SetProducts(v []TransactionInvoiceProductsInner) {
	o.Products = v
}

// GetDiscount returns the Discount field value if set, zero value otherwise.
func (o *TransactionInvoice) GetDiscount() TransactionInvoiceDiscount {
	if o == nil || IsNil(o.Discount) {
		var ret TransactionInvoiceDiscount
		return ret
	}
	return *o.Discount
}

// GetDiscountOk returns a tuple with the Discount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInvoice) GetDiscountOk() (*TransactionInvoiceDiscount, bool) {
	if o == nil || IsNil(o.Discount) {
		return nil, false
	}
	return o.Discount, true
}

// HasDiscount returns a boolean if a field has been set.
func (o *TransactionInvoice) HasDiscount() bool {
	if o != nil && !IsNil(o.Discount) {
		return true
	}

	return false
}

// SetDiscount gets a reference to the given TransactionInvoiceDiscount and assigns it to the Discount field.
func (o *TransactionInvoice) SetDiscount(v TransactionInvoiceDiscount) {
	o.Discount = &v
}

// GetShippingAmount returns the ShippingAmount field value if set, zero value otherwise.
func (o *TransactionInvoice) GetShippingAmount() int32 {
	if o == nil || IsNil(o.ShippingAmount) {
		var ret int32
		return ret
	}
	return *o.ShippingAmount
}

// GetShippingAmountOk returns a tuple with the ShippingAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInvoice) GetShippingAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.ShippingAmount) {
		return nil, false
	}
	return o.ShippingAmount, true
}

// HasShippingAmount returns a boolean if a field has been set.
func (o *TransactionInvoice) HasShippingAmount() bool {
	if o != nil && !IsNil(o.ShippingAmount) {
		return true
	}

	return false
}

// SetShippingAmount gets a reference to the given int32 and assigns it to the ShippingAmount field.
func (o *TransactionInvoice) SetShippingAmount(v int32) {
	o.ShippingAmount = &v
}

// GetTotalAmount returns the TotalAmount field value if set, zero value otherwise.
func (o *TransactionInvoice) GetTotalAmount() int32 {
	if o == nil || IsNil(o.TotalAmount) {
		var ret int32
		return ret
	}
	return *o.TotalAmount
}

// GetTotalAmountOk returns a tuple with the TotalAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInvoice) GetTotalAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalAmount) {
		return nil, false
	}
	return o.TotalAmount, true
}

// HasTotalAmount returns a boolean if a field has been set.
func (o *TransactionInvoice) HasTotalAmount() bool {
	if o != nil && !IsNil(o.TotalAmount) {
		return true
	}

	return false
}

// SetTotalAmount gets a reference to the given int32 and assigns it to the TotalAmount field.
func (o *TransactionInvoice) SetTotalAmount(v int32) {
	o.TotalAmount = &v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *TransactionInvoice) GetCustomFields() TransactionInvoiceCustomFields {
	if o == nil || IsNil(o.CustomFields) {
		var ret TransactionInvoiceCustomFields
		return ret
	}
	return *o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInvoice) GetCustomFieldsOk() (*TransactionInvoiceCustomFields, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return nil, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *TransactionInvoice) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given TransactionInvoiceCustomFields and assigns it to the CustomFields field.
func (o *TransactionInvoice) SetCustomFields(v TransactionInvoiceCustomFields) {
	o.CustomFields = &v
}

func (o TransactionInvoice) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionInvoice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CurrencyAlpha3) {
		toSerialize["currencyAlpha3"] = o.CurrencyAlpha3
	}
	if !IsNil(o.Products) {
		toSerialize["products"] = o.Products
	}
	if !IsNil(o.Discount) {
		toSerialize["discount"] = o.Discount
	}
	if !IsNil(o.ShippingAmount) {
		toSerialize["shippingAmount"] = o.ShippingAmount
	}
	if !IsNil(o.TotalAmount) {
		toSerialize["totalAmount"] = o.TotalAmount
	}
	if !IsNil(o.CustomFields) {
		toSerialize["customFields"] = o.CustomFields
	}
	return toSerialize, nil
}

type NullableTransactionInvoice struct {
	value *TransactionInvoice
	isSet bool
}

func (v NullableTransactionInvoice) Get() *TransactionInvoice {
	return v.value
}

func (v *NullableTransactionInvoice) Set(val *TransactionInvoice) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionInvoice) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionInvoice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionInvoice(val *TransactionInvoice) *NullableTransactionInvoice {
	return &NullableTransactionInvoice{value: val, isSet: true}
}

func (v NullableTransactionInvoice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionInvoice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
