/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GatewayCreateRequestBasketInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayCreateRequestBasketInner{}

// GatewayCreateRequestBasketInner struct for GatewayCreateRequestBasketInner
type GatewayCreateRequestBasketInner struct {
	// Name of item
	Name []string `json:"name"`
	// Description of item
	Description []string `json:"description,omitempty"`
	// Quantity of item
	Quantity int32 `json:"quantity"`
	// Amount in cents
	Amount int32 `json:"amount"`
	// VAT rate of item (overrides vatRate of Gateway, can be 0)
	VatRate *float32 `json:"vatRate,omitempty"`
	// Product stock keeping unit
	Sku *string `json:"sku,omitempty"`
}

type _GatewayCreateRequestBasketInner GatewayCreateRequestBasketInner

// NewGatewayCreateRequestBasketInner instantiates a new GatewayCreateRequestBasketInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayCreateRequestBasketInner(name []string, quantity int32, amount int32) *GatewayCreateRequestBasketInner {
	this := GatewayCreateRequestBasketInner{}
	this.Name = name
	this.Quantity = quantity
	this.Amount = amount
	return &this
}

// NewGatewayCreateRequestBasketInnerWithDefaults instantiates a new GatewayCreateRequestBasketInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayCreateRequestBasketInnerWithDefaults() *GatewayCreateRequestBasketInner {
	this := GatewayCreateRequestBasketInner{}
	return &this
}

// GetName returns the Name field value
func (o *GatewayCreateRequestBasketInner) GetName() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequestBasketInner) GetNameOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name, true
}

// SetName sets field value
func (o *GatewayCreateRequestBasketInner) SetName(v []string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GatewayCreateRequestBasketInner) GetDescription() []string {
	if o == nil || IsNil(o.Description) {
		var ret []string
		return ret
	}
	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequestBasketInner) GetDescriptionOk() ([]string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GatewayCreateRequestBasketInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given []string and assigns it to the Description field.
func (o *GatewayCreateRequestBasketInner) SetDescription(v []string) {
	o.Description = v
}

// GetQuantity returns the Quantity field value
func (o *GatewayCreateRequestBasketInner) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequestBasketInner) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *GatewayCreateRequestBasketInner) SetQuantity(v int32) {
	o.Quantity = v
}

// GetAmount returns the Amount field value
func (o *GatewayCreateRequestBasketInner) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequestBasketInner) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *GatewayCreateRequestBasketInner) SetAmount(v int32) {
	o.Amount = v
}

// GetVatRate returns the VatRate field value if set, zero value otherwise.
func (o *GatewayCreateRequestBasketInner) GetVatRate() float32 {
	if o == nil || IsNil(o.VatRate) {
		var ret float32
		return ret
	}
	return *o.VatRate
}

// GetVatRateOk returns a tuple with the VatRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequestBasketInner) GetVatRateOk() (*float32, bool) {
	if o == nil || IsNil(o.VatRate) {
		return nil, false
	}
	return o.VatRate, true
}

// HasVatRate returns a boolean if a field has been set.
func (o *GatewayCreateRequestBasketInner) HasVatRate() bool {
	if o != nil && !IsNil(o.VatRate) {
		return true
	}

	return false
}

// SetVatRate gets a reference to the given float32 and assigns it to the VatRate field.
func (o *GatewayCreateRequestBasketInner) SetVatRate(v float32) {
	o.VatRate = &v
}

// GetSku returns the Sku field value if set, zero value otherwise.
func (o *GatewayCreateRequestBasketInner) GetSku() string {
	if o == nil || IsNil(o.Sku) {
		var ret string
		return ret
	}
	return *o.Sku
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequestBasketInner) GetSkuOk() (*string, bool) {
	if o == nil || IsNil(o.Sku) {
		return nil, false
	}
	return o.Sku, true
}

// HasSku returns a boolean if a field has been set.
func (o *GatewayCreateRequestBasketInner) HasSku() bool {
	if o != nil && !IsNil(o.Sku) {
		return true
	}

	return false
}

// SetSku gets a reference to the given string and assigns it to the Sku field.
func (o *GatewayCreateRequestBasketInner) SetSku(v string) {
	o.Sku = &v
}

func (o GatewayCreateRequestBasketInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayCreateRequestBasketInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["quantity"] = o.Quantity
	toSerialize["amount"] = o.Amount
	if !IsNil(o.VatRate) {
		toSerialize["vatRate"] = o.VatRate
	}
	if !IsNil(o.Sku) {
		toSerialize["sku"] = o.Sku
	}
	return toSerialize, nil
}

func (o *GatewayCreateRequestBasketInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"quantity",
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGatewayCreateRequestBasketInner := _GatewayCreateRequestBasketInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGatewayCreateRequestBasketInner)

	if err != nil {
		return err
	}

	*o = GatewayCreateRequestBasketInner(varGatewayCreateRequestBasketInner)

	return err
}

type NullableGatewayCreateRequestBasketInner struct {
	value *GatewayCreateRequestBasketInner
	isSet bool
}

func (v NullableGatewayCreateRequestBasketInner) Get() *GatewayCreateRequestBasketInner {
	return v.value
}

func (v *NullableGatewayCreateRequestBasketInner) Set(val *GatewayCreateRequestBasketInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayCreateRequestBasketInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayCreateRequestBasketInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayCreateRequestBasketInner(val *GatewayCreateRequestBasketInner) *NullableGatewayCreateRequestBasketInner {
	return &NullableGatewayCreateRequestBasketInner{value: val, isSet: true}
}

func (v NullableGatewayCreateRequestBasketInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayCreateRequestBasketInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
