/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the PayoutList200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PayoutList200Response{}

// PayoutList200Response struct for PayoutList200Response
type PayoutList200Response struct {
	Status *string  `json:"status,omitempty"`
	Data   []Payout `json:"data,omitempty"`
}

// NewPayoutList200Response instantiates a new PayoutList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPayoutList200Response() *PayoutList200Response {
	this := PayoutList200Response{}
	return &this
}

// NewPayoutList200ResponseWithDefaults instantiates a new PayoutList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPayoutList200ResponseWithDefaults() *PayoutList200Response {
	this := PayoutList200Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PayoutList200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayoutList200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PayoutList200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PayoutList200Response) SetStatus(v string) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PayoutList200Response) GetData() []Payout {
	if o == nil || IsNil(o.Data) {
		var ret []Payout
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayoutList200Response) GetDataOk() ([]Payout, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PayoutList200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Payout and assigns it to the Data field.
func (o *PayoutList200Response) SetData(v []Payout) {
	o.Data = v
}

func (o PayoutList200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PayoutList200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullablePayoutList200Response struct {
	value *PayoutList200Response
	isSet bool
}

func (v NullablePayoutList200Response) Get() *PayoutList200Response {
	return v.value
}

func (v *NullablePayoutList200Response) Set(val *PayoutList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePayoutList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePayoutList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayoutList200Response(val *PayoutList200Response) *NullablePayoutList200Response {
	return &NullablePayoutList200Response{value: val, isSet: true}
}

func (v NullablePayoutList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayoutList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
