/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the InvoiceDeletion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoiceDeletion{}

// InvoiceDeletion struct for InvoiceDeletion
type InvoiceDeletion struct {
	Deleted *bool   `json:"deleted,omitempty"`
	Uuid    *string `json:"uuid,omitempty"`
}

// NewInvoiceDeletion instantiates a new InvoiceDeletion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceDeletion() *InvoiceDeletion {
	this := InvoiceDeletion{}
	var deleted bool = true
	this.Deleted = &deleted
	return &this
}

// NewInvoiceDeletionWithDefaults instantiates a new InvoiceDeletion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceDeletionWithDefaults() *InvoiceDeletion {
	this := InvoiceDeletion{}
	var deleted bool = true
	this.Deleted = &deleted
	return &this
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *InvoiceDeletion) GetDeleted() bool {
	if o == nil || IsNil(o.Deleted) {
		var ret bool
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceDeletion) GetDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *InvoiceDeletion) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given bool and assigns it to the Deleted field.
func (o *InvoiceDeletion) SetDeleted(v bool) {
	o.Deleted = &v
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *InvoiceDeletion) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceDeletion) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *InvoiceDeletion) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *InvoiceDeletion) SetUuid(v string) {
	o.Uuid = &v
}

func (o InvoiceDeletion) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoiceDeletion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	return toSerialize, nil
}

type NullableInvoiceDeletion struct {
	value *InvoiceDeletion
	isSet bool
}

func (v NullableInvoiceDeletion) Get() *InvoiceDeletion {
	return v.value
}

func (v *NullableInvoiceDeletion) Set(val *InvoiceDeletion) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceDeletion) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceDeletion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceDeletion(val *InvoiceDeletion) *NullableInvoiceDeletion {
	return &NullableInvoiceDeletion{value: val, isSet: true}
}

func (v NullableInvoiceDeletion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceDeletion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
