/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the BillUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillUpdateRequest{}

// BillUpdateRequest struct for BillUpdateRequest
type BillUpdateRequest struct {
	Date *string `json:"date,omitempty"`
	// The language ISO code by ISO 639-1.
	Language *string `json:"language,omitempty"`
	// Currency code (ISO 4217)
	Currency      *string                               `json:"currency,omitempty"`
	DueAfterDays  *int32                                `json:"dueAfterDays,omitempty"`
	Recipient     *BillCreateRequestRecipient           `json:"recipient,omitempty"`
	ServicePeriod *BillCreateRequestServicePeriod       `json:"servicePeriod,omitempty"`
	Discount      *BillCreateRequestDiscount            `json:"discount,omitempty"`
	CashDiscounts []BillCreateRequestCashDiscountsInner `json:"cashDiscounts,omitempty"`
	// Amount in the smallest unit of the currency.
	ShippingCost *int32 `json:"shippingCost,omitempty"`
	// Amount in the smallest unit of the currency.
	ApplicationFee  *int32                              `json:"applicationFee,omitempty"`
	Note            *string                             `json:"note,omitempty"`
	Terms           *string                             `json:"terms,omitempty"`
	Positions       []BillCreateRequestPositionsInner   `json:"positions,omitempty"`
	Attachments     []BillCreateRequestAttachmentsInner `json:"attachments,omitempty"`
	BankInformation *BillCreateRequestBankInformation   `json:"bankInformation,omitempty"`
	// This payout descriptor is added to the payout statement (Only for Payrexx Swiss Collecting payments and single transaction payouts). Max. 80 chars.
	PayoutDescriptor *string                           `json:"payoutDescriptor,omitempty"`
	Psp              []int32                           `json:"psp,omitempty"`
	Pm               []string                          `json:"pm,omitempty"`
	Reminders        []BillCreateRequestRemindersInner `json:"reminders,omitempty"`
	Reference        *string                           `json:"reference,omitempty"`
	Design           *string                           `json:"design,omitempty"`
	// Whether to send the invoice.
	Send *bool `json:"send,omitempty"`
	// Send invoice to additional recipients. Pass email addresses as Strings.
	AdditionalRecipients []string `json:"additionalRecipients,omitempty"`
	// Whether to complete the invoice.
	Complete *bool `json:"complete,omitempty"`
}

// NewBillUpdateRequest instantiates a new BillUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillUpdateRequest() *BillUpdateRequest {
	this := BillUpdateRequest{}
	var send bool = false
	this.Send = &send
	var complete bool = false
	this.Complete = &complete
	return &this
}

// NewBillUpdateRequestWithDefaults instantiates a new BillUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillUpdateRequestWithDefaults() *BillUpdateRequest {
	this := BillUpdateRequest{}
	var send bool = false
	this.Send = &send
	var complete bool = false
	this.Complete = &complete
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *BillUpdateRequest) SetDate(v string) {
	o.Date = &v
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetLanguage() string {
	if o == nil || IsNil(o.Language) {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.Language) {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasLanguage() bool {
	if o != nil && !IsNil(o.Language) {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *BillUpdateRequest) SetLanguage(v string) {
	o.Language = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *BillUpdateRequest) SetCurrency(v string) {
	o.Currency = &v
}

// GetDueAfterDays returns the DueAfterDays field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetDueAfterDays() int32 {
	if o == nil || IsNil(o.DueAfterDays) {
		var ret int32
		return ret
	}
	return *o.DueAfterDays
}

// GetDueAfterDaysOk returns a tuple with the DueAfterDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetDueAfterDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.DueAfterDays) {
		return nil, false
	}
	return o.DueAfterDays, true
}

// HasDueAfterDays returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasDueAfterDays() bool {
	if o != nil && !IsNil(o.DueAfterDays) {
		return true
	}

	return false
}

// SetDueAfterDays gets a reference to the given int32 and assigns it to the DueAfterDays field.
func (o *BillUpdateRequest) SetDueAfterDays(v int32) {
	o.DueAfterDays = &v
}

// GetRecipient returns the Recipient field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetRecipient() BillCreateRequestRecipient {
	if o == nil || IsNil(o.Recipient) {
		var ret BillCreateRequestRecipient
		return ret
	}
	return *o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetRecipientOk() (*BillCreateRequestRecipient, bool) {
	if o == nil || IsNil(o.Recipient) {
		return nil, false
	}
	return o.Recipient, true
}

// HasRecipient returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasRecipient() bool {
	if o != nil && !IsNil(o.Recipient) {
		return true
	}

	return false
}

// SetRecipient gets a reference to the given BillCreateRequestRecipient and assigns it to the Recipient field.
func (o *BillUpdateRequest) SetRecipient(v BillCreateRequestRecipient) {
	o.Recipient = &v
}

// GetServicePeriod returns the ServicePeriod field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetServicePeriod() BillCreateRequestServicePeriod {
	if o == nil || IsNil(o.ServicePeriod) {
		var ret BillCreateRequestServicePeriod
		return ret
	}
	return *o.ServicePeriod
}

// GetServicePeriodOk returns a tuple with the ServicePeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetServicePeriodOk() (*BillCreateRequestServicePeriod, bool) {
	if o == nil || IsNil(o.ServicePeriod) {
		return nil, false
	}
	return o.ServicePeriod, true
}

// HasServicePeriod returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasServicePeriod() bool {
	if o != nil && !IsNil(o.ServicePeriod) {
		return true
	}

	return false
}

// SetServicePeriod gets a reference to the given BillCreateRequestServicePeriod and assigns it to the ServicePeriod field.
func (o *BillUpdateRequest) SetServicePeriod(v BillCreateRequestServicePeriod) {
	o.ServicePeriod = &v
}

// GetDiscount returns the Discount field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetDiscount() BillCreateRequestDiscount {
	if o == nil || IsNil(o.Discount) {
		var ret BillCreateRequestDiscount
		return ret
	}
	return *o.Discount
}

// GetDiscountOk returns a tuple with the Discount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetDiscountOk() (*BillCreateRequestDiscount, bool) {
	if o == nil || IsNil(o.Discount) {
		return nil, false
	}
	return o.Discount, true
}

// HasDiscount returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasDiscount() bool {
	if o != nil && !IsNil(o.Discount) {
		return true
	}

	return false
}

// SetDiscount gets a reference to the given BillCreateRequestDiscount and assigns it to the Discount field.
func (o *BillUpdateRequest) SetDiscount(v BillCreateRequestDiscount) {
	o.Discount = &v
}

// GetCashDiscounts returns the CashDiscounts field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetCashDiscounts() []BillCreateRequestCashDiscountsInner {
	if o == nil || IsNil(o.CashDiscounts) {
		var ret []BillCreateRequestCashDiscountsInner
		return ret
	}
	return o.CashDiscounts
}

// GetCashDiscountsOk returns a tuple with the CashDiscounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetCashDiscountsOk() ([]BillCreateRequestCashDiscountsInner, bool) {
	if o == nil || IsNil(o.CashDiscounts) {
		return nil, false
	}
	return o.CashDiscounts, true
}

// HasCashDiscounts returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasCashDiscounts() bool {
	if o != nil && !IsNil(o.CashDiscounts) {
		return true
	}

	return false
}

// SetCashDiscounts gets a reference to the given []BillCreateRequestCashDiscountsInner and assigns it to the CashDiscounts field.
func (o *BillUpdateRequest) SetCashDiscounts(v []BillCreateRequestCashDiscountsInner) {
	o.CashDiscounts = v
}

// GetShippingCost returns the ShippingCost field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetShippingCost() int32 {
	if o == nil || IsNil(o.ShippingCost) {
		var ret int32
		return ret
	}
	return *o.ShippingCost
}

// GetShippingCostOk returns a tuple with the ShippingCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetShippingCostOk() (*int32, bool) {
	if o == nil || IsNil(o.ShippingCost) {
		return nil, false
	}
	return o.ShippingCost, true
}

// HasShippingCost returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasShippingCost() bool {
	if o != nil && !IsNil(o.ShippingCost) {
		return true
	}

	return false
}

// SetShippingCost gets a reference to the given int32 and assigns it to the ShippingCost field.
func (o *BillUpdateRequest) SetShippingCost(v int32) {
	o.ShippingCost = &v
}

// GetApplicationFee returns the ApplicationFee field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetApplicationFee() int32 {
	if o == nil || IsNil(o.ApplicationFee) {
		var ret int32
		return ret
	}
	return *o.ApplicationFee
}

// GetApplicationFeeOk returns a tuple with the ApplicationFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetApplicationFeeOk() (*int32, bool) {
	if o == nil || IsNil(o.ApplicationFee) {
		return nil, false
	}
	return o.ApplicationFee, true
}

// HasApplicationFee returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasApplicationFee() bool {
	if o != nil && !IsNil(o.ApplicationFee) {
		return true
	}

	return false
}

// SetApplicationFee gets a reference to the given int32 and assigns it to the ApplicationFee field.
func (o *BillUpdateRequest) SetApplicationFee(v int32) {
	o.ApplicationFee = &v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasNote() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *BillUpdateRequest) SetNote(v string) {
	o.Note = &v
}

// GetTerms returns the Terms field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetTerms() string {
	if o == nil || IsNil(o.Terms) {
		var ret string
		return ret
	}
	return *o.Terms
}

// GetTermsOk returns a tuple with the Terms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetTermsOk() (*string, bool) {
	if o == nil || IsNil(o.Terms) {
		return nil, false
	}
	return o.Terms, true
}

// HasTerms returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasTerms() bool {
	if o != nil && !IsNil(o.Terms) {
		return true
	}

	return false
}

// SetTerms gets a reference to the given string and assigns it to the Terms field.
func (o *BillUpdateRequest) SetTerms(v string) {
	o.Terms = &v
}

// GetPositions returns the Positions field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetPositions() []BillCreateRequestPositionsInner {
	if o == nil || IsNil(o.Positions) {
		var ret []BillCreateRequestPositionsInner
		return ret
	}
	return o.Positions
}

// GetPositionsOk returns a tuple with the Positions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetPositionsOk() ([]BillCreateRequestPositionsInner, bool) {
	if o == nil || IsNil(o.Positions) {
		return nil, false
	}
	return o.Positions, true
}

// HasPositions returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasPositions() bool {
	if o != nil && !IsNil(o.Positions) {
		return true
	}

	return false
}

// SetPositions gets a reference to the given []BillCreateRequestPositionsInner and assigns it to the Positions field.
func (o *BillUpdateRequest) SetPositions(v []BillCreateRequestPositionsInner) {
	o.Positions = v
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetAttachments() []BillCreateRequestAttachmentsInner {
	if o == nil || IsNil(o.Attachments) {
		var ret []BillCreateRequestAttachmentsInner
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetAttachmentsOk() ([]BillCreateRequestAttachmentsInner, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []BillCreateRequestAttachmentsInner and assigns it to the Attachments field.
func (o *BillUpdateRequest) SetAttachments(v []BillCreateRequestAttachmentsInner) {
	o.Attachments = v
}

// GetBankInformation returns the BankInformation field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetBankInformation() BillCreateRequestBankInformation {
	if o == nil || IsNil(o.BankInformation) {
		var ret BillCreateRequestBankInformation
		return ret
	}
	return *o.BankInformation
}

// GetBankInformationOk returns a tuple with the BankInformation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetBankInformationOk() (*BillCreateRequestBankInformation, bool) {
	if o == nil || IsNil(o.BankInformation) {
		return nil, false
	}
	return o.BankInformation, true
}

// HasBankInformation returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasBankInformation() bool {
	if o != nil && !IsNil(o.BankInformation) {
		return true
	}

	return false
}

// SetBankInformation gets a reference to the given BillCreateRequestBankInformation and assigns it to the BankInformation field.
func (o *BillUpdateRequest) SetBankInformation(v BillCreateRequestBankInformation) {
	o.BankInformation = &v
}

// GetPayoutDescriptor returns the PayoutDescriptor field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetPayoutDescriptor() string {
	if o == nil || IsNil(o.PayoutDescriptor) {
		var ret string
		return ret
	}
	return *o.PayoutDescriptor
}

// GetPayoutDescriptorOk returns a tuple with the PayoutDescriptor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetPayoutDescriptorOk() (*string, bool) {
	if o == nil || IsNil(o.PayoutDescriptor) {
		return nil, false
	}
	return o.PayoutDescriptor, true
}

// HasPayoutDescriptor returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasPayoutDescriptor() bool {
	if o != nil && !IsNil(o.PayoutDescriptor) {
		return true
	}

	return false
}

// SetPayoutDescriptor gets a reference to the given string and assigns it to the PayoutDescriptor field.
func (o *BillUpdateRequest) SetPayoutDescriptor(v string) {
	o.PayoutDescriptor = &v
}

// GetPsp returns the Psp field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetPsp() []int32 {
	if o == nil || IsNil(o.Psp) {
		var ret []int32
		return ret
	}
	return o.Psp
}

// GetPspOk returns a tuple with the Psp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetPspOk() ([]int32, bool) {
	if o == nil || IsNil(o.Psp) {
		return nil, false
	}
	return o.Psp, true
}

// HasPsp returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasPsp() bool {
	if o != nil && !IsNil(o.Psp) {
		return true
	}

	return false
}

// SetPsp gets a reference to the given []int32 and assigns it to the Psp field.
func (o *BillUpdateRequest) SetPsp(v []int32) {
	o.Psp = v
}

// GetPm returns the Pm field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetPm() []string {
	if o == nil || IsNil(o.Pm) {
		var ret []string
		return ret
	}
	return o.Pm
}

// GetPmOk returns a tuple with the Pm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetPmOk() ([]string, bool) {
	if o == nil || IsNil(o.Pm) {
		return nil, false
	}
	return o.Pm, true
}

// HasPm returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasPm() bool {
	if o != nil && !IsNil(o.Pm) {
		return true
	}

	return false
}

// SetPm gets a reference to the given []string and assigns it to the Pm field.
func (o *BillUpdateRequest) SetPm(v []string) {
	o.Pm = v
}

// GetReminders returns the Reminders field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetReminders() []BillCreateRequestRemindersInner {
	if o == nil || IsNil(o.Reminders) {
		var ret []BillCreateRequestRemindersInner
		return ret
	}
	return o.Reminders
}

// GetRemindersOk returns a tuple with the Reminders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetRemindersOk() ([]BillCreateRequestRemindersInner, bool) {
	if o == nil || IsNil(o.Reminders) {
		return nil, false
	}
	return o.Reminders, true
}

// HasReminders returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasReminders() bool {
	if o != nil && !IsNil(o.Reminders) {
		return true
	}

	return false
}

// SetReminders gets a reference to the given []BillCreateRequestRemindersInner and assigns it to the Reminders field.
func (o *BillUpdateRequest) SetReminders(v []BillCreateRequestRemindersInner) {
	o.Reminders = v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *BillUpdateRequest) SetReference(v string) {
	o.Reference = &v
}

// GetDesign returns the Design field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetDesign() string {
	if o == nil || IsNil(o.Design) {
		var ret string
		return ret
	}
	return *o.Design
}

// GetDesignOk returns a tuple with the Design field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetDesignOk() (*string, bool) {
	if o == nil || IsNil(o.Design) {
		return nil, false
	}
	return o.Design, true
}

// HasDesign returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasDesign() bool {
	if o != nil && !IsNil(o.Design) {
		return true
	}

	return false
}

// SetDesign gets a reference to the given string and assigns it to the Design field.
func (o *BillUpdateRequest) SetDesign(v string) {
	o.Design = &v
}

// GetSend returns the Send field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetSend() bool {
	if o == nil || IsNil(o.Send) {
		var ret bool
		return ret
	}
	return *o.Send
}

// GetSendOk returns a tuple with the Send field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetSendOk() (*bool, bool) {
	if o == nil || IsNil(o.Send) {
		return nil, false
	}
	return o.Send, true
}

// HasSend returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasSend() bool {
	if o != nil && !IsNil(o.Send) {
		return true
	}

	return false
}

// SetSend gets a reference to the given bool and assigns it to the Send field.
func (o *BillUpdateRequest) SetSend(v bool) {
	o.Send = &v
}

// GetAdditionalRecipients returns the AdditionalRecipients field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetAdditionalRecipients() []string {
	if o == nil || IsNil(o.AdditionalRecipients) {
		var ret []string
		return ret
	}
	return o.AdditionalRecipients
}

// GetAdditionalRecipientsOk returns a tuple with the AdditionalRecipients field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetAdditionalRecipientsOk() ([]string, bool) {
	if o == nil || IsNil(o.AdditionalRecipients) {
		return nil, false
	}
	return o.AdditionalRecipients, true
}

// HasAdditionalRecipients returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasAdditionalRecipients() bool {
	if o != nil && !IsNil(o.AdditionalRecipients) {
		return true
	}

	return false
}

// SetAdditionalRecipients gets a reference to the given []string and assigns it to the AdditionalRecipients field.
func (o *BillUpdateRequest) SetAdditionalRecipients(v []string) {
	o.AdditionalRecipients = v
}

// GetComplete returns the Complete field value if set, zero value otherwise.
func (o *BillUpdateRequest) GetComplete() bool {
	if o == nil || IsNil(o.Complete) {
		var ret bool
		return ret
	}
	return *o.Complete
}

// GetCompleteOk returns a tuple with the Complete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillUpdateRequest) GetCompleteOk() (*bool, bool) {
	if o == nil || IsNil(o.Complete) {
		return nil, false
	}
	return o.Complete, true
}

// HasComplete returns a boolean if a field has been set.
func (o *BillUpdateRequest) HasComplete() bool {
	if o != nil && !IsNil(o.Complete) {
		return true
	}

	return false
}

// SetComplete gets a reference to the given bool and assigns it to the Complete field.
func (o *BillUpdateRequest) SetComplete(v bool) {
	o.Complete = &v
}

func (o BillUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Language) {
		toSerialize["language"] = o.Language
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.DueAfterDays) {
		toSerialize["dueAfterDays"] = o.DueAfterDays
	}
	if !IsNil(o.Recipient) {
		toSerialize["recipient"] = o.Recipient
	}
	if !IsNil(o.ServicePeriod) {
		toSerialize["servicePeriod"] = o.ServicePeriod
	}
	if !IsNil(o.Discount) {
		toSerialize["discount"] = o.Discount
	}
	if !IsNil(o.CashDiscounts) {
		toSerialize["cashDiscounts"] = o.CashDiscounts
	}
	if !IsNil(o.ShippingCost) {
		toSerialize["shippingCost"] = o.ShippingCost
	}
	if !IsNil(o.ApplicationFee) {
		toSerialize["applicationFee"] = o.ApplicationFee
	}
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}
	if !IsNil(o.Terms) {
		toSerialize["terms"] = o.Terms
	}
	if !IsNil(o.Positions) {
		toSerialize["positions"] = o.Positions
	}
	if !IsNil(o.Attachments) {
		toSerialize["attachments"] = o.Attachments
	}
	if !IsNil(o.BankInformation) {
		toSerialize["bankInformation"] = o.BankInformation
	}
	if !IsNil(o.PayoutDescriptor) {
		toSerialize["payoutDescriptor"] = o.PayoutDescriptor
	}
	if !IsNil(o.Psp) {
		toSerialize["psp"] = o.Psp
	}
	if !IsNil(o.Pm) {
		toSerialize["pm"] = o.Pm
	}
	if !IsNil(o.Reminders) {
		toSerialize["reminders"] = o.Reminders
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	if !IsNil(o.Design) {
		toSerialize["design"] = o.Design
	}
	if !IsNil(o.Send) {
		toSerialize["send"] = o.Send
	}
	if !IsNil(o.AdditionalRecipients) {
		toSerialize["additionalRecipients"] = o.AdditionalRecipients
	}
	if !IsNil(o.Complete) {
		toSerialize["complete"] = o.Complete
	}
	return toSerialize, nil
}

type NullableBillUpdateRequest struct {
	value *BillUpdateRequest
	isSet bool
}

func (v NullableBillUpdateRequest) Get() *BillUpdateRequest {
	return v.value
}

func (v *NullableBillUpdateRequest) Set(val *BillUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBillUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBillUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillUpdateRequest(val *BillUpdateRequest) *NullableBillUpdateRequest {
	return &NullableBillUpdateRequest{value: val, isSet: true}
}

func (v NullableBillUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
