/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the InvoicePositionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoicePositionsInner{}

// InvoicePositionsInner struct for InvoicePositionsInner
type InvoicePositionsInner struct {
	Title       *string          `json:"title,omitempty"`
	Description *string          `json:"description,omitempty"`
	Type        *string          `json:"type,omitempty"`
	Number      *int32           `json:"number,omitempty"`
	Price       *int32           `json:"price,omitempty"`
	Discount    *InvoiceDiscount `json:"discount,omitempty"`
	Vat         *int32           `json:"vat,omitempty"`
	Id          *string          `json:"id,omitempty"`
}

// NewInvoicePositionsInner instantiates a new InvoicePositionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoicePositionsInner() *InvoicePositionsInner {
	this := InvoicePositionsInner{}
	var number int32 = 0
	this.Number = &number
	var price int32 = 0
	this.Price = &price
	var vat int32 = 0
	this.Vat = &vat
	return &this
}

// NewInvoicePositionsInnerWithDefaults instantiates a new InvoicePositionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoicePositionsInnerWithDefaults() *InvoicePositionsInner {
	this := InvoicePositionsInner{}
	var number int32 = 0
	this.Number = &number
	var price int32 = 0
	this.Price = &price
	var vat int32 = 0
	this.Vat = &vat
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *InvoicePositionsInner) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicePositionsInner) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *InvoicePositionsInner) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *InvoicePositionsInner) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InvoicePositionsInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicePositionsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InvoicePositionsInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InvoicePositionsInner) SetDescription(v string) {
	o.Description = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *InvoicePositionsInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicePositionsInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *InvoicePositionsInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *InvoicePositionsInner) SetType(v string) {
	o.Type = &v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *InvoicePositionsInner) GetNumber() int32 {
	if o == nil || IsNil(o.Number) {
		var ret int32
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicePositionsInner) GetNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *InvoicePositionsInner) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given int32 and assigns it to the Number field.
func (o *InvoicePositionsInner) SetNumber(v int32) {
	o.Number = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *InvoicePositionsInner) GetPrice() int32 {
	if o == nil || IsNil(o.Price) {
		var ret int32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicePositionsInner) GetPriceOk() (*int32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *InvoicePositionsInner) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given int32 and assigns it to the Price field.
func (o *InvoicePositionsInner) SetPrice(v int32) {
	o.Price = &v
}

// GetDiscount returns the Discount field value if set, zero value otherwise.
func (o *InvoicePositionsInner) GetDiscount() InvoiceDiscount {
	if o == nil || IsNil(o.Discount) {
		var ret InvoiceDiscount
		return ret
	}
	return *o.Discount
}

// GetDiscountOk returns a tuple with the Discount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicePositionsInner) GetDiscountOk() (*InvoiceDiscount, bool) {
	if o == nil || IsNil(o.Discount) {
		return nil, false
	}
	return o.Discount, true
}

// HasDiscount returns a boolean if a field has been set.
func (o *InvoicePositionsInner) HasDiscount() bool {
	if o != nil && !IsNil(o.Discount) {
		return true
	}

	return false
}

// SetDiscount gets a reference to the given InvoiceDiscount and assigns it to the Discount field.
func (o *InvoicePositionsInner) SetDiscount(v InvoiceDiscount) {
	o.Discount = &v
}

// GetVat returns the Vat field value if set, zero value otherwise.
func (o *InvoicePositionsInner) GetVat() int32 {
	if o == nil || IsNil(o.Vat) {
		var ret int32
		return ret
	}
	return *o.Vat
}

// GetVatOk returns a tuple with the Vat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicePositionsInner) GetVatOk() (*int32, bool) {
	if o == nil || IsNil(o.Vat) {
		return nil, false
	}
	return o.Vat, true
}

// HasVat returns a boolean if a field has been set.
func (o *InvoicePositionsInner) HasVat() bool {
	if o != nil && !IsNil(o.Vat) {
		return true
	}

	return false
}

// SetVat gets a reference to the given int32 and assigns it to the Vat field.
func (o *InvoicePositionsInner) SetVat(v int32) {
	o.Vat = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InvoicePositionsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicePositionsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InvoicePositionsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *InvoicePositionsInner) SetId(v string) {
	o.Id = &v
}

func (o InvoicePositionsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoicePositionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Number) {
		toSerialize["number"] = o.Number
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	if !IsNil(o.Discount) {
		toSerialize["discount"] = o.Discount
	}
	if !IsNil(o.Vat) {
		toSerialize["vat"] = o.Vat
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableInvoicePositionsInner struct {
	value *InvoicePositionsInner
	isSet bool
}

func (v NullableInvoicePositionsInner) Get() *InvoicePositionsInner {
	return v.value
}

func (v *NullableInvoicePositionsInner) Set(val *InvoicePositionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoicePositionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoicePositionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoicePositionsInner(val *InvoicePositionsInner) *NullableInvoicePositionsInner {
	return &NullableInvoicePositionsInner{value: val, isSet: true}
}

func (v NullableInvoicePositionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoicePositionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
