/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the GatewayCreateRequestFieldsTitle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayCreateRequestFieldsTitle{}

// GatewayCreateRequestFieldsTitle struct for GatewayCreateRequestFieldsTitle
type GatewayCreateRequestFieldsTitle struct {
	// Value of field. Possible values are: mister, miss, diverse
	Value *string `json:"value,omitempty"`
}

// NewGatewayCreateRequestFieldsTitle instantiates a new GatewayCreateRequestFieldsTitle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayCreateRequestFieldsTitle() *GatewayCreateRequestFieldsTitle {
	this := GatewayCreateRequestFieldsTitle{}
	return &this
}

// NewGatewayCreateRequestFieldsTitleWithDefaults instantiates a new GatewayCreateRequestFieldsTitle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayCreateRequestFieldsTitleWithDefaults() *GatewayCreateRequestFieldsTitle {
	this := GatewayCreateRequestFieldsTitle{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *GatewayCreateRequestFieldsTitle) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequestFieldsTitle) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *GatewayCreateRequestFieldsTitle) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *GatewayCreateRequestFieldsTitle) SetValue(v string) {
	o.Value = &v
}

func (o GatewayCreateRequestFieldsTitle) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayCreateRequestFieldsTitle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableGatewayCreateRequestFieldsTitle struct {
	value *GatewayCreateRequestFieldsTitle
	isSet bool
}

func (v NullableGatewayCreateRequestFieldsTitle) Get() *GatewayCreateRequestFieldsTitle {
	return v.value
}

func (v *NullableGatewayCreateRequestFieldsTitle) Set(val *GatewayCreateRequestFieldsTitle) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayCreateRequestFieldsTitle) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayCreateRequestFieldsTitle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayCreateRequestFieldsTitle(val *GatewayCreateRequestFieldsTitle) *NullableGatewayCreateRequestFieldsTitle {
	return &NullableGatewayCreateRequestFieldsTitle{value: val, isSet: true}
}

func (v NullableGatewayCreateRequestFieldsTitle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayCreateRequestFieldsTitle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
