/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the InvoicePurchaseOnInvoiceInformation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoicePurchaseOnInvoiceInformation{}

// InvoicePurchaseOnInvoiceInformation struct for InvoicePurchaseOnInvoiceInformation
type InvoicePurchaseOnInvoiceInformation struct {
	Company   *string `json:"company,omitempty"`
	Address   *string `json:"address,omitempty"`
	Zip       *string `json:"zip,omitempty"`
	Place     *string `json:"place,omitempty"`
	BankName  *string `json:"bankName,omitempty"`
	Swift     *string `json:"swift,omitempty"`
	Iban      *string `json:"iban,omitempty"`
	Reference *string `json:"reference,omitempty"`
}

// NewInvoicePurchaseOnInvoiceInformation instantiates a new InvoicePurchaseOnInvoiceInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoicePurchaseOnInvoiceInformation() *InvoicePurchaseOnInvoiceInformation {
	this := InvoicePurchaseOnInvoiceInformation{}
	return &this
}

// NewInvoicePurchaseOnInvoiceInformationWithDefaults instantiates a new InvoicePurchaseOnInvoiceInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoicePurchaseOnInvoiceInformationWithDefaults() *InvoicePurchaseOnInvoiceInformation {
	this := InvoicePurchaseOnInvoiceInformation{}
	return &this
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *InvoicePurchaseOnInvoiceInformation) GetCompany() string {
	if o == nil || IsNil(o.Company) {
		var ret string
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicePurchaseOnInvoiceInformation) GetCompanyOk() (*string, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *InvoicePurchaseOnInvoiceInformation) HasCompany() bool {
	if o != nil && !IsNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given string and assigns it to the Company field.
func (o *InvoicePurchaseOnInvoiceInformation) SetCompany(v string) {
	o.Company = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *InvoicePurchaseOnInvoiceInformation) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicePurchaseOnInvoiceInformation) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *InvoicePurchaseOnInvoiceInformation) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *InvoicePurchaseOnInvoiceInformation) SetAddress(v string) {
	o.Address = &v
}

// GetZip returns the Zip field value if set, zero value otherwise.
func (o *InvoicePurchaseOnInvoiceInformation) GetZip() string {
	if o == nil || IsNil(o.Zip) {
		var ret string
		return ret
	}
	return *o.Zip
}

// GetZipOk returns a tuple with the Zip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicePurchaseOnInvoiceInformation) GetZipOk() (*string, bool) {
	if o == nil || IsNil(o.Zip) {
		return nil, false
	}
	return o.Zip, true
}

// HasZip returns a boolean if a field has been set.
func (o *InvoicePurchaseOnInvoiceInformation) HasZip() bool {
	if o != nil && !IsNil(o.Zip) {
		return true
	}

	return false
}

// SetZip gets a reference to the given string and assigns it to the Zip field.
func (o *InvoicePurchaseOnInvoiceInformation) SetZip(v string) {
	o.Zip = &v
}

// GetPlace returns the Place field value if set, zero value otherwise.
func (o *InvoicePurchaseOnInvoiceInformation) GetPlace() string {
	if o == nil || IsNil(o.Place) {
		var ret string
		return ret
	}
	return *o.Place
}

// GetPlaceOk returns a tuple with the Place field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicePurchaseOnInvoiceInformation) GetPlaceOk() (*string, bool) {
	if o == nil || IsNil(o.Place) {
		return nil, false
	}
	return o.Place, true
}

// HasPlace returns a boolean if a field has been set.
func (o *InvoicePurchaseOnInvoiceInformation) HasPlace() bool {
	if o != nil && !IsNil(o.Place) {
		return true
	}

	return false
}

// SetPlace gets a reference to the given string and assigns it to the Place field.
func (o *InvoicePurchaseOnInvoiceInformation) SetPlace(v string) {
	o.Place = &v
}

// GetBankName returns the BankName field value if set, zero value otherwise.
func (o *InvoicePurchaseOnInvoiceInformation) GetBankName() string {
	if o == nil || IsNil(o.BankName) {
		var ret string
		return ret
	}
	return *o.BankName
}

// GetBankNameOk returns a tuple with the BankName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicePurchaseOnInvoiceInformation) GetBankNameOk() (*string, bool) {
	if o == nil || IsNil(o.BankName) {
		return nil, false
	}
	return o.BankName, true
}

// HasBankName returns a boolean if a field has been set.
func (o *InvoicePurchaseOnInvoiceInformation) HasBankName() bool {
	if o != nil && !IsNil(o.BankName) {
		return true
	}

	return false
}

// SetBankName gets a reference to the given string and assigns it to the BankName field.
func (o *InvoicePurchaseOnInvoiceInformation) SetBankName(v string) {
	o.BankName = &v
}

// GetSwift returns the Swift field value if set, zero value otherwise.
func (o *InvoicePurchaseOnInvoiceInformation) GetSwift() string {
	if o == nil || IsNil(o.Swift) {
		var ret string
		return ret
	}
	return *o.Swift
}

// GetSwiftOk returns a tuple with the Swift field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicePurchaseOnInvoiceInformation) GetSwiftOk() (*string, bool) {
	if o == nil || IsNil(o.Swift) {
		return nil, false
	}
	return o.Swift, true
}

// HasSwift returns a boolean if a field has been set.
func (o *InvoicePurchaseOnInvoiceInformation) HasSwift() bool {
	if o != nil && !IsNil(o.Swift) {
		return true
	}

	return false
}

// SetSwift gets a reference to the given string and assigns it to the Swift field.
func (o *InvoicePurchaseOnInvoiceInformation) SetSwift(v string) {
	o.Swift = &v
}

// GetIban returns the Iban field value if set, zero value otherwise.
func (o *InvoicePurchaseOnInvoiceInformation) GetIban() string {
	if o == nil || IsNil(o.Iban) {
		var ret string
		return ret
	}
	return *o.Iban
}

// GetIbanOk returns a tuple with the Iban field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicePurchaseOnInvoiceInformation) GetIbanOk() (*string, bool) {
	if o == nil || IsNil(o.Iban) {
		return nil, false
	}
	return o.Iban, true
}

// HasIban returns a boolean if a field has been set.
func (o *InvoicePurchaseOnInvoiceInformation) HasIban() bool {
	if o != nil && !IsNil(o.Iban) {
		return true
	}

	return false
}

// SetIban gets a reference to the given string and assigns it to the Iban field.
func (o *InvoicePurchaseOnInvoiceInformation) SetIban(v string) {
	o.Iban = &v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *InvoicePurchaseOnInvoiceInformation) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicePurchaseOnInvoiceInformation) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *InvoicePurchaseOnInvoiceInformation) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *InvoicePurchaseOnInvoiceInformation) SetReference(v string) {
	o.Reference = &v
}

func (o InvoicePurchaseOnInvoiceInformation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoicePurchaseOnInvoiceInformation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Company) {
		toSerialize["company"] = o.Company
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Zip) {
		toSerialize["zip"] = o.Zip
	}
	if !IsNil(o.Place) {
		toSerialize["place"] = o.Place
	}
	if !IsNil(o.BankName) {
		toSerialize["bankName"] = o.BankName
	}
	if !IsNil(o.Swift) {
		toSerialize["swift"] = o.Swift
	}
	if !IsNil(o.Iban) {
		toSerialize["iban"] = o.Iban
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	return toSerialize, nil
}

type NullableInvoicePurchaseOnInvoiceInformation struct {
	value *InvoicePurchaseOnInvoiceInformation
	isSet bool
}

func (v NullableInvoicePurchaseOnInvoiceInformation) Get() *InvoicePurchaseOnInvoiceInformation {
	return v.value
}

func (v *NullableInvoicePurchaseOnInvoiceInformation) Set(val *InvoicePurchaseOnInvoiceInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoicePurchaseOnInvoiceInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoicePurchaseOnInvoiceInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoicePurchaseOnInvoiceInformation(val *InvoicePurchaseOnInvoiceInformation) *NullableInvoicePurchaseOnInvoiceInformation {
	return &NullableInvoicePurchaseOnInvoiceInformation{value: val, isSet: true}
}

func (v NullableInvoicePurchaseOnInvoiceInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoicePurchaseOnInvoiceInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
