/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the TransactionInvoiceDiscount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionInvoiceDiscount{}

// TransactionInvoiceDiscount struct for TransactionInvoiceDiscount
type TransactionInvoiceDiscount struct {
	Code       *string `json:"code,omitempty"`
	Percentage *int32  `json:"percentage,omitempty"`
	Amount     *int32  `json:"amount,omitempty"`
}

// NewTransactionInvoiceDiscount instantiates a new TransactionInvoiceDiscount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionInvoiceDiscount() *TransactionInvoiceDiscount {
	this := TransactionInvoiceDiscount{}
	var percentage int32 = 0
	this.Percentage = &percentage
	var amount int32 = 0
	this.Amount = &amount
	return &this
}

// NewTransactionInvoiceDiscountWithDefaults instantiates a new TransactionInvoiceDiscount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionInvoiceDiscountWithDefaults() *TransactionInvoiceDiscount {
	this := TransactionInvoiceDiscount{}
	var percentage int32 = 0
	this.Percentage = &percentage
	var amount int32 = 0
	this.Amount = &amount
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *TransactionInvoiceDiscount) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInvoiceDiscount) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *TransactionInvoiceDiscount) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *TransactionInvoiceDiscount) SetCode(v string) {
	o.Code = &v
}

// GetPercentage returns the Percentage field value if set, zero value otherwise.
func (o *TransactionInvoiceDiscount) GetPercentage() int32 {
	if o == nil || IsNil(o.Percentage) {
		var ret int32
		return ret
	}
	return *o.Percentage
}

// GetPercentageOk returns a tuple with the Percentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInvoiceDiscount) GetPercentageOk() (*int32, bool) {
	if o == nil || IsNil(o.Percentage) {
		return nil, false
	}
	return o.Percentage, true
}

// HasPercentage returns a boolean if a field has been set.
func (o *TransactionInvoiceDiscount) HasPercentage() bool {
	if o != nil && !IsNil(o.Percentage) {
		return true
	}

	return false
}

// SetPercentage gets a reference to the given int32 and assigns it to the Percentage field.
func (o *TransactionInvoiceDiscount) SetPercentage(v int32) {
	o.Percentage = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *TransactionInvoiceDiscount) GetAmount() int32 {
	if o == nil || IsNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInvoiceDiscount) GetAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *TransactionInvoiceDiscount) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *TransactionInvoiceDiscount) SetAmount(v int32) {
	o.Amount = &v
}

func (o TransactionInvoiceDiscount) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionInvoiceDiscount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Percentage) {
		toSerialize["percentage"] = o.Percentage
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	return toSerialize, nil
}

type NullableTransactionInvoiceDiscount struct {
	value *TransactionInvoiceDiscount
	isSet bool
}

func (v NullableTransactionInvoiceDiscount) Get() *TransactionInvoiceDiscount {
	return v.value
}

func (v *NullableTransactionInvoiceDiscount) Set(val *TransactionInvoiceDiscount) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionInvoiceDiscount) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionInvoiceDiscount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionInvoiceDiscount(val *TransactionInvoiceDiscount) *NullableTransactionInvoiceDiscount {
	return &NullableTransactionInvoiceDiscount{value: val, isSet: true}
}

func (v NullableTransactionInvoiceDiscount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionInvoiceDiscount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
