/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the GatewayFieldsDateOfBirth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayFieldsDateOfBirth{}

// GatewayFieldsDateOfBirth struct for GatewayFieldsDateOfBirth
type GatewayFieldsDateOfBirth struct {
	Active    *bool                          `json:"active,omitempty"`
	Mandatory *bool                          `json:"mandatory,omitempty"`
	Names     *GatewayFieldsDateOfBirthNames `json:"names,omitempty"`
}

// NewGatewayFieldsDateOfBirth instantiates a new GatewayFieldsDateOfBirth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayFieldsDateOfBirth() *GatewayFieldsDateOfBirth {
	this := GatewayFieldsDateOfBirth{}
	var active bool = true
	this.Active = &active
	var mandatory bool = true
	this.Mandatory = &mandatory
	return &this
}

// NewGatewayFieldsDateOfBirthWithDefaults instantiates a new GatewayFieldsDateOfBirth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayFieldsDateOfBirthWithDefaults() *GatewayFieldsDateOfBirth {
	this := GatewayFieldsDateOfBirth{}
	var active bool = true
	this.Active = &active
	var mandatory bool = true
	this.Mandatory = &mandatory
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *GatewayFieldsDateOfBirth) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayFieldsDateOfBirth) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *GatewayFieldsDateOfBirth) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *GatewayFieldsDateOfBirth) SetActive(v bool) {
	o.Active = &v
}

// GetMandatory returns the Mandatory field value if set, zero value otherwise.
func (o *GatewayFieldsDateOfBirth) GetMandatory() bool {
	if o == nil || IsNil(o.Mandatory) {
		var ret bool
		return ret
	}
	return *o.Mandatory
}

// GetMandatoryOk returns a tuple with the Mandatory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayFieldsDateOfBirth) GetMandatoryOk() (*bool, bool) {
	if o == nil || IsNil(o.Mandatory) {
		return nil, false
	}
	return o.Mandatory, true
}

// HasMandatory returns a boolean if a field has been set.
func (o *GatewayFieldsDateOfBirth) HasMandatory() bool {
	if o != nil && !IsNil(o.Mandatory) {
		return true
	}

	return false
}

// SetMandatory gets a reference to the given bool and assigns it to the Mandatory field.
func (o *GatewayFieldsDateOfBirth) SetMandatory(v bool) {
	o.Mandatory = &v
}

// GetNames returns the Names field value if set, zero value otherwise.
func (o *GatewayFieldsDateOfBirth) GetNames() GatewayFieldsDateOfBirthNames {
	if o == nil || IsNil(o.Names) {
		var ret GatewayFieldsDateOfBirthNames
		return ret
	}
	return *o.Names
}

// GetNamesOk returns a tuple with the Names field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayFieldsDateOfBirth) GetNamesOk() (*GatewayFieldsDateOfBirthNames, bool) {
	if o == nil || IsNil(o.Names) {
		return nil, false
	}
	return o.Names, true
}

// HasNames returns a boolean if a field has been set.
func (o *GatewayFieldsDateOfBirth) HasNames() bool {
	if o != nil && !IsNil(o.Names) {
		return true
	}

	return false
}

// SetNames gets a reference to the given GatewayFieldsDateOfBirthNames and assigns it to the Names field.
func (o *GatewayFieldsDateOfBirth) SetNames(v GatewayFieldsDateOfBirthNames) {
	o.Names = &v
}

func (o GatewayFieldsDateOfBirth) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayFieldsDateOfBirth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Mandatory) {
		toSerialize["mandatory"] = o.Mandatory
	}
	if !IsNil(o.Names) {
		toSerialize["names"] = o.Names
	}
	return toSerialize, nil
}

type NullableGatewayFieldsDateOfBirth struct {
	value *GatewayFieldsDateOfBirth
	isSet bool
}

func (v NullableGatewayFieldsDateOfBirth) Get() *GatewayFieldsDateOfBirth {
	return v.value
}

func (v *NullableGatewayFieldsDateOfBirth) Set(val *GatewayFieldsDateOfBirth) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayFieldsDateOfBirth) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayFieldsDateOfBirth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayFieldsDateOfBirth(val *GatewayFieldsDateOfBirth) *NullableGatewayFieldsDateOfBirth {
	return &NullableGatewayFieldsDateOfBirth{value: val, isSet: true}
}

func (v NullableGatewayFieldsDateOfBirth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayFieldsDateOfBirth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
