/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the InvoiceServicePeriod type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoiceServicePeriod{}

// InvoiceServicePeriod struct for InvoiceServicePeriod
type InvoiceServicePeriod struct {
	From *string `json:"from,omitempty"`
	To   *string `json:"to,omitempty"`
}

// NewInvoiceServicePeriod instantiates a new InvoiceServicePeriod object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceServicePeriod() *InvoiceServicePeriod {
	this := InvoiceServicePeriod{}
	return &this
}

// NewInvoiceServicePeriodWithDefaults instantiates a new InvoiceServicePeriod object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceServicePeriodWithDefaults() *InvoiceServicePeriod {
	this := InvoiceServicePeriod{}
	return &this
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *InvoiceServicePeriod) GetFrom() string {
	if o == nil || IsNil(o.From) {
		var ret string
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceServicePeriod) GetFromOk() (*string, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *InvoiceServicePeriod) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given string and assigns it to the From field.
func (o *InvoiceServicePeriod) SetFrom(v string) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *InvoiceServicePeriod) GetTo() string {
	if o == nil || IsNil(o.To) {
		var ret string
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceServicePeriod) GetToOk() (*string, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *InvoiceServicePeriod) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given string and assigns it to the To field.
func (o *InvoiceServicePeriod) SetTo(v string) {
	o.To = &v
}

func (o InvoiceServicePeriod) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoiceServicePeriod) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	return toSerialize, nil
}

type NullableInvoiceServicePeriod struct {
	value *InvoiceServicePeriod
	isSet bool
}

func (v NullableInvoiceServicePeriod) Get() *InvoiceServicePeriod {
	return v.value
}

func (v *NullableInvoiceServicePeriod) Set(val *InvoiceServicePeriod) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceServicePeriod) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceServicePeriod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceServicePeriod(val *InvoiceServicePeriod) *NullableInvoiceServicePeriod {
	return &NullableInvoiceServicePeriod{value: val, isSet: true}
}

func (v NullableInvoiceServicePeriod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceServicePeriod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
