/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EcrPaymentMethodList200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EcrPaymentMethodList200Response{}

// EcrPaymentMethodList200Response struct for EcrPaymentMethodList200Response
type EcrPaymentMethodList200Response struct {
	Status string             `json:"status"`
	Data   []EcrPaymentMethod `json:"data,omitempty"`
}

type _EcrPaymentMethodList200Response EcrPaymentMethodList200Response

// NewEcrPaymentMethodList200Response instantiates a new EcrPaymentMethodList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEcrPaymentMethodList200Response(status string) *EcrPaymentMethodList200Response {
	this := EcrPaymentMethodList200Response{}
	this.Status = status
	return &this
}

// NewEcrPaymentMethodList200ResponseWithDefaults instantiates a new EcrPaymentMethodList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEcrPaymentMethodList200ResponseWithDefaults() *EcrPaymentMethodList200Response {
	this := EcrPaymentMethodList200Response{}
	return &this
}

// GetStatus returns the Status field value
func (o *EcrPaymentMethodList200Response) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *EcrPaymentMethodList200Response) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *EcrPaymentMethodList200Response) SetStatus(v string) {
	o.Status = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *EcrPaymentMethodList200Response) GetData() []EcrPaymentMethod {
	if o == nil || IsNil(o.Data) {
		var ret []EcrPaymentMethod
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EcrPaymentMethodList200Response) GetDataOk() ([]EcrPaymentMethod, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *EcrPaymentMethodList200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []EcrPaymentMethod and assigns it to the Data field.
func (o *EcrPaymentMethodList200Response) SetData(v []EcrPaymentMethod) {
	o.Data = v
}

func (o EcrPaymentMethodList200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EcrPaymentMethodList200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

func (o *EcrPaymentMethodList200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEcrPaymentMethodList200Response := _EcrPaymentMethodList200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEcrPaymentMethodList200Response)

	if err != nil {
		return err
	}

	*o = EcrPaymentMethodList200Response(varEcrPaymentMethodList200Response)

	return err
}

type NullableEcrPaymentMethodList200Response struct {
	value *EcrPaymentMethodList200Response
	isSet bool
}

func (v NullableEcrPaymentMethodList200Response) Get() *EcrPaymentMethodList200Response {
	return v.value
}

func (v *NullableEcrPaymentMethodList200Response) Set(val *EcrPaymentMethodList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableEcrPaymentMethodList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableEcrPaymentMethodList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEcrPaymentMethodList200Response(val *EcrPaymentMethodList200Response) *NullableEcrPaymentMethodList200Response {
	return &NullableEcrPaymentMethodList200Response{value: val, isSet: true}
}

func (v NullableEcrPaymentMethodList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEcrPaymentMethodList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
