/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the TransactionPayment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionPayment{}

// TransactionPayment struct for TransactionPayment
type TransactionPayment struct {
	Brand                        *string                                         `json:"brand,omitempty"`
	Wallet                       interface{}                                     `json:"wallet,omitempty"`
	PurchaseOnInvoiceInformation *TransactionPaymentPurchaseOnInvoiceInformation `json:"purchaseOnInvoiceInformation,omitempty"`
}

// NewTransactionPayment instantiates a new TransactionPayment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionPayment() *TransactionPayment {
	this := TransactionPayment{}
	return &this
}

// NewTransactionPaymentWithDefaults instantiates a new TransactionPayment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionPaymentWithDefaults() *TransactionPayment {
	this := TransactionPayment{}
	return &this
}

// GetBrand returns the Brand field value if set, zero value otherwise.
func (o *TransactionPayment) GetBrand() string {
	if o == nil || IsNil(o.Brand) {
		var ret string
		return ret
	}
	return *o.Brand
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionPayment) GetBrandOk() (*string, bool) {
	if o == nil || IsNil(o.Brand) {
		return nil, false
	}
	return o.Brand, true
}

// HasBrand returns a boolean if a field has been set.
func (o *TransactionPayment) HasBrand() bool {
	if o != nil && !IsNil(o.Brand) {
		return true
	}

	return false
}

// SetBrand gets a reference to the given string and assigns it to the Brand field.
func (o *TransactionPayment) SetBrand(v string) {
	o.Brand = &v
}

// GetWallet returns the Wallet field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TransactionPayment) GetWallet() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Wallet
}

// GetWalletOk returns a tuple with the Wallet field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionPayment) GetWalletOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Wallet) {
		return nil, false
	}
	return &o.Wallet, true
}

// HasWallet returns a boolean if a field has been set.
func (o *TransactionPayment) HasWallet() bool {
	if o != nil && !IsNil(o.Wallet) {
		return true
	}

	return false
}

// SetWallet gets a reference to the given interface{} and assigns it to the Wallet field.
func (o *TransactionPayment) SetWallet(v interface{}) {
	o.Wallet = v
}

// GetPurchaseOnInvoiceInformation returns the PurchaseOnInvoiceInformation field value if set, zero value otherwise.
func (o *TransactionPayment) GetPurchaseOnInvoiceInformation() TransactionPaymentPurchaseOnInvoiceInformation {
	if o == nil || IsNil(o.PurchaseOnInvoiceInformation) {
		var ret TransactionPaymentPurchaseOnInvoiceInformation
		return ret
	}
	return *o.PurchaseOnInvoiceInformation
}

// GetPurchaseOnInvoiceInformationOk returns a tuple with the PurchaseOnInvoiceInformation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionPayment) GetPurchaseOnInvoiceInformationOk() (*TransactionPaymentPurchaseOnInvoiceInformation, bool) {
	if o == nil || IsNil(o.PurchaseOnInvoiceInformation) {
		return nil, false
	}
	return o.PurchaseOnInvoiceInformation, true
}

// HasPurchaseOnInvoiceInformation returns a boolean if a field has been set.
func (o *TransactionPayment) HasPurchaseOnInvoiceInformation() bool {
	if o != nil && !IsNil(o.PurchaseOnInvoiceInformation) {
		return true
	}

	return false
}

// SetPurchaseOnInvoiceInformation gets a reference to the given TransactionPaymentPurchaseOnInvoiceInformation and assigns it to the PurchaseOnInvoiceInformation field.
func (o *TransactionPayment) SetPurchaseOnInvoiceInformation(v TransactionPaymentPurchaseOnInvoiceInformation) {
	o.PurchaseOnInvoiceInformation = &v
}

func (o TransactionPayment) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionPayment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Brand) {
		toSerialize["brand"] = o.Brand
	}
	if o.Wallet != nil {
		toSerialize["wallet"] = o.Wallet
	}
	if !IsNil(o.PurchaseOnInvoiceInformation) {
		toSerialize["purchaseOnInvoiceInformation"] = o.PurchaseOnInvoiceInformation
	}
	return toSerialize, nil
}

type NullableTransactionPayment struct {
	value *TransactionPayment
	isSet bool
}

func (v NullableTransactionPayment) Get() *TransactionPayment {
	return v.value
}

func (v *NullableTransactionPayment) Set(val *TransactionPayment) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionPayment) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionPayment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionPayment(val *TransactionPayment) *NullableTransactionPayment {
	return &NullableTransactionPayment{value: val, isSet: true}
}

func (v NullableTransactionPayment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionPayment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
