/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the TransactionPaymentPurchaseOnInvoiceInformation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionPaymentPurchaseOnInvoiceInformation{}

// TransactionPaymentPurchaseOnInvoiceInformation struct for TransactionPaymentPurchaseOnInvoiceInformation
type TransactionPaymentPurchaseOnInvoiceInformation struct {
	Zip       *string `json:"zip,omitempty"`
	Iban      *string `json:"iban,omitempty"`
	Place     *string `json:"place,omitempty"`
	Swift     *string `json:"swift,omitempty"`
	Address   *string `json:"address,omitempty"`
	Company   *string `json:"company,omitempty"`
	BankName  *string `json:"bankName,omitempty"`
	Reference *string `json:"reference,omitempty"`
}

// NewTransactionPaymentPurchaseOnInvoiceInformation instantiates a new TransactionPaymentPurchaseOnInvoiceInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionPaymentPurchaseOnInvoiceInformation() *TransactionPaymentPurchaseOnInvoiceInformation {
	this := TransactionPaymentPurchaseOnInvoiceInformation{}
	return &this
}

// NewTransactionPaymentPurchaseOnInvoiceInformationWithDefaults instantiates a new TransactionPaymentPurchaseOnInvoiceInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionPaymentPurchaseOnInvoiceInformationWithDefaults() *TransactionPaymentPurchaseOnInvoiceInformation {
	this := TransactionPaymentPurchaseOnInvoiceInformation{}
	return &this
}

// GetZip returns the Zip field value if set, zero value otherwise.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) GetZip() string {
	if o == nil || IsNil(o.Zip) {
		var ret string
		return ret
	}
	return *o.Zip
}

// GetZipOk returns a tuple with the Zip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) GetZipOk() (*string, bool) {
	if o == nil || IsNil(o.Zip) {
		return nil, false
	}
	return o.Zip, true
}

// HasZip returns a boolean if a field has been set.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) HasZip() bool {
	if o != nil && !IsNil(o.Zip) {
		return true
	}

	return false
}

// SetZip gets a reference to the given string and assigns it to the Zip field.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) SetZip(v string) {
	o.Zip = &v
}

// GetIban returns the Iban field value if set, zero value otherwise.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) GetIban() string {
	if o == nil || IsNil(o.Iban) {
		var ret string
		return ret
	}
	return *o.Iban
}

// GetIbanOk returns a tuple with the Iban field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) GetIbanOk() (*string, bool) {
	if o == nil || IsNil(o.Iban) {
		return nil, false
	}
	return o.Iban, true
}

// HasIban returns a boolean if a field has been set.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) HasIban() bool {
	if o != nil && !IsNil(o.Iban) {
		return true
	}

	return false
}

// SetIban gets a reference to the given string and assigns it to the Iban field.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) SetIban(v string) {
	o.Iban = &v
}

// GetPlace returns the Place field value if set, zero value otherwise.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) GetPlace() string {
	if o == nil || IsNil(o.Place) {
		var ret string
		return ret
	}
	return *o.Place
}

// GetPlaceOk returns a tuple with the Place field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) GetPlaceOk() (*string, bool) {
	if o == nil || IsNil(o.Place) {
		return nil, false
	}
	return o.Place, true
}

// HasPlace returns a boolean if a field has been set.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) HasPlace() bool {
	if o != nil && !IsNil(o.Place) {
		return true
	}

	return false
}

// SetPlace gets a reference to the given string and assigns it to the Place field.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) SetPlace(v string) {
	o.Place = &v
}

// GetSwift returns the Swift field value if set, zero value otherwise.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) GetSwift() string {
	if o == nil || IsNil(o.Swift) {
		var ret string
		return ret
	}
	return *o.Swift
}

// GetSwiftOk returns a tuple with the Swift field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) GetSwiftOk() (*string, bool) {
	if o == nil || IsNil(o.Swift) {
		return nil, false
	}
	return o.Swift, true
}

// HasSwift returns a boolean if a field has been set.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) HasSwift() bool {
	if o != nil && !IsNil(o.Swift) {
		return true
	}

	return false
}

// SetSwift gets a reference to the given string and assigns it to the Swift field.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) SetSwift(v string) {
	o.Swift = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) SetAddress(v string) {
	o.Address = &v
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) GetCompany() string {
	if o == nil || IsNil(o.Company) {
		var ret string
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) GetCompanyOk() (*string, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) HasCompany() bool {
	if o != nil && !IsNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given string and assigns it to the Company field.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) SetCompany(v string) {
	o.Company = &v
}

// GetBankName returns the BankName field value if set, zero value otherwise.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) GetBankName() string {
	if o == nil || IsNil(o.BankName) {
		var ret string
		return ret
	}
	return *o.BankName
}

// GetBankNameOk returns a tuple with the BankName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) GetBankNameOk() (*string, bool) {
	if o == nil || IsNil(o.BankName) {
		return nil, false
	}
	return o.BankName, true
}

// HasBankName returns a boolean if a field has been set.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) HasBankName() bool {
	if o != nil && !IsNil(o.BankName) {
		return true
	}

	return false
}

// SetBankName gets a reference to the given string and assigns it to the BankName field.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) SetBankName(v string) {
	o.BankName = &v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *TransactionPaymentPurchaseOnInvoiceInformation) SetReference(v string) {
	o.Reference = &v
}

func (o TransactionPaymentPurchaseOnInvoiceInformation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionPaymentPurchaseOnInvoiceInformation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Zip) {
		toSerialize["zip"] = o.Zip
	}
	if !IsNil(o.Iban) {
		toSerialize["iban"] = o.Iban
	}
	if !IsNil(o.Place) {
		toSerialize["place"] = o.Place
	}
	if !IsNil(o.Swift) {
		toSerialize["swift"] = o.Swift
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Company) {
		toSerialize["company"] = o.Company
	}
	if !IsNil(o.BankName) {
		toSerialize["bankName"] = o.BankName
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	return toSerialize, nil
}

type NullableTransactionPaymentPurchaseOnInvoiceInformation struct {
	value *TransactionPaymentPurchaseOnInvoiceInformation
	isSet bool
}

func (v NullableTransactionPaymentPurchaseOnInvoiceInformation) Get() *TransactionPaymentPurchaseOnInvoiceInformation {
	return v.value
}

func (v *NullableTransactionPaymentPurchaseOnInvoiceInformation) Set(val *TransactionPaymentPurchaseOnInvoiceInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionPaymentPurchaseOnInvoiceInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionPaymentPurchaseOnInvoiceInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionPaymentPurchaseOnInvoiceInformation(val *TransactionPaymentPurchaseOnInvoiceInformation) *NullableTransactionPaymentPurchaseOnInvoiceInformation {
	return &NullableTransactionPaymentPurchaseOnInvoiceInformation{value: val, isSet: true}
}

func (v NullableTransactionPaymentPurchaseOnInvoiceInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionPaymentPurchaseOnInvoiceInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
