/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EcrPaymentInitiate200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EcrPaymentInitiate200Response{}

// EcrPaymentInitiate200Response struct for EcrPaymentInitiate200Response
type EcrPaymentInitiate200Response struct {
	Status string      `json:"status"`
	Data   *EcrPayment `json:"data,omitempty"`
	// Contains error messages
	Message *string `json:"message,omitempty"`
}

type _EcrPaymentInitiate200Response EcrPaymentInitiate200Response

// NewEcrPaymentInitiate200Response instantiates a new EcrPaymentInitiate200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEcrPaymentInitiate200Response(status string) *EcrPaymentInitiate200Response {
	this := EcrPaymentInitiate200Response{}
	this.Status = status
	return &this
}

// NewEcrPaymentInitiate200ResponseWithDefaults instantiates a new EcrPaymentInitiate200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEcrPaymentInitiate200ResponseWithDefaults() *EcrPaymentInitiate200Response {
	this := EcrPaymentInitiate200Response{}
	return &this
}

// GetStatus returns the Status field value
func (o *EcrPaymentInitiate200Response) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *EcrPaymentInitiate200Response) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *EcrPaymentInitiate200Response) SetStatus(v string) {
	o.Status = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *EcrPaymentInitiate200Response) GetData() EcrPayment {
	if o == nil || IsNil(o.Data) {
		var ret EcrPayment
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EcrPaymentInitiate200Response) GetDataOk() (*EcrPayment, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *EcrPaymentInitiate200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given EcrPayment and assigns it to the Data field.
func (o *EcrPaymentInitiate200Response) SetData(v EcrPayment) {
	o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *EcrPaymentInitiate200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EcrPaymentInitiate200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *EcrPaymentInitiate200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *EcrPaymentInitiate200Response) SetMessage(v string) {
	o.Message = &v
}

func (o EcrPaymentInitiate200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EcrPaymentInitiate200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

func (o *EcrPaymentInitiate200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEcrPaymentInitiate200Response := _EcrPaymentInitiate200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEcrPaymentInitiate200Response)

	if err != nil {
		return err
	}

	*o = EcrPaymentInitiate200Response(varEcrPaymentInitiate200Response)

	return err
}

type NullableEcrPaymentInitiate200Response struct {
	value *EcrPaymentInitiate200Response
	isSet bool
}

func (v NullableEcrPaymentInitiate200Response) Get() *EcrPaymentInitiate200Response {
	return v.value
}

func (v *NullableEcrPaymentInitiate200Response) Set(val *EcrPaymentInitiate200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableEcrPaymentInitiate200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableEcrPaymentInitiate200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEcrPaymentInitiate200Response(val *EcrPaymentInitiate200Response) *NullableEcrPaymentInitiate200Response {
	return &NullableEcrPaymentInitiate200Response{value: val, isSet: true}
}

func (v NullableEcrPaymentInitiate200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEcrPaymentInitiate200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
