/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BillCreateRequestRecipient type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillCreateRequestRecipient{}

// BillCreateRequestRecipient struct for BillCreateRequestRecipient
type BillCreateRequestRecipient struct {
	// **Required:** at least one of `company`, `firstName`, or `lastName` must be **provided**
	Company *string `json:"company,omitempty"`
	// **Required:** at least one of `company`, `firstName`, or `lastName` must be **provided**
	FirstName *string `json:"firstName,omitempty"`
	// **Required:** at least one of `company`, `firstName`, or `lastName` must be **provided**
	LastName *string `json:"lastName,omitempty"`
	Address  *string `json:"address,omitempty"`
	Zip      *string `json:"zip,omitempty"`
	City     *string `json:"city,omitempty"`
	// Country code (ISO 3166-1 alpha-2)
	Country *string `json:"country,omitempty"`
	Email   string  `json:"email"`
}

type _BillCreateRequestRecipient BillCreateRequestRecipient

// NewBillCreateRequestRecipient instantiates a new BillCreateRequestRecipient object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillCreateRequestRecipient(email string) *BillCreateRequestRecipient {
	this := BillCreateRequestRecipient{}
	this.Email = email
	return &this
}

// NewBillCreateRequestRecipientWithDefaults instantiates a new BillCreateRequestRecipient object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillCreateRequestRecipientWithDefaults() *BillCreateRequestRecipient {
	this := BillCreateRequestRecipient{}
	return &this
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *BillCreateRequestRecipient) GetCompany() string {
	if o == nil || IsNil(o.Company) {
		var ret string
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequestRecipient) GetCompanyOk() (*string, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *BillCreateRequestRecipient) HasCompany() bool {
	if o != nil && !IsNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given string and assigns it to the Company field.
func (o *BillCreateRequestRecipient) SetCompany(v string) {
	o.Company = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *BillCreateRequestRecipient) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequestRecipient) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *BillCreateRequestRecipient) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *BillCreateRequestRecipient) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *BillCreateRequestRecipient) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequestRecipient) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *BillCreateRequestRecipient) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *BillCreateRequestRecipient) SetLastName(v string) {
	o.LastName = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *BillCreateRequestRecipient) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequestRecipient) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *BillCreateRequestRecipient) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *BillCreateRequestRecipient) SetAddress(v string) {
	o.Address = &v
}

// GetZip returns the Zip field value if set, zero value otherwise.
func (o *BillCreateRequestRecipient) GetZip() string {
	if o == nil || IsNil(o.Zip) {
		var ret string
		return ret
	}
	return *o.Zip
}

// GetZipOk returns a tuple with the Zip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequestRecipient) GetZipOk() (*string, bool) {
	if o == nil || IsNil(o.Zip) {
		return nil, false
	}
	return o.Zip, true
}

// HasZip returns a boolean if a field has been set.
func (o *BillCreateRequestRecipient) HasZip() bool {
	if o != nil && !IsNil(o.Zip) {
		return true
	}

	return false
}

// SetZip gets a reference to the given string and assigns it to the Zip field.
func (o *BillCreateRequestRecipient) SetZip(v string) {
	o.Zip = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *BillCreateRequestRecipient) GetCity() string {
	if o == nil || IsNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequestRecipient) GetCityOk() (*string, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *BillCreateRequestRecipient) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *BillCreateRequestRecipient) SetCity(v string) {
	o.City = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *BillCreateRequestRecipient) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillCreateRequestRecipient) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *BillCreateRequestRecipient) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *BillCreateRequestRecipient) SetCountry(v string) {
	o.Country = &v
}

// GetEmail returns the Email field value
func (o *BillCreateRequestRecipient) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *BillCreateRequestRecipient) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *BillCreateRequestRecipient) SetEmail(v string) {
	o.Email = v
}

func (o BillCreateRequestRecipient) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillCreateRequestRecipient) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Company) {
		toSerialize["company"] = o.Company
	}
	if !IsNil(o.FirstName) {
		toSerialize["firstName"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["lastName"] = o.LastName
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Zip) {
		toSerialize["zip"] = o.Zip
	}
	if !IsNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *BillCreateRequestRecipient) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillCreateRequestRecipient := _BillCreateRequestRecipient{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillCreateRequestRecipient)

	if err != nil {
		return err
	}

	*o = BillCreateRequestRecipient(varBillCreateRequestRecipient)

	return err
}

type NullableBillCreateRequestRecipient struct {
	value *BillCreateRequestRecipient
	isSet bool
}

func (v NullableBillCreateRequestRecipient) Get() *BillCreateRequestRecipient {
	return v.value
}

func (v *NullableBillCreateRequestRecipient) Set(val *BillCreateRequestRecipient) {
	v.value = val
	v.isSet = true
}

func (v NullableBillCreateRequestRecipient) IsSet() bool {
	return v.isSet
}

func (v *NullableBillCreateRequestRecipient) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillCreateRequestRecipient(val *BillCreateRequestRecipient) *NullableBillCreateRequestRecipient {
	return &NullableBillCreateRequestRecipient{value: val, isSet: true}
}

func (v NullableBillCreateRequestRecipient) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillCreateRequestRecipient) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
