/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the InvoiceBankInformation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoiceBankInformation{}

// InvoiceBankInformation struct for InvoiceBankInformation
type InvoiceBankInformation struct {
	Iban    *string `json:"iban,omitempty"`
	Name    *string `json:"name,omitempty"`
	Address *string `json:"address,omitempty"`
}

// NewInvoiceBankInformation instantiates a new InvoiceBankInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceBankInformation() *InvoiceBankInformation {
	this := InvoiceBankInformation{}
	return &this
}

// NewInvoiceBankInformationWithDefaults instantiates a new InvoiceBankInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceBankInformationWithDefaults() *InvoiceBankInformation {
	this := InvoiceBankInformation{}
	return &this
}

// GetIban returns the Iban field value if set, zero value otherwise.
func (o *InvoiceBankInformation) GetIban() string {
	if o == nil || IsNil(o.Iban) {
		var ret string
		return ret
	}
	return *o.Iban
}

// GetIbanOk returns a tuple with the Iban field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceBankInformation) GetIbanOk() (*string, bool) {
	if o == nil || IsNil(o.Iban) {
		return nil, false
	}
	return o.Iban, true
}

// HasIban returns a boolean if a field has been set.
func (o *InvoiceBankInformation) HasIban() bool {
	if o != nil && !IsNil(o.Iban) {
		return true
	}

	return false
}

// SetIban gets a reference to the given string and assigns it to the Iban field.
func (o *InvoiceBankInformation) SetIban(v string) {
	o.Iban = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InvoiceBankInformation) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceBankInformation) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InvoiceBankInformation) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InvoiceBankInformation) SetName(v string) {
	o.Name = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *InvoiceBankInformation) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceBankInformation) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *InvoiceBankInformation) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *InvoiceBankInformation) SetAddress(v string) {
	o.Address = &v
}

func (o InvoiceBankInformation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoiceBankInformation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Iban) {
		toSerialize["iban"] = o.Iban
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	return toSerialize, nil
}

type NullableInvoiceBankInformation struct {
	value *InvoiceBankInformation
	isSet bool
}

func (v NullableInvoiceBankInformation) Get() *InvoiceBankInformation {
	return v.value
}

func (v *NullableInvoiceBankInformation) Set(val *InvoiceBankInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceBankInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceBankInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceBankInformation(val *InvoiceBankInformation) *NullableInvoiceBankInformation {
	return &NullableInvoiceBankInformation{value: val, isSet: true}
}

func (v NullableInvoiceBankInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceBankInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
