/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the TransactionInvoiceCustomFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionInvoiceCustomFields{}

// TransactionInvoiceCustomFields struct for TransactionInvoiceCustomFields
type TransactionInvoiceCustomFields struct {
	Var20 *TransactionInvoiceCustomFields20 `json:"20,omitempty"`
}

// NewTransactionInvoiceCustomFields instantiates a new TransactionInvoiceCustomFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionInvoiceCustomFields() *TransactionInvoiceCustomFields {
	this := TransactionInvoiceCustomFields{}
	return &this
}

// NewTransactionInvoiceCustomFieldsWithDefaults instantiates a new TransactionInvoiceCustomFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionInvoiceCustomFieldsWithDefaults() *TransactionInvoiceCustomFields {
	this := TransactionInvoiceCustomFields{}
	return &this
}

// GetVar20 returns the Var20 field value if set, zero value otherwise.
func (o *TransactionInvoiceCustomFields) GetVar20() TransactionInvoiceCustomFields20 {
	if o == nil || IsNil(o.Var20) {
		var ret TransactionInvoiceCustomFields20
		return ret
	}
	return *o.Var20
}

// GetVar20Ok returns a tuple with the Var20 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInvoiceCustomFields) GetVar20Ok() (*TransactionInvoiceCustomFields20, bool) {
	if o == nil || IsNil(o.Var20) {
		return nil, false
	}
	return o.Var20, true
}

// HasVar20 returns a boolean if a field has been set.
func (o *TransactionInvoiceCustomFields) HasVar20() bool {
	if o != nil && !IsNil(o.Var20) {
		return true
	}

	return false
}

// SetVar20 gets a reference to the given TransactionInvoiceCustomFields20 and assigns it to the Var20 field.
func (o *TransactionInvoiceCustomFields) SetVar20(v TransactionInvoiceCustomFields20) {
	o.Var20 = &v
}

func (o TransactionInvoiceCustomFields) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionInvoiceCustomFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Var20) {
		toSerialize["20"] = o.Var20
	}
	return toSerialize, nil
}

type NullableTransactionInvoiceCustomFields struct {
	value *TransactionInvoiceCustomFields
	isSet bool
}

func (v NullableTransactionInvoiceCustomFields) Get() *TransactionInvoiceCustomFields {
	return v.value
}

func (v *NullableTransactionInvoiceCustomFields) Set(val *TransactionInvoiceCustomFields) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionInvoiceCustomFields) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionInvoiceCustomFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionInvoiceCustomFields(val *TransactionInvoiceCustomFields) *NullableTransactionInvoiceCustomFields {
	return &NullableTransactionInvoiceCustomFields{value: val, isSet: true}
}

func (v NullableTransactionInvoiceCustomFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionInvoiceCustomFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
