/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the InvoiceDiscount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoiceDiscount{}

// InvoiceDiscount struct for InvoiceDiscount
type InvoiceDiscount struct {
	Amount *int32  `json:"amount,omitempty"`
	Type   *string `json:"type,omitempty"`
}

// NewInvoiceDiscount instantiates a new InvoiceDiscount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceDiscount() *InvoiceDiscount {
	this := InvoiceDiscount{}
	var amount int32 = 0
	this.Amount = &amount
	return &this
}

// NewInvoiceDiscountWithDefaults instantiates a new InvoiceDiscount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceDiscountWithDefaults() *InvoiceDiscount {
	this := InvoiceDiscount{}
	var amount int32 = 0
	this.Amount = &amount
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *InvoiceDiscount) GetAmount() int32 {
	if o == nil || IsNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceDiscount) GetAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *InvoiceDiscount) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *InvoiceDiscount) SetAmount(v int32) {
	o.Amount = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *InvoiceDiscount) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceDiscount) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *InvoiceDiscount) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *InvoiceDiscount) SetType(v string) {
	o.Type = &v
}

func (o InvoiceDiscount) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoiceDiscount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableInvoiceDiscount struct {
	value *InvoiceDiscount
	isSet bool
}

func (v NullableInvoiceDiscount) Get() *InvoiceDiscount {
	return v.value
}

func (v *NullableInvoiceDiscount) Set(val *InvoiceDiscount) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceDiscount) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceDiscount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceDiscount(val *InvoiceDiscount) *NullableInvoiceDiscount {
	return &NullableInvoiceDiscount{value: val, isSet: true}
}

func (v NullableInvoiceDiscount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceDiscount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
