/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TransactionUpdateTokenizationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionUpdateTokenizationRequest{}

// TransactionUpdateTokenizationRequest struct for TransactionUpdateTokenizationRequest
type TransactionUpdateTokenizationRequest struct {
	// Percentage value for new vatRate
	VatRate int32 `json:"vatRate"`
}

type _TransactionUpdateTokenizationRequest TransactionUpdateTokenizationRequest

// NewTransactionUpdateTokenizationRequest instantiates a new TransactionUpdateTokenizationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionUpdateTokenizationRequest(vatRate int32) *TransactionUpdateTokenizationRequest {
	this := TransactionUpdateTokenizationRequest{}
	this.VatRate = vatRate
	return &this
}

// NewTransactionUpdateTokenizationRequestWithDefaults instantiates a new TransactionUpdateTokenizationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionUpdateTokenizationRequestWithDefaults() *TransactionUpdateTokenizationRequest {
	this := TransactionUpdateTokenizationRequest{}
	return &this
}

// GetVatRate returns the VatRate field value
func (o *TransactionUpdateTokenizationRequest) GetVatRate() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.VatRate
}

// GetVatRateOk returns a tuple with the VatRate field value
// and a boolean to check if the value has been set.
func (o *TransactionUpdateTokenizationRequest) GetVatRateOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VatRate, true
}

// SetVatRate sets field value
func (o *TransactionUpdateTokenizationRequest) SetVatRate(v int32) {
	o.VatRate = v
}

func (o TransactionUpdateTokenizationRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionUpdateTokenizationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["vatRate"] = o.VatRate
	return toSerialize, nil
}

func (o *TransactionUpdateTokenizationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"vatRate",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransactionUpdateTokenizationRequest := _TransactionUpdateTokenizationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransactionUpdateTokenizationRequest)

	if err != nil {
		return err
	}

	*o = TransactionUpdateTokenizationRequest(varTransactionUpdateTokenizationRequest)

	return err
}

type NullableTransactionUpdateTokenizationRequest struct {
	value *TransactionUpdateTokenizationRequest
	isSet bool
}

func (v NullableTransactionUpdateTokenizationRequest) Get() *TransactionUpdateTokenizationRequest {
	return v.value
}

func (v *NullableTransactionUpdateTokenizationRequest) Set(val *TransactionUpdateTokenizationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionUpdateTokenizationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionUpdateTokenizationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionUpdateTokenizationRequest(val *TransactionUpdateTokenizationRequest) *NullableTransactionUpdateTokenizationRequest {
	return &NullableTransactionUpdateTokenizationRequest{value: val, isSet: true}
}

func (v NullableTransactionUpdateTokenizationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionUpdateTokenizationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
