/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the InvoiceCashDiscountsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoiceCashDiscountsInner{}

// InvoiceCashDiscountsInner struct for InvoiceCashDiscountsInner
type InvoiceCashDiscountsInner struct {
	Days    *int32 `json:"days,omitempty"`
	Percent *int32 `json:"percent,omitempty"`
}

// NewInvoiceCashDiscountsInner instantiates a new InvoiceCashDiscountsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceCashDiscountsInner() *InvoiceCashDiscountsInner {
	this := InvoiceCashDiscountsInner{}
	var days int32 = 0
	this.Days = &days
	var percent int32 = 0
	this.Percent = &percent
	return &this
}

// NewInvoiceCashDiscountsInnerWithDefaults instantiates a new InvoiceCashDiscountsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceCashDiscountsInnerWithDefaults() *InvoiceCashDiscountsInner {
	this := InvoiceCashDiscountsInner{}
	var days int32 = 0
	this.Days = &days
	var percent int32 = 0
	this.Percent = &percent
	return &this
}

// GetDays returns the Days field value if set, zero value otherwise.
func (o *InvoiceCashDiscountsInner) GetDays() int32 {
	if o == nil || IsNil(o.Days) {
		var ret int32
		return ret
	}
	return *o.Days
}

// GetDaysOk returns a tuple with the Days field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCashDiscountsInner) GetDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.Days) {
		return nil, false
	}
	return o.Days, true
}

// HasDays returns a boolean if a field has been set.
func (o *InvoiceCashDiscountsInner) HasDays() bool {
	if o != nil && !IsNil(o.Days) {
		return true
	}

	return false
}

// SetDays gets a reference to the given int32 and assigns it to the Days field.
func (o *InvoiceCashDiscountsInner) SetDays(v int32) {
	o.Days = &v
}

// GetPercent returns the Percent field value if set, zero value otherwise.
func (o *InvoiceCashDiscountsInner) GetPercent() int32 {
	if o == nil || IsNil(o.Percent) {
		var ret int32
		return ret
	}
	return *o.Percent
}

// GetPercentOk returns a tuple with the Percent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceCashDiscountsInner) GetPercentOk() (*int32, bool) {
	if o == nil || IsNil(o.Percent) {
		return nil, false
	}
	return o.Percent, true
}

// HasPercent returns a boolean if a field has been set.
func (o *InvoiceCashDiscountsInner) HasPercent() bool {
	if o != nil && !IsNil(o.Percent) {
		return true
	}

	return false
}

// SetPercent gets a reference to the given int32 and assigns it to the Percent field.
func (o *InvoiceCashDiscountsInner) SetPercent(v int32) {
	o.Percent = &v
}

func (o InvoiceCashDiscountsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoiceCashDiscountsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Days) {
		toSerialize["days"] = o.Days
	}
	if !IsNil(o.Percent) {
		toSerialize["percent"] = o.Percent
	}
	return toSerialize, nil
}

type NullableInvoiceCashDiscountsInner struct {
	value *InvoiceCashDiscountsInner
	isSet bool
}

func (v NullableInvoiceCashDiscountsInner) Get() *InvoiceCashDiscountsInner {
	return v.value
}

func (v *NullableInvoiceCashDiscountsInner) Set(val *InvoiceCashDiscountsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceCashDiscountsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceCashDiscountsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceCashDiscountsInner(val *InvoiceCashDiscountsInner) *NullableInvoiceCashDiscountsInner {
	return &NullableInvoiceCashDiscountsInner{value: val, isSet: true}
}

func (v NullableInvoiceCashDiscountsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceCashDiscountsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
