/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the PaylinkFieldsCustomField1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaylinkFieldsCustomField1{}

// PaylinkFieldsCustomField1 struct for PaylinkFieldsCustomField1
type PaylinkFieldsCustomField1 struct {
	Active    *bool                           `json:"active,omitempty"`
	Mandatory *bool                           `json:"mandatory,omitempty"`
	Names     *PaylinkFieldsCustomField1Names `json:"names,omitempty"`
}

// NewPaylinkFieldsCustomField1 instantiates a new PaylinkFieldsCustomField1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaylinkFieldsCustomField1() *PaylinkFieldsCustomField1 {
	this := PaylinkFieldsCustomField1{}
	var active bool = true
	this.Active = &active
	var mandatory bool = true
	this.Mandatory = &mandatory
	return &this
}

// NewPaylinkFieldsCustomField1WithDefaults instantiates a new PaylinkFieldsCustomField1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaylinkFieldsCustomField1WithDefaults() *PaylinkFieldsCustomField1 {
	this := PaylinkFieldsCustomField1{}
	var active bool = true
	this.Active = &active
	var mandatory bool = true
	this.Mandatory = &mandatory
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *PaylinkFieldsCustomField1) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaylinkFieldsCustomField1) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *PaylinkFieldsCustomField1) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *PaylinkFieldsCustomField1) SetActive(v bool) {
	o.Active = &v
}

// GetMandatory returns the Mandatory field value if set, zero value otherwise.
func (o *PaylinkFieldsCustomField1) GetMandatory() bool {
	if o == nil || IsNil(o.Mandatory) {
		var ret bool
		return ret
	}
	return *o.Mandatory
}

// GetMandatoryOk returns a tuple with the Mandatory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaylinkFieldsCustomField1) GetMandatoryOk() (*bool, bool) {
	if o == nil || IsNil(o.Mandatory) {
		return nil, false
	}
	return o.Mandatory, true
}

// HasMandatory returns a boolean if a field has been set.
func (o *PaylinkFieldsCustomField1) HasMandatory() bool {
	if o != nil && !IsNil(o.Mandatory) {
		return true
	}

	return false
}

// SetMandatory gets a reference to the given bool and assigns it to the Mandatory field.
func (o *PaylinkFieldsCustomField1) SetMandatory(v bool) {
	o.Mandatory = &v
}

// GetNames returns the Names field value if set, zero value otherwise.
func (o *PaylinkFieldsCustomField1) GetNames() PaylinkFieldsCustomField1Names {
	if o == nil || IsNil(o.Names) {
		var ret PaylinkFieldsCustomField1Names
		return ret
	}
	return *o.Names
}

// GetNamesOk returns a tuple with the Names field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaylinkFieldsCustomField1) GetNamesOk() (*PaylinkFieldsCustomField1Names, bool) {
	if o == nil || IsNil(o.Names) {
		return nil, false
	}
	return o.Names, true
}

// HasNames returns a boolean if a field has been set.
func (o *PaylinkFieldsCustomField1) HasNames() bool {
	if o != nil && !IsNil(o.Names) {
		return true
	}

	return false
}

// SetNames gets a reference to the given PaylinkFieldsCustomField1Names and assigns it to the Names field.
func (o *PaylinkFieldsCustomField1) SetNames(v PaylinkFieldsCustomField1Names) {
	o.Names = &v
}

func (o PaylinkFieldsCustomField1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaylinkFieldsCustomField1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Mandatory) {
		toSerialize["mandatory"] = o.Mandatory
	}
	if !IsNil(o.Names) {
		toSerialize["names"] = o.Names
	}
	return toSerialize, nil
}

type NullablePaylinkFieldsCustomField1 struct {
	value *PaylinkFieldsCustomField1
	isSet bool
}

func (v NullablePaylinkFieldsCustomField1) Get() *PaylinkFieldsCustomField1 {
	return v.value
}

func (v *NullablePaylinkFieldsCustomField1) Set(val *PaylinkFieldsCustomField1) {
	v.value = val
	v.isSet = true
}

func (v NullablePaylinkFieldsCustomField1) IsSet() bool {
	return v.isSet
}

func (v *NullablePaylinkFieldsCustomField1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaylinkFieldsCustomField1(val *PaylinkFieldsCustomField1) *NullablePaylinkFieldsCustomField1 {
	return &NullablePaylinkFieldsCustomField1{value: val, isSet: true}
}

func (v NullablePaylinkFieldsCustomField1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaylinkFieldsCustomField1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
