/*
Payrexx REST API

Assembled by scripts/build_spec.py from the per-endpoint OpenAPI fragments published on developers.payrexx.com. Not an official Payrexx artefact.

API version: 1.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrexx

import (
	"encoding/json"
)

// checks if the TransactionList200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionList200Response{}

// TransactionList200Response struct for TransactionList200Response
type TransactionList200Response struct {
	Status *string       `json:"status,omitempty"`
	Data   []Transaction `json:"data,omitempty"`
}

// NewTransactionList200Response instantiates a new TransactionList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionList200Response() *TransactionList200Response {
	this := TransactionList200Response{}
	return &this
}

// NewTransactionList200ResponseWithDefaults instantiates a new TransactionList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionList200ResponseWithDefaults() *TransactionList200Response {
	this := TransactionList200Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TransactionList200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionList200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TransactionList200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *TransactionList200Response) SetStatus(v string) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *TransactionList200Response) GetData() []Transaction {
	if o == nil || IsNil(o.Data) {
		var ret []Transaction
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionList200Response) GetDataOk() ([]Transaction, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *TransactionList200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Transaction and assigns it to the Data field.
func (o *TransactionList200Response) SetData(v []Transaction) {
	o.Data = v
}

func (o TransactionList200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionList200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableTransactionList200Response struct {
	value *TransactionList200Response
	isSet bool
}

func (v NullableTransactionList200Response) Get() *TransactionList200Response {
	return v.value
}

func (v *NullableTransactionList200Response) Set(val *TransactionList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionList200Response(val *TransactionList200Response) *NullableTransactionList200Response {
	return &NullableTransactionList200Response{value: val, isSet: true}
}

func (v NullableTransactionList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
